#!/usr/bin/env python3
"""Build vocab_it.json from curated word lists + italian_morph.py.

Same generated-data contract as the Latin deck: edit the lists here, re-run,
then rebuild + validate the trainer. Do not hand-edit vocab_it.json.
"""
import json, os, sys, collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from italian_morph import noun_forms, conjugate, decline_adjective, pluralize

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'vocab_it.json')

# ---------------------------------------------------------------------------
# NOUNS: (word, gender, English, lesson[, explicit plural])
# The plural is generated; give it explicitly only to assert a curated form.
# ---------------------------------------------------------------------------
NOUNS = [
    # L1 basics, people & family
    ("uomo", "m", "man", "1"), ("donna", "f", "woman", "1"),
    ("ragazzo", "m", "boy", "1"), ("ragazza", "f", "girl", "1"),
    ("bambino", "m", "child, little boy", "1"), ("bambina", "f", "little girl", "1"),
    ("persona", "f", "person", "1"), ("gente", "f", "people", "1"),
    ("famiglia", "f", "family", "1"), ("padre", "m", "father", "1"),
    ("madre", "f", "mother", "1"), ("figlio", "m", "son", "1"),
    ("figlia", "f", "daughter", "1"), ("fratello", "m", "brother", "1"),
    ("sorella", "f", "sister", "1"), ("nonno", "m", "grandfather", "1"),
    ("nonna", "f", "grandmother", "1"), ("zio", "m", "uncle", "1", "zii"),
    ("zia", "f", "aunt", "1"), ("cugino", "m", "cousin", "1"),
    ("marito", "m", "husband", "1"), ("moglie", "f", "wife", "1", "mogli"),
    ("amico", "m", "friend", "1"), ("amica", "f", "friend (female)", "1"),
    ("nome", "m", "name", "1"), ("cognome", "m", "surname", "1"),
    ("signore", "m", "gentleman, Mr", "1"), ("signora", "f", "lady, Mrs", "1"),
    ("vicino", "m", "neighbour", "1"), ("collega", "m", "colleague", "1", "colleghi"),
    ("vita", "f", "life", "1"), ("mondo", "m", "world", "1"),
    ("cosa", "f", "thing", "1"), ("parte", "f", "part", "1"),
    ("modo", "m", "way, manner", "1"), ("problema", "m", "problem", "1"),
    ("domanda", "f", "question", "1"), ("risposta", "f", "answer", "1"),
    ("parola", "f", "word", "1"), ("idea", "f", "idea", "1"),
    # L2 house & home
    ("casa", "f", "house, home", "2"), ("appartamento", "m", "flat, apartment", "2"),
    ("stanza", "f", "room", "2"), ("camera", "f", "bedroom, room", "2"),
    ("cucina", "f", "kitchen", "2"), ("bagno", "m", "bathroom", "2"),
    ("salotto", "m", "living room", "2"), ("giardino", "m", "garden", "2"),
    ("porta", "f", "door", "2"), ("finestra", "f", "window", "2"),
    ("muro", "m", "wall", "2"), ("pavimento", "m", "floor", "2"),
    ("tetto", "m", "roof", "2"), ("scala", "f", "stairs, ladder", "2"),
    ("tavolo", "m", "table", "2"), ("sedia", "f", "chair", "2"),
    ("letto", "m", "bed", "2"), ("divano", "m", "sofa", "2"),
    ("armadio", "m", "wardrobe", "2"), ("specchio", "m", "mirror", "2"),
    ("lampada", "f", "lamp", "2"), ("chiave", "f", "key", "2"),
    ("frigorifero", "m", "fridge", "2"), ("piatto", "m", "plate, dish", "2"),
    ("bicchiere", "m", "glass", "2"), ("tazza", "f", "cup", "2"),
    ("forchetta", "f", "fork", "2"), ("coltello", "m", "knife", "2"),
    ("cucchiaio", "m", "spoon", "2"), ("bottiglia", "f", "bottle", "2"),
    # L3 numbers, time & calendar
    ("tempo", "m", "time, weather", "3"), ("ora", "f", "hour, time", "3"),
    ("minuto", "m", "minute", "3"), ("secondo", "m", "second", "3"),
    ("giorno", "m", "day", "3"), ("settimana", "f", "week", "3"),
    ("mese", "m", "month", "3"), ("anno", "m", "year", "3"),
    ("mattina", "f", "morning", "3"), ("pomeriggio", "m", "afternoon", "3"),
    ("sera", "f", "evening", "3"), ("notte", "f", "night", "3"),
    ("orologio", "m", "clock, watch", "3"),
    ("data", "f", "date", "3"), ("compleanno", "m", "birthday", "3"),
    ("festa", "f", "party, holiday", "3"), ("vacanza", "f", "holiday, vacation", "3"),
    ("lunedì", "m", "Monday", "3"), ("martedì", "m", "Tuesday", "3"),
    ("mercoledì", "m", "Wednesday", "3"), ("giovedì", "m", "Thursday", "3"),
    ("venerdì", "m", "Friday", "3"), ("sabato", "m", "Saturday", "3"),
    ("domenica", "f", "Sunday", "3"),
    # L4 food & drink
    ("cibo", "m", "food", "4"), ("acqua", "f", "water", "4"),
    ("pane", "m", "bread", "4"), ("pasta", "f", "pasta", "4"),
    ("pizza", "f", "pizza", "4"), ("riso", "m", "rice", "4"),
    ("carne", "f", "meat", "4"), ("pesce", "m", "fish", "4"),
    ("pollo", "m", "chicken", "4"), ("uovo", "m", "egg", "4"),
    ("formaggio", "m", "cheese", "4"), ("latte", "m", "milk", "4"),
    ("burro", "m", "butter", "4"), ("zucchero", "m", "sugar", "4"),
    ("sale", "m", "salt", "4"), ("olio", "m", "oil", "4"),
    ("frutta", "f", "fruit", "4"), ("mela", "f", "apple", "4"),
    ("arancia", "f", "orange", "4"), ("banana", "f", "banana", "4"),
    ("verdura", "f", "vegetables", "4"), ("insalata", "f", "salad", "4"),
    ("patata", "f", "potato", "4"), ("pomodoro", "m", "tomato", "4"),
    ("caffè", "m", "coffee", "4"), ("tè", "m", "tea", "4"),
    ("vino", "m", "wine", "4"), ("birra", "f", "beer", "4"),
    ("dolce", "m", "dessert, sweet", "4"), ("gelato", "m", "ice cream", "4"),
    ("colazione", "f", "breakfast", "4"), ("pranzo", "m", "lunch", "4"),
    ("cena", "f", "dinner", "4"), ("ristorante", "m", "restaurant", "4"),
    ("conto", "m", "bill, account", "4"), ("cameriere", "m", "waiter", "4"),
    ("menu", "m", "menu", "4"), ("fame", "f", "hunger", "4"),
    ("sete", "f", "thirst", "4"),
    # L5 town & places
    ("città", "f", "city, town", "5"), ("paese", "m", "country, village", "5"),
    ("via", "f", "street, way", "5"), ("strada", "f", "road, street", "5"),
    ("piazza", "f", "square", "5"), ("negozio", "m", "shop", "5"),
    ("mercato", "m", "market", "5"), ("banca", "f", "bank", "5"),
    ("chiesa", "f", "church", "5"), ("scuola", "f", "school", "5"),
    ("ospedale", "m", "hospital", "5"), ("albergo", "m", "hotel", "5"),
    ("museo", "m", "museum", "5"), ("teatro", "m", "theatre", "5"),
    ("cinema", "m", "cinema", "5"), ("parco", "m", "park", "5"),
    ("ponte", "m", "bridge", "5"), ("stazione", "f", "station", "5"),
    ("aeroporto", "m", "airport", "5"), ("porto", "m", "port, harbour", "5"),
    ("ufficio", "m", "office", "5"), ("posto", "m", "place, seat", "5"),
    ("centro", "m", "centre", "5"), ("angolo", "m", "corner", "5"),
    ("edificio", "m", "building", "5"), ("palazzo", "m", "building, palace", "5"),
    ("biblioteca", "f", "library", "5"), ("farmacia", "f", "pharmacy", "5"),
    # L6 travel & transport
    ("viaggio", "m", "journey, trip", "6"), ("treno", "m", "train", "6"),
    ("macchina", "f", "car, machine", "6"), ("autobus", "m", "bus", "6"),
    ("aereo", "m", "aeroplane", "6"), ("nave", "f", "ship", "6"),
    ("bicicletta", "f", "bicycle", "6"), ("moto", "f", "motorbike", "6"),
    ("biglietto", "m", "ticket", "6"), ("valigia", "f", "suitcase", "6"),
    ("passaporto", "m", "passport", "6"), ("mappa", "f", "map", "6"),
    ("volo", "m", "flight", "6"), ("ritardo", "m", "delay", "6"),
    ("partenza", "f", "departure", "6"), ("arrivo", "m", "arrival", "6"),
    ("benzina", "f", "petrol", "6"), ("patente", "f", "driving licence", "6"),
    # L7 work & school
    ("lavoro", "m", "work, job", "7"), ("studio", "m", "study, office", "7"),
    ("studente", "m", "student", "7"), ("insegnante", "m", "teacher", "7"),
    ("professore", "m", "professor, teacher", "7"), ("medico", "m", "doctor", "7"),
    ("avvocato", "m", "lawyer", "7"), ("operaio", "m", "worker", "7"),
    ("impiegato", "m", "employee, clerk", "7"), ("direttore", "m", "director, manager", "7"),
    ("azienda", "f", "company, firm", "7"), ("libro", "m", "book", "7"),
    ("quaderno", "m", "notebook", "7"), ("penna", "f", "pen", "7"),
    ("matita", "f", "pencil", "7"), ("foglio", "m", "sheet of paper", "7"),
    ("lezione", "f", "lesson", "7"), ("esame", "m", "exam", "7"),
    ("corso", "m", "course", "7"), ("compito", "m", "homework, task", "7"),
    ("classe", "f", "class, classroom", "7"), ("voto", "m", "mark, grade, vote", "7"),
    ("stipendio", "m", "salary", "7"), ("riunione", "f", "meeting", "7"),
    ("progetto", "m", "project", "7"),
    # L8 body & health
    ("corpo", "m", "body", "8"), ("testa", "f", "head", "8"),
    ("capello", "m", "hair (single)", "8"), ("occhio", "m", "eye", "8"),
    ("orecchio", "m", "ear", "8"), ("naso", "m", "nose", "8"),
    ("bocca", "f", "mouth", "8", "bocche"), ("dente", "m", "tooth", "8"),
    ("collo", "m", "neck", "8"), ("spalla", "f", "shoulder", "8"),
    ("braccio", "m", "arm", "8"), ("mano", "f", "hand", "8", "mani"),
    ("dito", "m", "finger", "8"), ("gamba", "f", "leg", "8"),
    ("piede", "m", "foot", "8"), ("cuore", "m", "heart", "8"),
    ("schiena", "f", "back", "8"), ("stomaco", "m", "stomach", "8", "stomaci"),
    ("salute", "f", "health", "8"), ("malattia", "f", "illness", "8"),
    ("dolore", "m", "pain", "8"), ("febbre", "f", "fever", "8"),
    ("medicina", "f", "medicine", "8"), ("sangue", "m", "blood", "8"),
    # L9 clothes & shopping
    ("vestito", "m", "dress, suit", "9"), ("camicia", "f", "shirt", "9"),
    ("gonna", "f", "skirt", "9"), ("prezzo", "m", "price", "9"),
    ("giacca", "f", "jacket", "9"), ("cappotto", "m", "coat", "9"),
    ("maglione", "m", "jumper, sweater", "9"), ("scarpa", "f", "shoe", "9"),
    ("calza", "f", "sock, stocking", "9"), ("cappello", "m", "hat", "9"),
    ("borsa", "f", "bag", "9"), ("cintura", "f", "belt", "9"),
    ("denaro", "m", "money", "9"), ("carta", "f", "card, paper", "9"),
    ("saldo", "m", "sale, balance", "9"), ("taglia", "f", "size", "9"),
    ("regalo", "m", "present, gift", "9"),
    # L10 nature & weather
    ("natura", "f", "nature", "10"), ("cielo", "m", "sky", "10"),
    ("sole", "m", "sun", "10"), ("luna", "f", "moon", "10"),
    ("stella", "f", "star", "10"), ("nuvola", "f", "cloud", "10"),
    ("pioggia", "f", "rain", "10"), ("neve", "f", "snow", "10"),
    ("vento", "m", "wind", "10"), ("mare", "m", "sea", "10"),
    ("lago", "m", "lake", "10"), ("fiume", "m", "river", "10"),
    ("montagna", "f", "mountain", "10"), ("collina", "f", "hill", "10"),
    ("campagna", "f", "countryside", "10"), ("bosco", "m", "wood, forest", "10"),
    ("albero", "m", "tree", "10"), ("fiore", "m", "flower", "10"),
    ("foglia", "f", "leaf", "10"), ("erba", "f", "grass", "10"),
    ("terra", "f", "earth, land", "10"), ("pietra", "f", "stone", "10"),
    ("sabbia", "f", "sand", "10"), ("fuoco", "m", "fire", "10"),
    ("aria", "f", "air", "10"), ("isola", "f", "island", "10"),
    ("spiaggia", "f", "beach", "10"), ("stagione", "f", "season", "10"),
    ("primavera", "f", "spring", "10"), ("estate", "f", "summer", "10"),
    ("autunno", "m", "autumn", "10"), ("inverno", "m", "winter", "10"),
    # L11 animals
    ("animale", "m", "animal", "11"), ("cane", "m", "dog", "11"),
    ("gatto", "m", "cat", "11"), ("cavallo", "m", "horse", "11"),
    ("mucca", "f", "cow", "11"), ("pecora", "f", "sheep", "11"),
    ("maiale", "m", "pig", "11"), ("uccello", "m", "bird", "11"),
    ("topo", "m", "mouse", "11"), ("insetto", "m", "insect", "11"),
    ("ape", "f", "bee", "11"), ("farfalla", "f", "butterfly", "11"),
    ("leone", "m", "lion", "11"), ("lupo", "m", "wolf", "11"),
    ("orso", "m", "bear", "11"), ("coda", "f", "tail", "11"),
    # L12 free time & media
    ("musica", "f", "music", "12"), ("canzone", "f", "song", "12"),
    ("giornale", "m", "newspaper", "12"),
    ("rivista", "f", "magazine", "12"), ("televisione", "f", "television", "12"),
    ("radio", "f", "radio", "12"), ("telefono", "m", "telephone", "12"),
    ("computer", "m", "computer", "12"), ("gioco", "m", "game", "12"),
    ("sport", "m", "sport", "12"), ("partita", "f", "match, game", "12"),
    ("squadra", "f", "team", "12"), ("palla", "f", "ball", "12"),
    ("corsa", "f", "race, run", "12"), ("nuoto", "m", "swimming", "12"),
    ("foto", "f", "photo", "12"), ("quadro", "m", "picture, painting", "12"),
    ("storia", "f", "story, history", "12"), ("notizia", "f", "news item", "12"),
    ("messaggio", "m", "message", "12"), ("lettera", "f", "letter", "12"),
    ("numero", "m", "number", "12"), ("colore", "m", "colour", "12"),
    # L13 abstract & feelings
    ("amore", "m", "love", "13"), ("odio", "m", "hatred", "13"),
    ("paura", "f", "fear", "13"), ("gioia", "f", "joy", "13"),
    ("tristezza", "f", "sadness", "13"), ("rabbia", "f", "anger", "13"),
    ("speranza", "f", "hope", "13"), ("sogno", "m", "dream", "13"),
    ("verità", "f", "truth", "13"), ("bugia", "f", "lie", "13"),
    ("forza", "f", "strength, force", "13"), ("coraggio", "m", "courage", "13"),
    ("pace", "f", "peace", "13"), ("guerra", "f", "war", "13"),
    ("libertà", "f", "freedom", "13"), ("diritto", "m", "right, law", "13"),
    ("legge", "f", "law", "13"), ("governo", "m", "government", "13"),
    ("società", "f", "society", "13"), ("gruppo", "m", "group", "13"),
    ("gara", "f", "competition", "13"),
    ("errore", "m", "mistake", "13"), ("successo", "m", "success", "13"),
    ("fine", "f", "end", "13"), ("inizio", "m", "beginning", "13"),
    ("ragione", "f", "reason", "13"), ("motivo", "m", "reason, motive", "13"),
    ("esempio", "m", "example", "13"), ("differenza", "f", "difference", "13"),
    ("possibilità", "f", "possibility", "13"), ("occasione", "f", "occasion, chance", "13"),
    ("bisogno", "m", "need", "13"), ("aiuto", "m", "help", "13"),
    ("consiglio", "m", "advice", "13"), ("scelta", "f", "choice", "13"),
    ("cambiamento", "m", "change", "13"), ("silenzio", "m", "silence", "13"),
    ("rumore", "m", "noise", "13"), ("voce", "f", "voice", "13"),

    # === batch 2 ==========================================================
    ("zaino", "m", "backpack", "9"), ("ombrello", "m", "umbrella", "9"),
    ("guanto", "m", "glove", "9"), ("sciarpa", "f", "scarf", "9"),
    ("maglietta", "f", "T-shirt", "9"), ("pigiama", "m", "pyjamas", "9"),
    ("costume", "m", "costume, swimsuit", "9"), ("asciugamano", "m", "towel", "9"),
    ("sapone", "m", "soap", "9"), ("spazzolino", "m", "toothbrush", "9"),
    ("pettine", "m", "comb", "9"), ("profumo", "m", "perfume", "9"),
    ("portafoglio", "m", "wallet", "9"), ("moneta", "f", "coin", "9"),
    ("banconota", "f", "banknote", "9"), ("scontrino", "m", "receipt", "9"),
    ("sconto", "m", "discount", "9"), ("offerta", "f", "offer", "9"),
    ("cliente", "m", "customer", "9"), ("vetrina", "f", "shop window", "9"),
    ("cassetto", "m", "drawer", "2"), ("scaffale", "m", "shelf", "2"),
    ("tenda", "f", "curtain, tent", "2"), ("tappeto", "m", "carpet, rug", "2"),
    ("cuscino", "m", "cushion, pillow", "2"), ("coperta", "f", "blanket", "2"),
    ("cantina", "f", "cellar", "2"), ("garage", "m", "garage", "2"),
    ("cortile", "m", "courtyard", "2"), ("balcone", "m", "balcony", "2"),
    ("terrazza", "f", "terrace", "2"), ("ascensore", "m", "lift, elevator", "2"),
    ("corridoio", "m", "corridor", "2"), ("ingresso", "m", "entrance", "2"),
    ("padella", "f", "frying pan", "2"), ("pentola", "f", "pot, saucepan", "2"),
    ("forno", "m", "oven", "2"), ("lavatrice", "f", "washing machine", "2"),
    ("zucchina", "f", "courgette", "4"), ("melanzana", "f", "aubergine", "4"),
    ("peperone", "m", "pepper (vegetable)", "4"), ("cipolla", "f", "onion", "4"),
    ("aglio", "m", "garlic", "4"), ("carota", "f", "carrot", "4"),
    ("fagiolo", "m", "bean", "4"), ("pisello", "m", "pea", "4"),
    ("fragola", "f", "strawberry", "4"), ("pera", "f", "pear", "4"),
    ("pesca", "f", "peach, fishing", "4"), ("uva", "f", "grapes", "4"),
    ("limone", "m", "lemon", "4"), ("melone", "m", "melon", "4"),
    ("prosciutto", "m", "ham", "4"), ("salame", "m", "salami", "4"),
    ("salsiccia", "f", "sausage", "4"), ("bistecca", "f", "steak", "4"),
    ("panino", "m", "bread roll, sandwich", "4"), ("torta", "f", "cake, pie", "4"),
    ("biscotto", "m", "biscuit", "4"), ("cioccolato", "m", "chocolate", "4"),
    ("marmellata", "f", "jam", "4"), ("succo", "m", "juice", "4"),
    ("bibita", "f", "soft drink", "4"), ("ghiaccio", "m", "ice", "4"),
    ("cameriera", "f", "waitress", "7"), ("panettiere", "m", "baker", "7"),
    ("macellaio", "m", "butcher", "7"), ("commesso", "m", "shop assistant", "7"),
    ("postino", "m", "postman", "7"), ("poliziotto", "m", "policeman", "7"),
    ("infermiere", "m", "nurse", "7"), ("dentista", "m", "dentist", "7"),
    ("ingegnere", "m", "engineer", "7"), ("architetto", "m", "architect", "7"),
    ("giornalista", "m", "journalist", "7"), ("attore", "m", "actor", "7"),
    ("cantante", "m", "singer", "7"), ("pittore", "m", "painter", "7"),
    ("scrittore", "m", "writer", "7"), ("contadino", "m", "farmer", "7"),
    ("soldato", "m", "soldier", "7"), ("sindaco", "m", "mayor", "7", "sindaci"),
    ("semaforo", "m", "traffic light", "6"), ("incrocio", "m", "crossroads", "6"),
    ("marciapiede", "m", "pavement", "6"), ("parcheggio", "m", "car park", "6"),
    ("autostrada", "f", "motorway", "6"), ("motore", "m", "engine", "6"),
    ("volante", "m", "steering wheel", "6"), ("freno", "m", "brake", "6"),
    ("sedile", "m", "seat", "6"), ("finestrino", "m", "car/train window", "6"),
    ("targa", "f", "number plate", "6"), ("binario", "m", "platform, track", "6"),
    ("carrozza", "f", "carriage", "6"), ("controllore", "m", "ticket inspector", "6"),
    ("orario", "m", "timetable, schedule", "6"), ("coincidenza", "f", "connection", "6"),
    ("sciopero", "m", "strike", "6"), ("bagaglio", "m", "luggage", "6"),
    ("dogana", "f", "customs", "6"), ("confine", "m", "border", "6"),
    ("campeggio", "m", "campsite", "6"), ("bussola", "f", "compass", "6"),
    ("tosse", "f", "cough", "8"), ("raffreddore", "m", "cold (illness)", "8"),
    ("influenza", "f", "flu, influence", "8"), ("allergia", "f", "allergy", "8"),
    ("ferita", "f", "wound, injury", "8"), ("cerotto", "m", "plaster", "8"),
    ("pillola", "f", "pill", "8"), ("sciroppo", "m", "syrup", "8"),
    ("iniezione", "f", "injection", "8"), ("visita", "f", "visit, examination", "8"),
    ("ricetta", "f", "recipe, prescription", "8"), ("terapia", "f", "therapy", "8"),
    ("cura", "f", "care, treatment", "8"),
    ("mente", "f", "mind", "13"), ("anima", "f", "soul", "13"),
    ("carattere", "m", "character", "13"), ("abitudine", "f", "habit", "13"),
    ("comportamento", "m", "behaviour", "13"), ("educazione", "f", "education, manners", "13"),
    ("esperienza", "f", "experience", "13"), ("conoscenza", "f", "knowledge", "13"),
    ("intelligenza", "f", "intelligence", "13"), ("fantasia", "f", "imagination", "13"),
    ("curiosità", "f", "curiosity", "13"), ("pazienza", "f", "patience", "13"),
    ("fiducia", "f", "trust", "13"), ("rispetto", "m", "respect", "13"),
    ("orgoglio", "m", "pride", "13"), ("vergogna", "f", "shame", "13"),
    ("colpa", "f", "fault, guilt", "13"), ("perdono", "m", "forgiveness", "13"),
    ("promessa", "f", "promise", "13"), ("segreto", "m", "secret", "13"),
    ("scherzo", "m", "joke", "13"), ("sorpresa", "f", "surprise", "13"),
    ("desiderio", "m", "wish, desire", "13"), ("opinione", "f", "opinion", "13"),
    ("discussione", "f", "discussion", "13"), ("accordo", "m", "agreement", "13"),
    ("soluzione", "f", "solution", "13"), ("risultato", "m", "result", "13"),
    ("conseguenza", "f", "consequence", "13"), ("regola", "f", "rule", "13"),
    ("ordine", "m", "order", "13"), ("confusione", "f", "confusion", "13"),
    ("attenzione", "f", "attention", "13"), ("sforzo", "m", "effort", "13"),
    ("fatica", "f", "effort, fatigue", "13"), ("riposo", "m", "rest", "13"),
    ("sonno", "m", "sleep, sleepiness", "13"), ("impegno", "m", "commitment", "13"),
    ("responsabilità", "f", "responsibility", "13"),
    ("memoria", "f", "memory", "13"), ("passo", "m", "step, pace", "13"),
    ("livello", "m", "level", "13"), ("qualità", "f", "quality", "13"),
    ("quantità", "f", "quantity", "13"), ("misura", "f", "measure, size", "13"),
    ("peso", "m", "weight", "13"), ("altezza", "f", "height", "13"),
    ("larghezza", "f", "width", "13"), ("distanza", "f", "distance", "13"),
    ("velocità", "f", "speed", "13"), ("direzione", "f", "direction", "13"),
    ("posizione", "f", "position", "13"), ("situazione", "f", "situation", "13"),
    ("condizione", "f", "condition", "13"), ("effetto", "m", "effect", "13"),
    ("causa", "f", "cause", "13"), ("scopo", "m", "purpose, aim", "13"),
    ("piano", "m", "floor, plan", "13"),
    ("sistema", "m", "system", "13"), ("metodo", "m", "method", "13"),
    ("tipo", "m", "type, kind", "13"), ("forma", "f", "shape, form", "13"),
    ("valore", "m", "value", "13"), ("costo", "m", "cost", "13"),
]

# ---------------------------------------------------------------------------
# VERBS: (infinitive, English, lesson[, isc])
# ---------------------------------------------------------------------------
VERBS = [
    ("essere", "to be", "14"), ("avere", "to have", "14"),
    ("stare", "to stay, be (health)", "14"), ("fare", "to do, make", "14"),
    ("andare", "to go", "14"), ("venire", "to come", "14"),
    ("dare", "to give", "14"), ("dire", "to say, tell", "14"),
    ("potere", "to be able, can", "14"), ("volere", "to want", "14"),
    ("dovere", "to have to, must", "14"), ("sapere", "to know (a fact)", "14"),
    ("conoscere", "to know (a person), meet", "14"),
    ("parlare", "to speak, talk", "14"), ("ascoltare", "to listen to", "14"),
    ("sentire", "to hear, feel", "14"), ("guardare", "to look at, watch", "14"),
    ("vedere", "to see", "14"), ("leggere", "to read", "14"),
    ("scrivere", "to write", "14"), ("studiare", "to study", "14"),
    ("imparare", "to learn", "14"), ("insegnare", "to teach", "14"),
    ("capire", "to understand", "14", True), ("finire", "to finish", "14", True),
    ("preferire", "to prefer", "14", True), ("pulire", "to clean", "14", True),
    ("spedire", "to send, post", "14", True), ("costruire", "to build", "14", True),
    ("mangiare", "to eat", "14"), ("bere", "to drink", "14"),
    ("cucinare", "to cook", "14"), ("comprare", "to buy", "14"),
    ("vendere", "to sell", "14"), ("pagare", "to pay", "14"),
    ("costare", "to cost", "14"), ("spendere", "to spend", "14"),
    ("lavorare", "to work", "14"), ("giocare", "to play (a game)", "14"),
    ("suonare", "to play (an instrument), ring", "14"),
    ("cantare", "to sing", "14"), ("ballare", "to dance", "14"),
    ("correre", "to run", "14"), ("camminare", "to walk", "14"),
    ("nuotare", "to swim", "14"), ("viaggiare", "to travel", "14"),
    ("partire", "to leave, depart", "14"), ("arrivare", "to arrive", "14"),
    ("tornare", "to return, go back", "14"), ("entrare", "to enter", "14"),
    ("uscire", "to go out", "14"), ("salire", "to go up, get on", "14"),
    ("scendere", "to go down, get off", "14"), ("cadere", "to fall", "14"),
    ("restare", "to stay, remain", "14"), ("rimanere", "to remain", "14"),
    ("aprire", "to open", "15"), ("chiudere", "to close", "15"),
    ("prendere", "to take", "15"), ("mettere", "to put", "15"),
    ("portare", "to bring, carry, wear", "15"), ("lasciare", "to leave, let", "15"),
    ("trovare", "to find", "15"), ("cercare", "to look for", "15"),
    ("perdere", "to lose, miss", "15"), ("vincere", "to win", "15"),
    ("dormire", "to sleep", "15"), ("svegliare", "to wake (someone)", "15"),
    ("aspettare", "to wait for", "15"), ("chiamare", "to call", "15"),
    ("rispondere", "to answer", "15"), ("domandare", "to ask", "15"),
    ("chiedere", "to ask for", "15"), ("ringraziare", "to thank", "15"),
    ("aiutare", "to help", "15"), ("amare", "to love", "15"),
    ("piacere", "to please, be pleasing", "15"), ("odiare", "to hate", "15"),
    ("ridere", "to laugh", "15"), ("piangere", "to cry", "15"),
    ("pensare", "to think", "15"), ("credere", "to believe", "15"),
    ("ricordare", "to remember", "15"), ("dimenticare", "to forget", "15"),
    ("sperare", "to hope", "15"), ("provare", "to try, feel", "15"),
    ("cominciare", "to begin", "15"), ("continuare", "to continue", "15"),
    ("smettere", "to stop (doing)", "15"), ("cambiare", "to change", "15"),
    ("usare", "to use", "15"), ("scegliere", "to choose", "15"),
    ("decidere", "to decide", "15"), ("morire", "to die", "15"),
    ("nascere", "to be born", "15"), ("vivere", "to live", "15"),
    ("crescere", "to grow", "15"), ("diventare", "to become", "15"),
    ("sembrare", "to seem", "15"), ("succedere", "to happen", "15"),
    ("riuscire", "to succeed, manage", "15"), ("mancare", "to be missing, miss", "15"),
    ("bastare", "to be enough", "15"), ("servire", "to serve, be of use", "15"),
    ("guidare", "to drive", "15"), ("volare", "to fly", "15"),
    ("rompere", "to break", "15"),
    ("saltare", "to jump", "15"), ("tenere", "to hold, keep", "15"),
    ("tirare", "to pull, throw", "15"), ("spingere", "to push", "15"),
    ("lavare", "to wash", "15"), ("vestire", "to dress", "15"),
    ("incontrare", "to meet", "15"), ("invitare", "to invite", "15"),
    ("visitare", "to visit", "15"), ("mostrare", "to show", "15"),
    ("spiegare", "to explain", "15"), ("raccontare", "to tell, narrate", "15"),
    ("ripetere", "to repeat", "15"), ("dimostrare", "to demonstrate, prove", "15"),

    # === batch 2 ==========================================================
    ("alzare", "to lift, raise", "15"),
    ("abitare", "to live, reside", "15"), ("accendere", "to switch on, light", "15"),
    ("spegnere", "to switch off", "15"), ("accompagnare", "to accompany", "15"),
    ("affittare", "to rent", "15"), ("aggiungere", "to add", "15"),
    ("annoiare", "to bore", "15"), ("apparecchiare", "to set (the table)", "15"),
    ("appartenere", "to belong", "15"), ("approfittare", "to take advantage", "15"),
    ("arrabbiare", "to anger", "15"), ("asciugare", "to dry", "15"),
    ("attraversare", "to cross", "15"), ("aumentare", "to increase", "15"),
    ("avvicinare", "to bring closer", "15"), ("baciare", "to kiss", "15"),
    ("bagnare", "to wet, water", "15"), ("bussare", "to knock", "15"),
    ("cacciare", "to hunt, chase away", "15"), ("calmare", "to calm", "15"),
    ("caricare", "to load, charge", "15"),
    ("celebrare", "to celebrate", "15"), ("chiacchierare", "to chat", "15"),
    ("colpire", "to hit, strike", "15", True), ("comandare", "to command", "15"),
    ("combattere", "to fight", "15"), ("completare", "to complete", "15"),
    ("comunicare", "to communicate", "15"), ("condurre", "to lead, drive", "15"),
    ("confondere", "to confuse", "15"), ("conservare", "to keep, preserve", "15"),
    ("considerare", "to consider", "15"), ("consigliare", "to advise", "15"),
    ("contare", "to count", "15"), ("controllare", "to check, control", "15"),
    ("convincere", "to convince", "15"), ("coprire", "to cover", "15"),
    ("creare", "to create", "15"), ("cucire", "to sew", "15"),
    ("curare", "to treat, look after", "15"), ("danneggiare", "to damage", "15"),
    ("descrivere", "to describe", "15"), ("desiderare", "to wish, desire", "15"),
    ("difendere", "to defend", "15"), ("dipendere", "to depend", "15"),
    ("dipingere", "to paint", "15"), ("dirigere", "to direct", "15"),
    ("discutere", "to discuss, argue", "15"), ("distruggere", "to destroy", "15"),
    ("disturbare", "to disturb", "15"), ("dividere", "to divide, share", "15"),
    ("dubitare", "to doubt", "15"), ("durare", "to last", "15"),
    ("eleggere", "to elect", "15"), ("esistere", "to exist", "15"), ("esprimere", "to express", "15"),
    ("evitare", "to avoid", "15"), ("fermare", "to stop", "15"),
    ("firmare", "to sign", "15"), ("fumare", "to smoke", "15"),
    ("funzionare", "to work, function", "15"), ("godere", "to enjoy", "15"),
    ("gridare", "to shout", "15"), ("guadagnare", "to earn", "15"),
    ("guarire", "to heal, recover", "15", True), ("immaginare", "to imagine", "15"),
    ("impedire", "to prevent", "15", True), ("indicare", "to indicate, point out", "15"),
    ("informare", "to inform", "15"), ("iniziare", "to begin", "15"),
    ("insistere", "to insist", "15"), ("interessare", "to interest", "15"),
    ("interrompere", "to interrupt", "15"), ("lanciare", "to throw, launch", "15"),
    ("legare", "to tie", "15"), ("liberare", "to free", "15"),
    ("litigare", "to quarrel", "15"), ("mandare", "to send", "15"),
    ("mentire", "to lie", "15"), ("meritare", "to deserve", "15"),
    ("migliorare", "to improve", "15"), ("misurare", "to measure", "15"),
    ("nascondere", "to hide", "15"), ("negare", "to deny", "15"),
    ("notare", "to notice", "15"), ("obbedire", "to obey", "15", True),
    ("occupare", "to occupy", "15"), ("offrire", "to offer", "15"),
    ("ordinare", "to order, tidy", "15"), ("organizzare", "to organise", "15"),
    ("osservare", "to observe", "15"), ("ottenere", "to obtain", "15"),
    ("parcheggiare", "to park", "15"), ("partecipare", "to take part", "15"),
    ("passare", "to pass, spend (time)", "15"), ("peggiorare", "to worsen", "15"),
    ("permettere", "to allow", "15"), ("pesare", "to weigh", "15"),
    ("pettinare", "to comb", "15"), ("piegare", "to fold, bend", "15"), ("pregare", "to pray, beg", "15"),
    ("preoccupare", "to worry", "15"), ("preparare", "to prepare", "15"),
    ("presentare", "to present, introduce", "15"), ("prestare", "to lend", "15"),
    ("produrre", "to produce", "15"), ("promettere", "to promise", "15"),
    ("proporre", "to propose", "15"), ("proteggere", "to protect", "15"),
    ("punire", "to punish", "15", True),
    ("raccogliere", "to pick up, collect", "15"), ("raggiungere", "to reach", "15"),
    ("realizzare", "to achieve, realise", "15"), ("regalare", "to give as a gift", "15"),
    ("registrare", "to record, register", "15"), ("rendere", "to give back, make", "15"),
    ("resistere", "to resist", "15"), ("respirare", "to breathe", "15"),
    ("riconoscere", "to recognise", "15"), ("ricevere", "to receive", "15"),
    ("riempire", "to fill", "15"), ("riflettere", "to reflect", "15"),
    ("rifiutare", "to refuse", "15"), ("riparare", "to repair", "15"), ("riposare", "to rest", "15"), ("risolvere", "to solve", "15"),
    ("risparmiare", "to save (money)", "15"), ("rispettare", "to respect", "15"),
    ("ritrovare", "to find again", "15"), ("salutare", "to greet", "15"),
    ("salvare", "to save, rescue", "15"), ("sbagliare", "to make a mistake", "15"),
    ("scappare", "to escape, run away", "15"), ("scherzare", "to joke", "15"),
    ("sciare", "to ski", "15"), ("scoprire", "to discover", "15"),
    ("scusare", "to excuse", "15"), ("seguire", "to follow", "15"),
    ("separare", "to separate", "15"), ("sistemare", "to arrange, sort out", "15"),
    ("soffrire", "to suffer", "15"), ("sognare", "to dream", "15"),
    ("sorridere", "to smile", "15"), ("sostenere", "to support", "15"),
    ("spaventare", "to frighten", "15"), ("sposare", "to marry", "15"), ("stampare", "to print", "15"),
    ("stringere", "to tighten, squeeze", "15"), ("suggerire", "to suggest", "15", True), ("superare", "to overcome, pass", "15"),
    ("svolgere", "to carry out", "15"), ("tagliare", "to cut", "15"),
    ("telefonare", "to telephone", "15"), ("tentare", "to try, attempt", "15"),
    ("toccare", "to touch", "15"), ("togliere", "to remove, take off", "15"),
    ("tradurre", "to translate", "15"), ("tradire", "to betray", "15", True),
    ("trasformare", "to transform", "15"), ("trattare", "to treat, deal with", "15"),
    ("unire", "to unite, join", "15", True), ("urlare", "to yell", "15"),
    ("utilizzare", "to use", "15"), ("valere", "to be worth", "15"),
    ("versare", "to pour", "15"), ("volgere", "to turn", "15"),
    ("votare", "to vote", "15"), ]

# ---------------------------------------------------------------------------
# ADJECTIVES: (masc sg, English, lesson[, invariable])
# ---------------------------------------------------------------------------
ADJECTIVES = [
    ("buono", "good", "16"), ("cattivo", "bad", "16"),
    ("grande", "big, great", "16"), ("piccolo", "small", "16"),
    ("nuovo", "new", "16"), ("vecchio", "old", "16"),
    ("giovane", "young", "16"), ("lungo", "long", "16"),
    ("corto", "short", "16"), ("alto", "tall, high", "16"),
    ("basso", "low, short", "16"), ("largo", "wide", "16"),
    ("stretto", "narrow, tight", "16"), ("grosso", "big, thick", "16"),
    ("bello", "beautiful, nice", "16"), ("brutto", "ugly, bad", "16"),
    ("caldo", "hot, warm", "16"), ("freddo", "cold", "16"),
    ("pieno", "full", "16"), ("vuoto", "empty", "16"),
    ("pulito", "clean", "16"), ("sporco", "dirty", "16", ),
    ("facile", "easy", "16"), ("difficile", "difficult", "16"),
    ("forte", "strong, loud", "16"), ("debole", "weak", "16"),
    ("veloce", "fast", "16"), ("lento", "slow", "16"),
    ("ricco", "rich", "16"), ("povero", "poor", "16"),
    ("felice", "happy", "16"), ("triste", "sad", "16"),
    ("contento", "pleased, glad", "16"), ("arrabbiato", "angry", "16"),
    ("stanco", "tired", "16"), ("malato", "ill, sick", "16"),
    ("sano", "healthy", "16"), ("libero", "free", "16"),
    ("occupato", "busy, occupied", "16"), ("aperto", "open", "16"),
    ("chiuso", "closed", "16"), ("caro", "dear, expensive", "16"),
    ("economico", "cheap", "16", ), ("importante", "important", "16"),
    ("interessante", "interesting", "16"), ("noioso", "boring", "16"),
    ("simpatico", "nice, likeable", "16", ), ("gentile", "kind", "16"),
    ("bravo", "good, clever", "16"), ("intelligente", "intelligent", "16"),
    ("stupido", "stupid", "16"), ("strano", "strange", "16"),
    ("vero", "true, real", "16"), ("falso", "false", "16"),
    ("giusto", "right, fair", "16"), ("sbagliato", "wrong", "16"),
    ("possibile", "possible", "16"), ("impossibile", "impossible", "16"),
    ("sicuro", "sure, safe", "16"), ("pericoloso", "dangerous", "16"),
    ("famoso", "famous", "16"), ("straniero", "foreign", "16"),
    ("italiano", "Italian", "16"), ("inglese", "English", "16"),
    ("francese", "French", "16"), ("tedesco", "German", "16", ),
    ("spagnolo", "Spanish", "16"), ("americano", "American", "16"),
    ("bianco", "white", "16", ), ("nero", "black", "16"),
    ("rosso", "red", "16"), ("verde", "green", "16"),
    ("giallo", "yellow", "16"), ("blu", "blue", "16", True),
    ("azzurro", "light blue", "16"), ("grigio", "grey", "16"),
    ("marrone", "brown", "16"), ("rosa", "pink", "16", True),
    ("primo", "first", "16"), ("ultimo", "last", "16"),
    ("prossimo", "next", "16"), ("scorso", "last, past", "16"),
    ("solo", "alone, only", "16"), ("stesso", "same", "16"),
    ("altro", "other", "16"), ("tutto", "all, whole", "16"),
    ("molto", "much, a lot of", "16"), ("poco", "little, few", "16", ),
    ("amaro", "bitter", "16"),
    ("salato", "salty", "16"), ("fresco", "fresh, cool", "16", ),
    ("secco", "dry", "16", ), ("bagnato", "wet", "16"),
    ("leggero", "light (weight)", "16"), ("pesante", "heavy", "16"),
    ("morbido", "soft", "16"), ("duro", "hard", "16"),

    # === batch 2 ==========================================================
    ("allegro", "cheerful", "16"), ("calmo", "calm", "16"),
    ("nervoso", "nervous", "16"), ("timido", "shy", "16"),
    ("simile", "similar", "16"), ("diverso", "different", "16"),
    ("uguale", "equal, same", "16"), ("intero", "whole, entire", "16"),
    ("mezzo", "half", "16"), ("doppio", "double", "16"),
    ("singolo", "single", "16"), ("comune", "common", "16"),
    ("raro", "rare", "16"), ("normale", "normal", "16"),
    ("speciale", "special", "16"), ("particolare", "particular", "16"),
    ("generale", "general", "16"), ("principale", "main", "16"),
    ("necessario", "necessary", "16"), ("utile", "useful", "16"),
    ("inutile", "useless", "16"), ("pratico", "practical", "16", ),
    ("comodo", "comfortable", "16"), ("scomodo", "uncomfortable", "16"),
    ("tranquillo", "quiet, calm", "16"), ("rumoroso", "noisy", "16"),
    ("silenzioso", "silent", "16"), ("chiaro", "clear, light", "16"),
    ("scuro", "dark", "16"), ("luminoso", "bright", "16"),
    ("profondo", "deep", "16"), ("sottile", "thin", "16"),
    ("liscio", "smooth", "16"),
    ("ruvido", "rough", "16"), ("dritto", "straight", "16"),
    ("curvo", "curved", "16"), ("rotondo", "round", "16"),
    ("quadrato", "square", "16"), ("presente", "present", "16"),
    ("assente", "absent", "16"), ("pronto", "ready", "16"),
    ("attento", "attentive, careful", "16"), ("distratto", "distracted", "16"),
    ("educato", "polite", "16"), ("maleducato", "rude", "16"),
    ("generoso", "generous", "16"), ("avaro", "mean, stingy", "16"),
    ("onesto", "honest", "16"), ("disonesto", "dishonest", "16"),
    ("coraggioso", "brave", "16"), ("pauroso", "fearful", "16"),
    ("paziente", "patient", "16"), ("impaziente", "impatient", "16"),
    ("preoccupato", "worried", "16"),
    ("sorpreso", "surprised", "16"), ("deluso", "disappointed", "16"),
    ("soddisfatto", "satisfied", "16"), ("innamorato", "in love", "16"),
    ("orgoglioso", "proud", "16"),
    ("modesto", "modest", "16"), ("serio", "serious", "16"),
    ("divertente", "funny, entertaining", "16"), ("ridicolo", "ridiculous", "16"),
    ("perfetto", "perfect", "16"), ("terribile", "terrible", "16"),
    ("meraviglioso", "wonderful", "16"), ("orribile", "horrible", "16"),
    ("moderno", "modern", "16"), ("antico", "ancient", "16", ),
    ("recente", "recent", "16"), ("attuale", "current", "16"),
    ("futuro", "future", "16"), ("passato", "past", "16"),
    ("nazionale", "national", "16"), ("internazionale", "international", "16"),
    ("pubblico", "public", "16", ), ("privato", "private", "16"),
    ("naturale", "natural", "16"), ("artificiale", "artificial", "16"),
]

# ---------------------------------------------------------------------------
# Closed classes: (Italian, English, pos, lesson)
# ---------------------------------------------------------------------------
OTHERS = [
    ("io", "I", "pronoun", "1"), ("tu", "you (sg.)", "pronoun", "1"),
    ("lui", "he", "pronoun", "1"), ("lei", "she", "pronoun", "1"),
    ("noi", "we", "pronoun", "1"), ("voi", "you (pl.)", "pronoun", "1"),
    ("loro", "they", "pronoun", "1"), ("questo", "this", "pronoun", "1"),
    ("quello", "that", "pronoun", "1"), ("chi", "who", "pronoun", "1"),
    ("che", "what, that, which", "pronoun", "1"), ("qualcuno", "someone", "pronoun", "1"),
    ("qualcosa", "something", "pronoun", "1"), ("niente", "nothing", "pronoun", "1"),
    ("nessuno", "nobody", "pronoun", "1"), ("ognuno", "everyone", "pronoun", "1"),
    ("mio", "my", "pronoun", "1"), ("tuo", "your (sg.)", "pronoun", "1"),
    ("suo", "his, her", "pronoun", "1"), ("nostro", "our", "pronoun", "1"),
    ("vostro", "your (pl.)", "pronoun", "1"),
    ("di", "of, from", "preposition", "5"), ("a", "to, at", "preposition", "5"),
    ("da", "from, by, since", "preposition", "5"), ("in", "in, to", "preposition", "5"),
    ("con", "with", "preposition", "5"), ("su", "on, above", "preposition", "5"),
    ("per", "for, through", "preposition", "5"), ("tra", "between, among, in", "preposition", "5"),
    ("fra", "between, among", "preposition", "5"), ("senza", "without", "preposition", "5"),
    ("sopra", "above, on top of", "preposition", "5"), ("sotto", "under, below", "preposition", "5"),
    ("davanti", "in front of", "preposition", "5"), ("dietro", "behind", "preposition", "5"),
    ("dentro", "inside", "preposition", "5"), ("fuori", "outside", "preposition", "5"),
    ("accanto", "next to, beside", "preposition", "5"), ("verso", "towards", "preposition", "5"),
    ("contro", "against", "preposition", "5"), ("durante", "during", "preposition", "5"),
    ("dopo", "after", "preposition", "3"), ("prima", "before", "preposition", "3"),
    ("e", "and", "conjunction", "1"), ("ma", "but", "conjunction", "1"),
    ("o", "or", "conjunction", "1"), ("perché", "because, why", "conjunction", "1"),
    ("se", "if", "conjunction", "1"), ("quando", "when", "conjunction", "1"),
    ("mentre", "while", "conjunction", "1"), ("anche", "also, too", "conjunction", "1"),
    ("però", "however", "conjunction", "1"), ("quindi", "so, therefore", "conjunction", "1"),
    ("allora", "then, so", "conjunction", "1"), ("invece", "instead", "conjunction", "1"),
    ("oppure", "or, otherwise", "conjunction", "1"), ("siccome", "since, as", "conjunction", "1"),
    ("non", "not", "adverb", "1"), ("sì", "yes", "adverb", "1"),
    ("no", "no", "adverb", "1"), ("bene", "well", "adverb", "16"),
    ("male", "badly", "adverb", "16"), ("meglio", "better", "adverb", "16"),
    ("peggio", "worse", "adverb", "16"), ("più", "more", "adverb", "16"),
    ("meno", "less", "adverb", "16"),
    ("troppo", "too much", "adverb", "16"), ("abbastanza", "enough, quite", "adverb", "16"),
    ("quasi", "almost", "adverb", "16"), ("appena", "just, barely", "adverb", "16"),
    ("insieme", "together", "adverb", "16"), ("solamente", "only", "adverb", "16"),
    ("davvero", "really", "adverb", "16"), ("forse", "perhaps", "adverb", "16"),
    ("certo", "certainly, of course", "adverb", "16"), ("volentieri", "gladly", "adverb", "16"),
    ("piano", "slowly, quietly", "adverb", "16"), ("presto", "early, soon", "adverb", "3"),
    ("tardi", "late", "adverb", "3"), ("oggi", "today", "adverb", "3"),
    ("ieri", "yesterday", "adverb", "3"), ("domani", "tomorrow", "adverb", "3"),
    ("adesso", "now", "adverb", "3"),
    ("sempre", "always", "adverb", "3"), ("mai", "never, ever", "adverb", "3"),
    ("spesso", "often", "adverb", "3"), ("qualche volta", "sometimes", "adverb", "3"),
    ("ancora", "still, yet, again", "adverb", "3"), ("già", "already", "adverb", "3"),
    ("poi", "then, afterwards", "adverb", "3"), ("subito", "immediately", "adverb", "3"),
    ("qui", "here", "adverb", "5"), ("qua", "here", "adverb", "5"),
    ("lì", "there", "adverb", "5"), ("là", "there", "adverb", "5"),
    ("dove", "where", "adverb", "5"), ("come", "how, as", "adverb", "5"),
    ("quanto", "how much", "adverb", "5"),
    ("lontano", "far", "adverb", "5"),
    ("uno", "one", "number", "3"), ("due", "two", "number", "3"),
    ("tre", "three", "number", "3"), ("quattro", "four", "number", "3"),
    ("cinque", "five", "number", "3"), ("sei", "six", "number", "3"),
    ("sette", "seven", "number", "3"), ("otto", "eight", "number", "3"),
    ("nove", "nine", "number", "3"), ("dieci", "ten", "number", "3"),
    ("venti", "twenty", "number", "3"), ("trenta", "thirty", "number", "3"),
    ("cento", "a hundred", "number", "3"), ("mille", "a thousand", "number", "3"),
    ("ciao", "hi, bye", "phrase", "1"), ("buongiorno", "good morning", "phrase", "1"),
    ("buonasera", "good evening", "phrase", "1"), ("buonanotte", "good night", "phrase", "1"),
    ("arrivederci", "goodbye", "phrase", "1"), ("per favore", "please", "phrase", "1"),
    ("grazie", "thank you", "phrase", "1"), ("prego", "you're welcome", "phrase", "1"),
    ("scusi", "excuse me (formal)", "phrase", "1"), ("mi dispiace", "I'm sorry", "phrase", "1"),
    ("come stai?", "how are you?", "phrase", "1"), ("quanto costa?", "how much does it cost?", "phrase", "9"),
    ("non capisco", "I don't understand", "phrase", "1"), ("a dopo", "see you later", "phrase", "1"),

    # === batch 2 ==========================================================
    ("finalmente", "finally, at last", "adverb", "3"),
    ("improvvisamente", "suddenly", "adverb", "3"),
    ("recentemente", "recently", "adverb", "3"),
    ("raramente", "rarely", "adverb", "3"),
    ("normalmente", "normally", "adverb", "3"),
    ("generalmente", "generally", "adverb", "3"),
    ("attualmente", "currently", "adverb", "3"),
    ("immediatamente", "immediately", "adverb", "3"),
    ("lentamente", "slowly", "adverb", "16"),
    ("velocemente", "quickly", "adverb", "16"),
    ("facilmente", "easily", "adverb", "16"),
    ("difficilmente", "with difficulty", "adverb", "16"),
    ("perfettamente", "perfectly", "adverb", "16"),
    ("completamente", "completely", "adverb", "16"),
    ("assolutamente", "absolutely", "adverb", "16"),
    ("probabilmente", "probably", "adverb", "16"),
    ("sicuramente", "surely", "adverb", "16"),
    ("veramente", "truly, really", "adverb", "16"),
    ("naturalmente", "naturally, of course", "adverb", "16"),
    ("purtroppo", "unfortunately", "adverb", "16"),
    ("magari", "maybe, if only", "adverb", "16"),
    ("almeno", "at least", "adverb", "16"),
    ("soprattutto", "above all", "adverb", "16"),
    ("inoltre", "moreover", "adverb", "16"),
    ("comunque", "anyway, however", "adverb", "16"),
    ("neanche", "not even, neither", "adverb", "16"),
    ("nemmeno", "not even", "adverb", "16"),
    ("ovunque", "everywhere", "adverb", "5"),
    ("altrove", "elsewhere", "adverb", "5"),
    ("indietro", "back, backwards", "adverb", "5"),
    ("avanti", "forward, ahead", "adverb", "5"),
    ("giù", "down", "adverb", "5"), ("perciò", "therefore", "conjunction", "1"),
    ("infatti", "in fact, indeed", "conjunction", "1"),
    ("benché", "although", "conjunction", "1"),
    ("affinché", "so that", "conjunction", "1"),
    ("finché", "until, as long as", "conjunction", "1"),
    ("nonostante", "despite", "conjunction", "1"),
    ("undici", "eleven", "number", "3"), ("dodici", "twelve", "number", "3"),
    ("tredici", "thirteen", "number", "3"), ("quindici", "fifteen", "number", "3"),
    ("sedici", "sixteen", "number", "3"), ("diciotto", "eighteen", "number", "3"),
    ("quaranta", "forty", "number", "3"), ("cinquanta", "fifty", "number", "3"),
    ("sessanta", "sixty", "number", "3"), ("settanta", "seventy", "number", "3"),
    ("ottanta", "eighty", "number", "3"), ("novanta", "ninety", "number", "3"),
    ("buon appetito", "enjoy your meal", "phrase", "4"),
    ("in bocca al lupo", "good luck", "phrase", "1"),
    ("a presto", "see you soon", "phrase", "1"),
    ("come va?", "how's it going?", "phrase", "1"),
    ("va bene", "OK, all right", "phrase", "1"),
    ("piacere di conoscerti", "nice to meet you", "phrase", "1"),
    ("non lo so", "I don't know", "phrase", "1"),
    ("che peccato", "what a pity", "phrase", "1"),
]

DEDUPE_SUFFIX = {"oggi2": "oggi", "gente2": "gente", "molto2": "molto", "ora2": "ora",
                 "vicino2": "vicino", "dolce2": "dolce", "film2": "film",
                 "pantaloni2": "pantaloni", "soldi2": "soldi",
                 "costare2": "costare", "viaggiare2": "viaggiare", "costruire2": "costruire"}

# ---------------------------------------------------------------------------
# Cloze: headword -> [(sentence with {target}, English)]
# ---------------------------------------------------------------------------
CLOZE = {
    "casa": [("La {casa} è molto grande.", "The house is very big."),
             ("Le {case} sono vecchie.", "The houses are old.")],
    "libro": [("Leggo un {libro} interessante.", "I am reading an interesting book."),
              ("I {libri} sono sul tavolo.", "The books are on the table.")],
    "amico": [("Il mio {amico} arriva domani.", "My friend arrives tomorrow."),
              ("Ho molti {amici} a Roma.", "I have many friends in Rome.")],
    "città": [("Vivo in una {città} piccola.", "I live in a small city."),
              ("Le {città} italiane sono belle.", "Italian cities are beautiful.")],
    "uomo": [("Quell'{uomo} è mio zio.", "That man is my uncle."),
             ("Gli {uomini} lavorano qui.", "The men work here.")],
    "mano": [("Ho una {mano} fredda.", "I have a cold hand."),
             ("Lavati le {mani}!", "Wash your hands!")],
    "uovo": [("Mangio un {uovo} a colazione.", "I eat an egg for breakfast."),
             ("Le {uova} sono fresche.", "The eggs are fresh.")],
    "parlare": [("Io {parlo} italiano.", "I speak Italian."),
                ("Loro {parlano} troppo.", "They talk too much.")],
    "essere": [("Io {sono} stanco.", "I am tired."),
               ("Noi {siamo} italiani.", "We are Italian.")],
    "avere": [("Io {ho} fame.", "I am hungry."),
              ("Loro {hanno} due figli.", "They have two children.")],
    "fare": [("Che cosa {fai}?", "What are you doing?"),
             ("Noi {facciamo} i compiti.", "We are doing the homework.")],
    "andare": [("Io {vado} a scuola.", "I go to school."),
               ("Loro {vanno} al mare.", "They are going to the seaside.")],
    "venire": [("Tu {vieni} con me?", "Are you coming with me?"),
               ("Loro {vengono} domani.", "They are coming tomorrow.")],
    "potere": [("Non {posso} venire.", "I can't come."),
               ("{Puoi} aiutarmi?", "Can you help me?")],
    "volere": [("Io {voglio} un caffè.", "I want a coffee."),
               ("Loro {vogliono} partire.", "They want to leave.")],
    "dovere": [("{Devo} studiare.", "I must study."),
               ("Noi {dobbiamo} andare.", "We have to go.")],
    "sapere": [("Non {so} niente.", "I don't know anything."),
               ("Loro {sanno} la verità.", "They know the truth.")],
    "capire": [("Non {capisco} bene.", "I don't understand well."),
               ("Loro non {capiscono}.", "They don't understand.")],
    "finire": [("Il film {finisce} tardi.", "The film finishes late."),
               ("Io {finisco} il lavoro.", "I am finishing the work.")],
    "mangiare": [("Noi {mangiamo} alle otto.", "We eat at eight."),
                 ("Tu {mangi} troppo.", "You eat too much.")],
    "bere": [("Io {bevo} acqua.", "I drink water."),
             ("Loro {bevono} vino.", "They drink wine.")],
    "cercare": [("Io {cerco} le chiavi.", "I am looking for the keys."),
                ("Tu {cerchi} lavoro?", "Are you looking for work?")],
    "pagare": [("Noi {paghiamo} il conto.", "We pay the bill."),
               ("Tu {paghi} con la carta.", "You pay by card.")],
    "prendere": [("{Prendo} un caffè.", "I'll have a coffee."),
                 ("Loro {prendono} il treno.", "They take the train.")],
    "uscire": [("Io {esco} stasera.", "I am going out this evening."),
               ("Loro {escono} tardi.", "They go out late.")],
    "dire": [("Che cosa {dici}?", "What are you saying?"),
             ("Loro {dicono} la verità.", "They tell the truth.")],
    "bello": [("Che {bella} giornata!", "What a beautiful day!"),
              ("I {belli} non sono sempre bravi.", "Beautiful people are not always good.")],
    "buono": [("È un {buon} amico.", "He is a good friend."),
              ("Le mele sono {buone}.", "The apples are good.")],
    "grande": [("Roma è una {grande} città.", "Rome is a big city."),
               ("Ho due fratelli {grandi}.", "I have two big brothers.")],
    "rosso": [("Ho una macchina {rossa}.", "I have a red car."),
              ("I fiori {rossi} sono belli.", "The red flowers are beautiful.")],
    "italiano": [("Lei è {italiana}.", "She is Italian."),
                 ("Gli studenti {italiani} studiano.", "The Italian students study.")],
    "tutto": [("Ho letto {tutto} il libro.", "I read the whole book."),
              ("{Tutte} le ragazze cantano.", "All the girls are singing.")],
    "acqua": [("Vorrei un po' d'{acqua}.", "I would like some water."),
              ("Le {acque} del lago sono fredde.", "The waters of the lake are cold.")],
    "giorno": [("Ogni {giorno} studio.", "Every day I study."),
               ("Passo i {giorni} a leggere.", "I spend my days reading.")],
    "tempo": [("Non ho {tempo}.", "I don't have time."),
              ("Che {tempo} fa oggi?", "What's the weather like today?")],

    "donna": [("La {donna} lavora in banca.", "The woman works in a bank."),
              ("Le {donne} parlano insieme.", "The women are talking together.")],
    "bambino": [("Il {bambino} dorme.", "The child is sleeping."),
                ("I {bambini} giocano in giardino.", "The children play in the garden.")],
    "famiglia": [("La mia {famiglia} è grande.", "My family is big."),
                 ("Le {famiglie} italiane sono unite.", "Italian families are close.")],
    "padre": [("Mio {padre} lavora molto.", "My father works a lot."),
              ("I {padri} aspettano fuori.", "The fathers are waiting outside.")],
    "scuola": [("Vado a {scuola} ogni giorno.", "I go to school every day."),
               ("Le {scuole} sono chiuse.", "The schools are closed.")],
    "lavoro": [("Il mio {lavoro} è difficile.", "My job is difficult."),
               ("Cerco {lavoro} da mesi.", "I have been looking for work for months.")],
    "macchina": [("La {macchina} è rossa.", "The car is red."),
                 ("Le {macchine} sono parcheggiate.", "The cars are parked.")],
    "treno": [("Il {treno} parte alle otto.", "The train leaves at eight."),
              ("I {treni} sono in ritardo.", "The trains are late.")],
    "strada": [("La {strada} è lunga.", "The road is long."),
               ("Le {strade} sono strette.", "The streets are narrow.")],
    "negozio": [("Il {negozio} apre alle nove.", "The shop opens at nine."),
                ("I {negozi} sono chiusi la domenica.", "The shops are closed on Sunday.")],
    "mare": [("Andiamo al {mare} d'estate.", "We go to the seaside in summer."),
             ("I {mari} del sud sono caldi.", "The southern seas are warm.")],
    "montagna": [("La {montagna} è alta.", "The mountain is high."),
                 ("Le {montagne} sono coperte di neve.", "The mountains are covered in snow.")],
    "amore": [("L'{amore} è importante.", "Love is important."),
              ("Gli {amori} giovanili durano poco.", "Young loves don't last long.")],
    "problema": [("Ho un {problema} serio.", "I have a serious problem."),
                 ("I {problemi} sono molti.", "The problems are many.")],
    "cane": [("Il {cane} abbaia.", "The dog is barking."),
             ("I {cani} corrono nel parco.", "The dogs run in the park.")],
    "gatto": [("Il {gatto} dorme sul divano.", "The cat sleeps on the sofa."),
              ("I {gatti} sono indipendenti.", "Cats are independent.")],
    "sole": [("Il {sole} splende.", "The sun is shining."),
             ("Mi piace il {sole} di maggio.", "I like the May sun.")],
    "pane": [("Compro il {pane} ogni mattina.", "I buy bread every morning."),
             ("Il {pane} è fresco.", "The bread is fresh.")],
    "vino": [("Il {vino} rosso è buono.", "The red wine is good."),
             ("I {vini} italiani sono famosi.", "Italian wines are famous.")],
    "andare": [("Dove {vai}?", "Where are you going?"),
               ("Noi {andiamo} a casa.", "We are going home.")],
    "fare": [("Io {faccio} colazione alle sette.", "I have breakfast at seven."),
             ("Loro {fanno} i compiti.", "They are doing their homework.")],
    "dare": [("Ti {do} il libro.", "I'll give you the book."),
             ("Loro {danno} una festa.", "They are throwing a party.")],
    "stare": [("Come {stai}?", "How are you?"),
              ("Noi {stiamo} bene.", "We are well.")],
    "vedere": [("Io {vedo} il mare.", "I see the sea."),
               ("Loro {vedono} un film.", "They are watching a film.")],
    "leggere": [("Io {leggo} il giornale.", "I read the newspaper."),
                ("Loro {leggono} molto.", "They read a lot.")],
    "scrivere": [("Io {scrivo} una lettera.", "I am writing a letter."),
                 ("Voi {scrivete} bene.", "You write well.")],
    "conoscere": [("Io {conosco} Maria.", "I know Maria."),
                  ("Loro {conoscono} la città.", "They know the city.")],
    "aprire": [("Io {apro} la finestra.", "I open the window."),
               ("Loro {aprono} il negozio.", "They open the shop.")],
    "chiudere": [("Io {chiudo} la porta.", "I close the door."),
                 ("Loro {chiudono} alle otto.", "They close at eight.")],
    "partire": [("Io {parto} domani.", "I am leaving tomorrow."),
                ("Loro {partono} presto.", "They leave early.")],
    "dormire": [("Io {dormo} otto ore.", "I sleep eight hours."),
                ("I bambini {dormono}.", "The children are sleeping.")],
    "lavorare": [("Io {lavoro} in ufficio.", "I work in an office."),
                 ("Loro {lavorano} di notte.", "They work at night.")],
    "giocare": [("I bambini {giocano} a calcio.", "The children play football."),
                ("Tu {giochi} bene.", "You play well.")],
    "studiare": [("Io {studio} italiano.", "I study Italian."),
                 ("Tu {studi} troppo.", "You study too much.")],
    "aspettare": [("Io {aspetto} l'autobus.", "I am waiting for the bus."),
                  ("Loro {aspettano} da un'ora.", "They have been waiting an hour.")],
    "trovare": [("Non {trovo} le chiavi.", "I can't find the keys."),
                ("Loro {trovano} sempre una soluzione.", "They always find a solution.")],
    "pensare": [("Io {penso} a te.", "I am thinking of you."),
                ("Loro {pensano} di partire.", "They are thinking of leaving.")],
    "piccolo": [("Ho una casa {piccola}.", "I have a small house."),
                ("I {piccoli} problemi sono facili.", "Small problems are easy.")],
    "nuovo": [("Ho una macchina {nuova}.", "I have a new car."),
              ("I {nuovi} studenti arrivano.", "The new students are arriving.")],
    "vecchio": [("Il mio nonno è {vecchio}.", "My grandfather is old."),
                ("Le case {vecchie} sono belle.", "Old houses are beautiful.")],
    "caldo": [("L'acqua è {calda}.", "The water is hot."),
              ("I giorni {caldi} sono finiti.", "The hot days are over.")],
    "difficile": [("L'esame è {difficile}.", "The exam is difficult."),
                  ("Le domande {difficili} sono le ultime.", "The difficult questions are the last ones.")],
    "felice": [("Sono molto {felice}.", "I am very happy."),
               ("Le persone {felici} sorridono.", "Happy people smile.")],
    "stanco": [("Sono {stanco} oggi.", "I am tired today."),
               ("Le ragazze sono {stanche}.", "The girls are tired.")],
    "aperto": [("Il negozio è {aperto}.", "The shop is open."),
               ("Le finestre sono {aperte}.", "The windows are open.")],
    "primo": [("È la {prima} volta.", "It's the first time."),
              ("I {primi} giorni sono difficili.", "The first days are difficult.")],
    "molto": [("Ho {molta} fame.", "I am very hungry."),
              ("Ci sono {molte} persone.", "There are many people.")],
}

ANTONYMS = [
    ("grande", "piccolo"), ("nuovo", "vecchio"), ("lungo", "corto"),
    ("alto", "basso"), ("caldo", "freddo"), ("pieno", "vuoto"),
    ("pulito", "sporco"), ("facile", "difficile"), ("forte", "debole"),
    ("veloce", "lento"), ("ricco", "povero"), ("felice", "triste"),
    ("aperto", "chiuso"), ("vero", "falso"), ("giusto", "sbagliato"),
    ("possibile", "impossibile"), ("bianco", "nero"), ("primo", "ultimo"),
    ("buono", "cattivo"), ("bello", "brutto"), ("giovane", "vecchio"),
    ("largo", "stretto"), ("leggero", "pesante"), ("morbido", "duro"),
    ("uomo", "donna"), ("padre", "madre"), ("figlio", "figlia"),
    ("fratello", "sorella"), ("giorno", "notte"), ("sole", "luna"),
    ("pace", "guerra"), ("amore", "odio"), ("gioia", "tristezza"),
    ("verità", "bugia"), ("inizio", "fine"), ("estate", "inverno"),
    ("comprare", "vendere"), ("aprire", "chiudere"), ("partire", "arrivare"),
    ("entrare", "uscire"), ("salire", "scendere"), ("ridere", "piangere"),
    ("nascere", "morire"), ("ricordare", "dimenticare"), ("amare", "odiare"),
    ("cominciare", "finire"), ("perdere", "vincere"), ("oggi", "domani"),
    ("sempre", "mai"), ("bene", "male"), ("più", "meno"), ("qui", "lì"),
    ("sopra", "sotto"), ("davanti", "dietro"), ("dentro", "fuori"),
    ("prima", "dopo"), ("presto", "tardi"), ("meglio", "peggio"),
]
SYNONYMS = [
    ("via", "strada"), ("denaro", "prezzo"), ("ragione", "motivo"),
    ("restare", "rimanere"), ("domandare", "chiedere"), ("qui", "qua"),
    ("lì", "là"), ("però", "ma"), ("quindi", "allora"),
    ("bambino", "ragazzo"), ("casa", "appartamento"), ("medico", "ospedale"),
    ("gioco", "sport"), ("storia", "notizia"), ("errore", "problema"),
    ("iniziare", "cominciare"), ("mandare", "spedire"),     ("desiderio", "sogno"), ("opinione", "idea"), ("accordo", "soluzione"),
    ("regola", "legge"), ("attenzione", "cura"),
    ("fatica", "sforzo"), ("riposo", "sonno"), ("colpa", "vergogna"),
    ("carattere", "comportamento"), ("conoscenza", "esperienza"),
    ("utilizzare", "usare"), ]

# ---------------------------------------------------------------------------
# SPECIAL BANK 1: essere vs stare.
# NB: Italian is NOT Spanish. Italian `essere` covers most of what Spanish
# splits between ser and estar — including location and temporary states
# ("sono a Roma", "sono stanco"). `stare` is reserved for health, the
# progressive, "stare per" + infinitive, and a closed set of fixed expressions.
# ---------------------------------------------------------------------------
ESSERE_STARE = [
    ("Io {sono} italiano.", "I am Italian.", "sto", "essere: nationality/identity"),
    ("Lei {è} medico.", "She is a doctor.", "sta", "essere: profession"),
    ("Noi {siamo} di Roma.", "We are from Rome.", "stiamo", "essere: origin"),
    ("Il tavolo {è} di legno.", "The table is made of wood.", "sta", "essere: material"),
    ("Oggi {è} lunedì.", "Today is Monday.", "sta", "essere: day/date"),
    ("{Sono} le tre.", "It is three o'clock.", "Stanno", "essere: telling the time"),
    ("Questo libro {è} mio.", "This book is mine.", "sta", "essere: possession"),
    ("La casa {è} grande.", "The house is big.", "sta", "essere: description"),
    ("Io {sono} stanco.", "I am tired.", "sto", "essere: temporary state (Italian uses essere, unlike Spanish estar)"),
    ("Lei {è} felice.", "She is happy.", "sta", "essere: emotion"),
    ("Noi {siamo} a Roma.", "We are in Rome.", "stiamo", "essere: location (Italian uses essere)"),
    ("Il gatto {è} sotto il tavolo.", "The cat is under the table.", "sta", "essere: location"),
    ("La porta {è} aperta.", "The door is open.", "sta", "essere: resulting state"),
    ("{È} tardi.", "It is late.", "Sta", "essere: impersonal"),
    ("Loro {sono} sposati.", "They are married.", "stanno", "essere: marital status"),
    ("Il caffè {è} caldo.", "The coffee is hot.", "sta", "essere: quality"),
    ("Voi {siete} in ritardo.", "You are late.", "state", "essere: state"),
    ("Questi fiori {sono} belli.", "These flowers are beautiful.", "stanno", "essere: description"),
    ("Il film {è} finito.", "The film is finished.", "sta", "essere: completed state"),
    ("Io {sono} pronto.", "I am ready.", "sto", "essere: readiness"),
    ("{Sono} nato a Milano.", "I was born in Milan.", "Sto", "essere: auxiliary in passato prossimo"),
    ("La finestra {è} rotta.", "The window is broken.", "sta", "essere: resulting state"),
    ("Come {stai}?", "How are you?", "sei", "stare: health/wellbeing — the classic case"),
    ("{Sto} bene, grazie.", "I am well, thank you.", "Sono", "stare: health"),
    ("Mio nonno {sta} male.", "My grandfather is unwell.", "è", "stare: health"),
    ("Noi {stiamo} benissimo.", "We are very well.", "siamo", "stare: health"),
    ("Io {sto} mangiando.", "I am eating.", "sono", "stare: progressive (stare + gerund)"),
    ("Loro {stanno} guardando la TV.", "They are watching TV.", "sono", "stare: progressive"),
    ("Che cosa {stai} facendo?", "What are you doing?", "sei", "stare: progressive"),
    ("Noi {stiamo} studiando.", "We are studying.", "siamo", "stare: progressive"),
    ("Il treno {sta} arrivando.", "The train is arriving.", "è", "stare: progressive"),
    ("{Sto} per uscire.", "I am about to go out.", "Sono", "stare per + infinitive = about to"),
    ("Il film {sta} per cominciare.", "The film is about to begin.", "è", "stare per: about to"),
    ("{Stai} attento!", "Be careful!", "Sei", "stare attento: fixed expression"),
    ("{State} zitti!", "Be quiet!", "Siete", "stare zitto: fixed expression"),
    ("I bambini non {stanno} fermi.", "The children won't keep still.", "sono", "stare fermo: fixed expression"),
    ("{Sta} tranquillo.", "Stay calm.", "È", "stare tranquillo: fixed expression"),
    ("Questo vestito ti {sta} bene.", "This dress suits you.", "è", "stare bene: to suit (clothes)"),
    ("Le scarpe mi {stanno} strette.", "The shoes are tight on me.", "sono", "stare + fit (clothing)"),
    ("Noi {stiamo} in piedi.", "We are standing.", "siamo", "stare in piedi: fixed expression"),
    ("{Sto} a casa stasera.", "I'm staying home tonight.", "Sono", "stare: to stay/remain somewhere"),
    ("Quanto tempo {stai} a Roma?", "How long are you staying in Rome?", "sei", "stare: duration of a stay"),
    ("{Stiamo} insieme da due anni.", "We have been together for two years.", "Siamo", "stare insieme: to be a couple"),
    ("Lui {sta} zitto tutto il giorno.", "He stays silent all day.", "è", "stare zitto: fixed expression"),
    ("{Sta} succedendo qualcosa.", "Something is happening.", "È", "stare: progressive"),
]

# ---------------------------------------------------------------------------
# SPECIAL BANK 2: avere vs essere as the passato prossimo auxiliary.
# ---------------------------------------------------------------------------
AVERE_ESSERE = [
    ("Ieri {ho} mangiato una pizza.", "Yesterday I ate a pizza.", "sono", "avere: transitive verb with an object"),
    ("Lei {ha} comprato un vestito.", "She bought a dress.", "è", "avere: transitive"),
    ("Noi {abbiamo} visto un film.", "We saw a film.", "siamo", "avere: transitive"),
    ("Loro {hanno} letto il giornale.", "They read the newspaper.", "sono", "avere: transitive"),
    ("{Ho} scritto una lettera.", "I wrote a letter.", "Sono", "avere: transitive"),
    ("Tu {hai} fatto i compiti.", "You did the homework.", "sei", "avere: transitive"),
    ("Noi {abbiamo} parlato con Maria.", "We spoke with Maria.", "siamo", "avere: parlare takes avere"),
    ("{Ho} dormito bene.", "I slept well.", "Sono", "avere: dormire takes avere"),
    ("Lui {ha} lavorato molto.", "He worked a lot.", "è", "avere: lavorare takes avere"),
    ("Noi {abbiamo} camminato per ore.", "We walked for hours.", "siamo", "avere: camminare takes avere"),
    ("Loro {hanno} viaggiato in Italia.", "They travelled in Italy.", "sono", "avere: viaggiare takes avere"),
    ("{Ho} telefonato a mia madre.", "I phoned my mother.", "Sono", "avere: telefonare takes avere"),
    ("Lei {ha} risposto subito.", "She answered immediately.", "è", "avere: rispondere takes avere"),
    ("{Abbiamo} cenato alle otto.", "We had dinner at eight.", "Siamo", "avere: cenare takes avere"),
    ("Tu {hai} capito tutto.", "You understood everything.", "sei", "avere: transitive"),
    ("Io {sono} andato al cinema.", "I went to the cinema.", "ho", "essere: andare = verb of motion"),
    ("Lei {è} venuta con noi.", "She came with us.", "ha", "essere: venire = verb of motion"),
    ("Noi {siamo} arrivati tardi.", "We arrived late.", "abbiamo", "essere: arrivare = motion"),
    ("Loro {sono} partiti stamattina.", "They left this morning.", "hanno", "essere: partire = motion"),
    ("Tu {sei} uscito presto.", "You went out early.", "hai", "essere: uscire = motion"),
    ("Io {sono} entrato in casa.", "I entered the house.", "ho", "essere: entrare = motion"),
    ("Lei {è} tornata a casa.", "She returned home.", "ha", "essere: tornare = motion"),
    ("Noi {siamo} saliti sul treno.", "We got on the train.", "abbiamo", "essere: salire = motion"),
    ("Loro {sono} scesi dall'autobus.", "They got off the bus.", "hanno", "essere: scendere = motion"),
    ("Il bambino {è} caduto.", "The child fell.", "ha", "essere: cadere = change of state"),
    ("Mio nonno {è} morto due anni fa.", "My grandfather died two years ago.", "ha", "essere: morire = change of state"),
    ("Lei {è} nata a Roma.", "She was born in Rome.", "ha", "essere: nascere = change of state"),
    ("I bambini {sono} cresciuti.", "The children have grown.", "hanno", "essere: crescere = change of state"),
    ("Lui {è} diventato medico.", "He became a doctor.", "ha", "essere: diventare = change of state"),
    ("Noi {siamo} rimasti a casa.", "We stayed at home.", "abbiamo", "essere: rimanere = staying"),
    ("Loro {sono} restati due giorni.", "They stayed two days.", "hanno", "essere: restare = staying"),
    ("Io {sono} stato a Milano.", "I have been to Milan.", "ho", "essere: essere itself takes essere"),
    ("Mi {sono} lavato le mani.", "I washed my hands.", "ho", "essere: reflexive verbs always take essere"),
    ("Lei si {è} svegliata presto.", "She woke up early.", "ha", "essere: reflexive"),
    ("Ci {siamo} divertiti molto.", "We enjoyed ourselves a lot.", "abbiamo", "essere: reflexive"),
    ("Ti {sei} vestito in fretta.", "You got dressed quickly.", "hai", "essere: reflexive"),
    ("Mi {è} piaciuto il film.", "I liked the film.", "ha", "essere: piacere takes essere"),
    ("Le {sono} piaciute le foto.", "She liked the photos.", "hanno", "essere: piacere takes essere"),
    ("Che cosa {è} successo?", "What happened?", "ha", "essere: succedere takes essere"),
    ("Mi {è} sembrato strano.", "It seemed strange to me.", "ha", "essere: sembrare takes essere"),
    ("Non ci {siamo} riusciti.", "We didn't manage it.", "abbiamo", "essere: riuscire takes essere"),
    ("Il pane {è} costato poco.", "The bread cost little.", "ha", "essere: costare takes essere"),
    ("Mi {sei} mancato.", "I missed you.", "hai", "essere: mancare takes essere"),
    ("Il tempo {è} bastato.", "The time was enough.", "ha", "essere: bastare takes essere"),
]


def build():
    entries, by_head = [], {}
    n = 0

    def nid():
        nonlocal n
        n += 1
        return f"it{n:04d}"

    for row in NOUNS:
        word, gender, en, lesson = row[0], row[1], row[2], row[3]
        explicit_pl = row[4] if len(row) > 4 else None
        head = DEDUPE_SUFFIX.get(word, word)
        forms = noun_forms(head, gender, plural=explicit_pl)
        e = {"it": head, "en": en, "pos": "noun", "id": nid(), "lesson": lesson,
             "gender": gender, "plural": forms["plural"], "noun_decl": forms}
        entries.append(e); by_head.setdefault(word, e)

    for row in VERBS:
        inf, en, lesson = row[0], row[1], row[2]
        isc = row[3] if len(row) > 3 else False
        head = DEDUPE_SUFFIX.get(inf, inf)
        e = {"it": head, "en": en, "pos": "verb", "id": nid(), "lesson": lesson,
             "conjugation": conjugate(head, isc=isc)}
        if isc:
            e["conj_note"] = "-isc- verb"
        entries.append(e); by_head.setdefault(inf, e)

    for row in ADJECTIVES:
        word, en, lesson = row[0], row[1], row[2]
        invariable = row[3] if len(row) > 3 else False
        head = DEDUPE_SUFFIX.get(word, word)
        e = {"it": head, "en": en, "pos": "adjective", "id": nid(), "lesson": lesson,
             "declension": decline_adjective(head, invariable=invariable)}
        entries.append(e); by_head.setdefault(word, e)

    for word, en, pos, lesson in OTHERS:
        head = DEDUPE_SUFFIX.get(word, word)
        e = {"it": head, "en": en, "pos": pos, "id": nid(), "lesson": lesson}
        entries.append(e); by_head.setdefault(word, e)

    attached = 0
    for head, sents in CLOZE.items():
        e = by_head.get(head)
        assert e is not None, f"cloze references unknown headword {head!r}"
        e["cloze"] = [{"it": s, "en": t} for s, t in sents]
        attached += len(sents)

    def link(pairs, field):
        for a, b in pairs:
            ea, eb = by_head.get(a), by_head.get(b)
            assert ea is not None, f"{field}: unknown headword {a!r}"
            assert eb is not None, f"{field}: unknown headword {b!r}"
            ea.setdefault(field, []); eb.setdefault(field, [])
            if eb["id"] not in ea[field]: ea[field].append(eb["id"])
            if ea["id"] not in eb[field]: eb[field].append(ea["id"])
    link(ANTONYMS, "antonyms")
    link(SYNONYMS, "synonyms")

    special = {
        "essere_stare": [
            {"id": f"est{i+1:03d}", "it": it, "en": en, "wrong": wrong, "note": note}
            for i, (it, en, wrong, note) in enumerate(ESSERE_STARE)],
        "avere_essere": [
            {"id": f"aux{i+1:03d}", "it": it, "en": en, "wrong": wrong, "note": note}
            for i, (it, en, wrong, note) in enumerate(AVERE_ESSERE)],
    }

    # ---- integrity ---------------------------------------------------------
    ids = [e["id"] for e in entries]
    assert len(ids) == len(set(ids)), "duplicate entry ids"
    keys = [(e["it"], e["pos"]) for e in entries]
    dupes = [k for k, c in collections.Counter(keys).items() if c > 1]
    assert not dupes, f"duplicate (it, pos) keys: {dupes}"
    byid = {e["id"]: e for e in entries}
    for e in entries:
        for field in ("antonyms", "synonyms"):
            for rid in e.get(field, []):
                assert rid in byid, f"{e['it']}: dangling {field} id {rid}"
        for c in e.get("cloze", []):
            assert c["it"].count("{") == 1 and c["it"].count("}") == 1, \
                f"{e['it']}: cloze must wrap exactly one target: {c['it']!r}"
        for group in ("noun_decl", "declension", "conjugation"):
            if isinstance(e.get(group), dict):
                for k, v in e[group].items():
                    assert v and v.strip(), f"{e['it']}: blank form for {group}.{k}"
        if e["pos"] == "verb":
            assert len(e["conjugation"]) == 6, f"{e['it']}: {len(e['conjugation'])} persons"
    seen_special = set()
    for bank, items in special.items():
        assert items, f"{bank}: empty bank"
        for it in items:
            assert it["id"] not in seen_special, f"duplicate special id {it['id']}"
            seen_special.add(it["id"])
            assert it["it"].count("{") == 1 and it["it"].count("}") == 1, \
                f"{bank} {it['id']}: must wrap exactly one target"
            assert it["wrong"], f"{bank} {it['id']}: missing counterpart"
            answer = it["it"].split("{")[1].split("}")[0]
            assert answer != it["wrong"], f"{bank} {it['id']}: answer equals counterpart"
            assert it["note"], f"{bank} {it['id']}: missing rule note"

    data = {"entries": entries,
            "meta": {"language": "Italian", "reference": "English",
                     "level": "A1-A2", "version": "v1"},
            "special": special}
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    counts = collections.Counter(e["pos"] for e in entries)
    print(f"wrote {os.path.normpath(OUT)}: {len(entries)} entries")
    print("  " + " · ".join(f"{v} {k}" for k, v in counts.most_common()))
    print(f"  cloze: {attached} sentences across {len(CLOZE)} words")
    print(f"  antonyms: {len(ANTONYMS)} pairs · synonyms: {len(SYNONYMS)} pairs")
    print(f"  special: essere_stare {len(special['essere_stare'])} · "
          f"avere_essere {len(special['avere_essere'])}")


if __name__ == "__main__":
    build()
