#!/usr/bin/env python3
"""Build vocab_la.json from curated dictionary entries + the morphology generator.

Source lists are compact (the forms a Latin dictionary actually prints); every
paradigm is expanded by latin_morph.py and assert-guarded there. Run:
    python3 scripts/build_latin_vocab.py
then rebuild + validate the trainer as usual.
"""
import json, os, sys, collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from latin_morph import decline_noun, conjugate_verb, decline_adjective

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'vocab_la.json')

# ---------------------------------------------------------------------------
# NOUNS: (nominative, genitive, gender, declension, i-stem?, English, lesson)
# Plural-only nouns are listed in PLURAL_ONLY_NOUNS below and give their
# genitive PLURAL instead (castra, castrōrum) since they have no singular.
# ---------------------------------------------------------------------------
NOUNS = [
    # --- L1 people & family -------------------------------------------------
    ("puella", "puellae", "f", 1, False, "girl", "1"),
    ("fēmina", "fēminae", "f", 1, False, "woman", "1"),
    ("puer", "puerī", "m", 2, False, "boy", "1"),
    ("vir", "virī", "m", 2, False, "man", "1"),
    ("homō", "hominis", "m", 3, False, "man, human being", "1"),
    ("pater", "patris", "m", 3, False, "father", "1"),
    ("māter", "mātris", "f", 3, False, "mother", "1"),
    ("frāter", "frātris", "m", 3, False, "brother", "1"),
    ("soror", "sorōris", "f", 3, False, "sister", "1"),
    ("fīlius", "fīliī", "m", 2, False, "son", "1"),
    ("fīlia", "fīliae", "f", 1, False, "daughter", "1"),
    ("amīcus", "amīcī", "m", 2, False, "friend", "1"),
    ("inimīcus", "inimīcī", "m", 2, False, "enemy (personal)", "1"),
    ("dominus", "dominī", "m", 2, False, "master, lord", "1"),
    ("domina", "dominae", "f", 1, False, "mistress, lady", "1"),
    ("servus", "servī", "m", 2, False, "slave", "1"),
    ("ancilla", "ancillae", "f", 1, False, "maidservant", "1"),
    ("nauta", "nautae", "m", 1, False, "sailor", "1"),
    ("agricola", "agricolae", "m", 1, False, "farmer", "1"),
    ("poēta", "poētae", "m", 1, False, "poet", "1"),
    ("nōmen", "nōminis", "n", 3, False, "name", "1"),
    ("vīta", "vītae", "f", 1, False, "life", "1"),
    ("mors", "mortis", "f", 3, True, "death", "1"),
    ("cīvis", "cīvis", "m", 3, True, "citizen", "1"),
    ("populus", "populī", "m", 2, False, "people", "1"),
    ("turba", "turbae", "f", 1, False, "crowd", "1"),
    ("comes", "comitis", "m", 3, False, "companion", "1"),
    ("hospes", "hospitis", "m", 3, False, "guest, host", "1"),
    ("senex", "senis", "m", 3, False, "old man", "1"),
    ("iuvenis", "iuvenis", "m", 3, True, "young man", "1"),

    # --- L2 house & daily life ---------------------------------------------
    ("domus", "domūs", "f", 4, False, "house, home", "2"),
    ("vīlla", "vīllae", "f", 1, False, "country house, villa", "2"),
    ("iānua", "iānuae", "f", 1, False, "door", "2"),
    ("hortus", "hortī", "m", 2, False, "garden, orchard", "2"),
    ("mēnsa", "mēnsae", "f", 1, False, "table", "2"),
    ("cubiculum", "cubiculī", "n", 2, False, "bedroom", "2"),
    ("culīna", "culīnae", "f", 1, False, "kitchen", "2"),
    ("ātrium", "ātriī", "n", 2, False, "atrium, hall", "2"),
    ("mūrus", "mūrī", "m", 2, False, "wall", "2"),
    ("tēctum", "tēctī", "n", 2, False, "roof, house", "2"),
    ("fenestra", "fenestrae", "f", 1, False, "window", "2"),
    ("lectus", "lectī", "m", 2, False, "bed, couch", "2"),
    ("aqua", "aquae", "f", 1, False, "water", "2"),
    ("ignis", "ignis", "m", 3, True, "fire", "2"),
    ("lūmen", "lūminis", "n", 3, False, "light, lamp", "2"),
    ("vestis", "vestis", "f", 3, True, "clothing, garment", "2"),
    ("toga", "togae", "f", 1, False, "toga", "2"),
    ("pecūnia", "pecūniae", "f", 1, False, "money", "2"),
    ("labor", "labōris", "m", 3, False, "work, toil", "2"),
    ("ōtium", "ōtiī", "n", 2, False, "leisure", "2"),
    ("negōtium", "negōtiī", "n", 2, False, "business, task", "2"),
    ("officium", "officiī", "n", 2, False, "duty", "2"),

    # --- L3 town, forum & buildings ----------------------------------------
    ("urbs", "urbis", "f", 3, True, "city", "3"),
    ("oppidum", "oppidī", "n", 2, False, "town", "3"),
    ("via", "viae", "f", 1, False, "road, way, street", "3"),
    ("forum", "forī", "n", 2, False, "forum, marketplace", "3"),
    ("templum", "templī", "n", 2, False, "temple, shrine", "3"),
    ("theātrum", "theātrī", "n", 2, False, "theatre", "3"),
    ("taberna", "tabernae", "f", 1, False, "shop, inn", "3"),
    ("porta", "portae", "f", 1, False, "gate", "3"),
    ("pōns", "pontis", "m", 3, True, "bridge", "3"),
    ("turris", "turris", "f", 3, True, "tower", "3"),
    ("aedificium", "aedificiī", "n", 2, False, "building", "3"),
    ("columna", "columnae", "f", 1, False, "column", "3"),
    ("statua", "statuae", "f", 1, False, "statue", "3"),
    ("locus", "locī", "m", 2, False, "place", "3"),
    ("pars", "partis", "f", 3, True, "part", "3"),

    # --- L4 food & farming --------------------------------------------------
    ("cibus", "cibī", "m", 2, False, "food", "4"),
    ("pānis", "pānis", "m", 3, True, "bread", "4"),
    ("vīnum", "vīnī", "n", 2, False, "wine", "4"),
    ("caro", "carnis", "f", 3, True, "meat, flesh", "4"),
    ("ōvum", "ōvī", "n", 2, False, "egg", "4"),
    ("cēna", "cēnae", "f", 1, False, "dinner", "4"),
    ("mel", "mellis", "n", 3, False, "honey", "4"),
    ("sāl", "salis", "m", 3, False, "salt", "4"),
    ("ager", "agrī", "m", 2, False, "field", "4"),
    ("terra", "terrae", "f", 1, False, "land, earth", "4"),
    ("frūmentum", "frūmentī", "n", 2, False, "grain, corn", "4"),
    ("arbor", "arboris", "f", 3, False, "tree", "4"),
    ("flōs", "flōris", "m", 3, False, "flower", "4"),
    ("rūs", "rūris", "n", 3, False, "countryside", "4"),
    ("fructus", "fructūs", "m", 4, False, "fruit, produce", "4"),

    # --- L5 body, health & senses ------------------------------------------
    ("corpus", "corporis", "n", 3, False, "body", "5"),
    ("caput", "capitis", "n", 3, False, "head", "5"),
    ("manus", "manūs", "f", 4, False, "hand, band of men", "5"),
    ("pēs", "pedis", "m", 3, False, "foot", "5"),
    ("oculus", "oculī", "m", 2, False, "eye", "5"),
    ("auris", "auris", "f", 3, True, "ear", "5"),
    ("ōs", "ōris", "n", 3, False, "mouth, face", "5"),
    ("cor", "cordis", "n", 3, True, "heart", "5"),
    ("sanguis", "sanguinis", "m", 3, False, "blood", "5"),
    ("vōx", "vōcis", "f", 3, False, "voice", "5"),
    ("vulnus", "vulneris", "n", 3, False, "wound", "5"),
    ("dolor", "dolōris", "m", 3, False, "pain, grief", "5"),
    ("somnus", "somnī", "m", 2, False, "sleep", "5"),
    ("morbus", "morbī", "m", 2, False, "disease", "5"),
    ("salūs", "salūtis", "f", 3, False, "health, safety", "5"),
    ("vīs", "vīs", "f", 3, True, "force, strength", "5"),

    # --- L6 school, writing & words ----------------------------------------
    ("liber", "librī", "m", 2, False, "book", "6"),
    ("littera", "litterae", "f", 1, False, "letter (of the alphabet)", "6"),
    ("verbum", "verbī", "n", 2, False, "word", "6"),
    ("magister", "magistrī", "m", 2, False, "teacher, master", "6"),
    ("discipulus", "discipulī", "m", 2, False, "pupil, student", "6"),
    ("schola", "scholae", "f", 1, False, "school", "6"),
    ("fābula", "fābulae", "f", 1, False, "story, play", "6"),
    ("carmen", "carminis", "n", 3, False, "song, poem", "6"),
    ("lingua", "linguae", "f", 1, False, "tongue, language", "6"),
    ("sententia", "sententiae", "f", 1, False, "opinion, sentence", "6"),
    ("exemplum", "exemplī", "n", 2, False, "example", "6"),
    ("studium", "studiī", "n", 2, False, "study, enthusiasm", "6"),
    ("ingenium", "ingeniī", "n", 2, False, "talent, character", "6"),
    ("mēns", "mentis", "f", 3, True, "mind", "6"),
    ("memoria", "memoriae", "f", 1, False, "memory", "6"),
    ("veritās", "veritātis", "f", 3, False, "truth", "6"),

    # --- L7 army, war & weapons --------------------------------------------
    ("bellum", "bellī", "n", 2, False, "war", "7"),
    ("pāx", "pācis", "f", 3, False, "peace", "7"),
    ("mīles", "mīlitis", "m", 3, False, "soldier", "7"),
    ("dux", "ducis", "m", 3, False, "leader, general", "7"),
    ("exercitus", "exercitūs", "m", 4, False, "army", "7"),
    ("legiō", "legiōnis", "f", 3, False, "legion", "7"),
    ("hostis", "hostis", "m", 3, True, "enemy (of the state)", "7"),
    ("gladius", "gladiī", "m", 2, False, "sword", "7"),
    ("hasta", "hastae", "f", 1, False, "spear", "7"),
    ("scūtum", "scūtī", "n", 2, False, "shield", "7"),
    ("proelium", "proeliī", "n", 2, False, "battle", "7"),
    ("victōria", "victōriae", "f", 1, False, "victory", "7"),
    ("perīculum", "perīculī", "n", 2, False, "danger", "7"),
    ("virtūs", "virtūtis", "f", 3, False, "courage, virtue", "7"),
    ("clāmor", "clāmōris", "m", 3, False, "shout, noise", "7"),
    ("custōs", "custōdis", "m", 3, False, "guard", "7"),

    # --- L8 government, law & Rome -----------------------------------------
    ("rēx", "rēgis", "m", 3, False, "king", "8"),
    ("rēgīna", "rēgīnae", "f", 1, False, "queen", "8"),
    ("cōnsul", "cōnsulis", "m", 3, False, "consul", "8"),
    ("senātus", "senātūs", "m", 4, False, "senate", "8"),
    ("lēx", "lēgis", "f", 3, False, "law", "8"),
    ("iūs", "iūris", "n", 3, False, "right, justice", "8"),
    ("imperium", "imperiī", "n", 2, False, "command, empire", "8"),
    ("rēs", "reī", "f", 5, False, "thing, matter, affair", "8"),
    ("cōnsilium", "cōnsiliī", "n", 2, False, "plan, advice", "8"),
    ("nūntius", "nūntiī", "m", 2, False, "messenger, message", "8"),
    ("praemium", "praemiī", "n", 2, False, "reward", "8"),
    ("poena", "poenae", "f", 1, False, "punishment, penalty", "8"),
    ("gēns", "gentis", "f", 3, True, "tribe, people, family", "8"),
    ("patria", "patriae", "f", 1, False, "fatherland, country", "8"),
    ("glōria", "glōriae", "f", 1, False, "glory, fame", "8"),
    ("honor", "honōris", "m", 3, False, "honour, office", "8"),
    ("potestās", "potestātis", "f", 3, False, "power, authority", "8"),

    # --- L9 gods, religion & myth ------------------------------------------
    ("deus", "deī", "m", 2, False, "god", "9"),
    ("dea", "deae", "f", 1, False, "goddess", "9"),
    ("sacerdōs", "sacerdōtis", "m", 3, False, "priest", "9"),
    ("āra", "ārae", "f", 1, False, "altar", "9"),
    ("sacrificium", "sacrificiī", "n", 2, False, "sacrifice", "9"),
    ("fātum", "fātī", "n", 2, False, "fate, destiny", "9"),
    ("fortūna", "fortūnae", "f", 1, False, "fortune, luck", "9"),
    ("animus", "animī", "m", 2, False, "mind, spirit, courage", "9"),
    ("anima", "animae", "f", 1, False, "soul, breath", "9"),
    ("umbra", "umbrae", "f", 1, False, "shadow, ghost", "9"),
    ("mōnstrum", "mōnstrī", "n", 2, False, "monster, omen", "9"),
    ("Iuppiter", "Iovis", "m", 3, False, "Jupiter", "9"),
    ("caelum", "caelī", "n", 2, False, "sky, heaven", "9"),
    ("nūmen", "nūminis", "n", 3, False, "divine power", "9"),

    # --- L10 travel, sea & geography ---------------------------------------
    ("mare", "maris", "n", 3, True, "sea", "10"),
    ("nāvis", "nāvis", "f", 3, True, "ship", "10"),
    ("portus", "portūs", "m", 4, False, "harbour, port", "10"),
    ("īnsula", "īnsulae", "f", 1, False, "island, apartment block", "10"),
    ("unda", "undae", "f", 1, False, "wave", "10"),
    ("ventus", "ventī", "m", 2, False, "wind", "10"),
    ("flūmen", "flūminis", "n", 3, False, "river", "10"),
    ("mōns", "montis", "m", 3, True, "mountain", "10"),
    ("silva", "silvae", "f", 1, False, "wood, forest", "10"),
    ("campus", "campī", "m", 2, False, "plain, field", "10"),
    ("iter", "itineris", "n", 3, False, "journey, route", "10"),
    ("equus", "equī", "m", 2, False, "horse", "10"),
    ("currus", "currūs", "m", 4, False, "chariot", "10"),
    ("rīpa", "rīpae", "f", 1, False, "bank (of a river)", "10"),
    ("saxum", "saxī", "n", 2, False, "rock, stone", "10"),
    ("lītus", "lītoris", "n", 3, False, "shore", "10"),

    # --- L11 time, seasons & weather ---------------------------------------
    ("tempus", "temporis", "n", 3, False, "time", "11"),
    ("diēs", "diēī", "m", 5, False, "day", "11"),
    ("nox", "noctis", "f", 3, True, "night", "11"),
    ("annus", "annī", "m", 2, False, "year", "11"),
    ("mēnsis", "mēnsis", "m", 3, True, "month", "11"),
    ("hōra", "hōrae", "f", 1, False, "hour", "11"),
    ("aestās", "aestātis", "f", 3, False, "summer", "11"),
    ("hiems", "hiemis", "f", 3, False, "winter", "11"),
    ("vēr", "vēris", "n", 3, False, "spring", "11"),
    ("sōl", "sōlis", "m", 3, False, "sun", "11"),
    ("lūna", "lūnae", "f", 1, False, "moon", "11"),
    ("stēlla", "stēllae", "f", 1, False, "star", "11"),
    ("nūbēs", "nūbis", "f", 3, True, "cloud", "11"),
    ("imber", "imbris", "m", 3, True, "rain, shower", "11"),
    ("lūx", "lūcis", "f", 3, False, "light, daylight", "11"),

    # --- L12 animals & nature ----------------------------------------------
    ("animal", "animālis", "n", 3, True, "animal", "12"),
    ("canis", "canis", "m", 3, False, "dog", "12"),
    ("avis", "avis", "f", 3, True, "bird", "12"),
    ("piscis", "piscis", "m", 3, True, "fish", "12"),
    ("leō", "leōnis", "m", 3, False, "lion", "12"),
    ("lupus", "lupī", "m", 2, False, "wolf", "12"),
    ("bōs", "bovis", "m", 3, False, "ox, cow", "12"),
    ("ovis", "ovis", "f", 3, True, "sheep", "12"),
    ("serpēns", "serpentis", "f", 3, True, "snake", "12"),
    ("aquila", "aquilae", "f", 1, False, "eagle", "12"),

    # === batch 2 =========================================================
    # L1 people
    ("uxor", "uxōris", "f", 3, False, "wife", "1"),
    ("marītus", "marītī", "m", 2, False, "husband", "1"),
    ("avus", "avī", "m", 2, False, "grandfather", "1"),
    ("avia", "aviae", "f", 1, False, "grandmother", "1"),
    ("coniūnx", "coniugis", "m", 3, False, "husband, wife, spouse", "1"),
    ("īnfāns", "īnfantis", "m", 3, True, "infant, baby", "1"),
    ("adulēscēns", "adulēscentis", "m", 3, True, "young man", "1"),
    ("vīcīnus", "vīcīnī", "m", 2, False, "neighbour", "1"),
    ("captīvus", "captīvī", "m", 2, False, "prisoner, captive", "1"),
    ("coquus", "coquī", "m", 2, False, "cook", "2"),
    ("mercātor", "mercātōris", "m", 3, False, "merchant, trader", "2"),
    ("medicus", "medicī", "m", 2, False, "doctor", "5"),
    ("pictor", "pictōris", "m", 3, False, "painter", "6"),
    ("faber", "fabrī", "m", 2, False, "craftsman, smith", "2"),
    ("senātor", "senātōris", "m", 3, False, "senator", "8"),
    ("magistrātus", "magistrātūs", "m", 4, False, "magistrate, office", "8"),
    ("praetor", "praetōris", "m", 3, False, "praetor", "8"),
    ("iūdex", "iūdicis", "m", 3, False, "judge", "8"),
    ("testis", "testis", "m", 3, True, "witness", "8"),
    ("gladiātor", "gladiātōris", "m", 3, False, "gladiator", "3"),
    # L2 house & objects
    ("tabula", "tabulae", "f", 1, False, "writing tablet, board", "6"),
    ("cēra", "cērae", "f", 1, False, "wax", "6"),
    ("stilus", "stilī", "m", 2, False, "pen, stylus", "6"),
    ("epistula", "epistulae", "f", 1, False, "letter, epistle", "6"),
    ("pōculum", "pōculī", "n", 2, False, "cup", "2"),
    ("urna", "urnae", "f", 1, False, "jar, urn", "2"),
    ("culter", "cultrī", "m", 2, False, "knife", "2"),
    ("catēna", "catēnae", "f", 1, False, "chain", "2"),
    ("clāvis", "clāvis", "f", 3, True, "key", "2"),
    ("fūnis", "fūnis", "m", 3, True, "rope", "2"),
    ("ānulus", "ānulī", "m", 2, False, "ring", "2"),
    ("gemma", "gemmae", "f", 1, False, "jewel, gem", "2"),
    ("argentum", "argentī", "n", 2, False, "silver", "2"),
    ("aurum", "aurī", "n", 2, False, "gold", "2"),
    ("ferrum", "ferrī", "n", 2, False, "iron, sword", "2"),
    ("marmor", "marmoris", "n", 3, False, "marble", "3"),
    ("lapis", "lapidis", "m", 3, False, "stone", "3"),
    # L3 town & entertainment
    ("lūdus", "lūdī", "m", 2, False, "game, school", "3"),
    ("circus", "circī", "m", 2, False, "circus, racetrack", "3"),
    ("spectāculum", "spectāculī", "n", 2, False, "show, spectacle", "3"),
    ("cīvitās", "cīvitātis", "f", 3, False, "state, citizenship", "8"),
    ("ōrdō", "ōrdinis", "m", 3, False, "order, rank, row", "8"),
    ("numerus", "numerī", "m", 2, False, "number", "11"),
    ("modus", "modī", "m", 2, False, "way, manner, measure", "6"),
    ("initium", "initiī", "n", 2, False, "beginning", "11"),
    ("fīnis", "fīnis", "m", 3, True, "end, boundary", "11"),
    ("saeculum", "saeculī", "n", 2, False, "age, century", "11"),
    ("aetās", "aetātis", "f", 3, False, "age, lifetime", "11"),
    # L4 food & plants
    ("lac", "lactis", "n", 3, False, "milk", "4"),
    ("oleum", "oleī", "n", 2, False, "oil", "4"),
    ("olīva", "olīvae", "f", 1, False, "olive", "4"),
    ("vītis", "vītis", "f", 3, True, "vine", "4"),
    ("rāmus", "rāmī", "m", 2, False, "branch", "4"),
    ("folium", "foliī", "n", 2, False, "leaf", "4"),
    ("sēmen", "sēminis", "n", 3, False, "seed", "4"),
    ("herba", "herbae", "f", 1, False, "grass, herb", "4"),
    ("quercus", "quercūs", "f", 4, False, "oak tree", "4"),
    # L5 feelings & mind
    ("spēs", "speī", "f", 5, False, "hope", "5"),
    ("metus", "metūs", "m", 4, False, "fear, dread", "5"),
    ("timor", "timōris", "m", 3, False, "fear", "5"),
    ("cūra", "cūrae", "f", 1, False, "care, worry", "5"),
    ("īra", "īrae", "f", 1, False, "anger", "5"),
    ("odium", "odiī", "n", 2, False, "hatred", "5"),
    ("amor", "amōris", "m", 3, False, "love", "5"),
    ("amīcitia", "amīcitiae", "f", 1, False, "friendship", "5"),
    ("gaudium", "gaudiī", "n", 2, False, "joy", "5"),
    # L6-8 abstract & law
    ("laus", "laudis", "f", 3, False, "praise", "6"),
    ("fāma", "fāmae", "f", 1, False, "fame, reputation, rumour", "6"),
    ("scelus", "sceleris", "n", 3, False, "crime, wickedness", "8"),
    ("culpa", "culpae", "f", 1, False, "fault, blame", "8"),
    ("crux", "crucis", "f", 3, True, "cross", "8"),
    ("carcer", "carceris", "m", 3, False, "prison", "8"),
    ("mōs", "mōris", "m", 3, False, "custom, habit", "8"),
    ("cōnsuētūdō", "cōnsuētūdinis", "f", 3, False, "custom, habit", "8"),
    ("foedus", "foederis", "n", 3, False, "treaty", "8"),
    ("ōmen", "ōminis", "n", 3, False, "omen, sign", "9"),
    ("lūcus", "lūcī", "m", 2, False, "sacred grove", "9"),
    # L7 war
    ("impetus", "impetūs", "m", 4, False, "attack, charge", "7"),
    ("lēgātus", "lēgātī", "m", 2, False, "envoy, legate", "7"),
    ("praesidium", "praesidiī", "n", 2, False, "garrison, protection", "7"),
    ("cohors", "cohortis", "f", 3, True, "cohort", "7"),
    ("sagitta", "sagittae", "f", 1, False, "arrow", "7"),
    ("arcus", "arcūs", "m", 4, False, "bow, arch", "7"),
    ("tuba", "tubae", "f", 1, False, "trumpet", "7"),
    ("vēxillum", "vēxillī", "n", 2, False, "standard, banner", "7"),
    ("praeda", "praedae", "f", 1, False, "booty, plunder", "7"),
    # L10-12 nature & travel
    ("fōns", "fontis", "m", 3, True, "spring, fountain, source", "10"),
    ("lacus", "lacūs", "m", 4, False, "lake", "10"),
    ("collis", "collis", "m", 3, True, "hill", "10"),
    ("vallis", "vallis", "f", 3, True, "valley", "10"),
    ("spēlunca", "spēluncae", "f", 1, False, "cave", "10"),
    ("harēna", "harēnae", "f", 1, False, "sand, arena", "10"),
    ("pulvis", "pulveris", "m", 3, False, "dust", "10"),
    ("rēmus", "rēmī", "m", 2, False, "oar", "10"),
    ("vēlum", "vēlī", "n", 2, False, "sail, cloth", "10"),
    ("ancora", "ancorae", "f", 1, False, "anchor", "10"),
    ("nix", "nivis", "f", 3, True, "snow", "11"),
    ("fulmen", "fulminis", "n", 3, False, "lightning, thunderbolt", "11"),
    ("nebula", "nebulae", "f", 1, False, "mist, fog", "11"),
    ("autumnus", "autumnī", "m", 2, False, "autumn", "11"),
    ("vesper", "vesperī", "m", 2, False, "evening", "11"),
    ("aurōra", "aurōrae", "f", 1, False, "dawn", "11"),
    ("cervus", "cervī", "m", 2, False, "deer, stag", "12"),
    ("taurus", "taurī", "m", 2, False, "bull", "12"),
    ("mūs", "mūris", "m", 3, True, "mouse", "12"),
    ("apis", "apis", "f", 3, True, "bee", "12"),

    # === batch 3 =========================================================
    ("dominium", "dominiī", "n", 2, False, "ownership, rule", "8"),
    ("cōnsulātus", "cōnsulātūs", "m", 4, False, "consulship", "8"),
    ("prōvincia", "prōvinciae", "f", 1, False, "province", "8"),
    ("rēgnum", "rēgnī", "n", 2, False, "kingdom, royal power", "8"),
    ("libertās", "libertātis", "f", 3, False, "freedom", "8"),
    ("servitūs", "servitūtis", "f", 3, False, "slavery", "8"),
    ("dignitās", "dignitātis", "f", 3, False, "dignity, rank", "8"),
    ("auctōritās", "auctōritātis", "f", 3, False, "authority, influence", "8"),
    ("iniūria", "iniūriae", "f", 1, False, "injustice, wrong", "8"),
    ("beneficium", "beneficiī", "n", 2, False, "kindness, favour", "8"),
    ("supplicium", "suppliciī", "n", 2, False, "punishment, execution", "8"),
    ("condiciō", "condiciōnis", "f", 3, False, "condition, terms", "8"),
    ("ōrātiō", "ōrātiōnis", "f", 3, False, "speech", "6"),
    ("ōrātor", "ōrātōris", "m", 3, False, "speaker, orator", "6"),
    ("scrīptor", "scrīptōris", "m", 3, False, "writer", "6"),
    ("versus", "versūs", "m", 4, False, "verse, line", "6"),
    ("volūmen", "volūminis", "n", 3, False, "roll, book", "6"),
    ("opīniō", "opīniōnis", "f", 3, False, "opinion, belief", "6"),
    ("ratiō", "ratiōnis", "f", 3, False, "reason, method, account", "6"),
    ("cōgitātiō", "cōgitātiōnis", "f", 3, False, "thought", "6"),
    ("scientia", "scientiae", "f", 1, False, "knowledge", "6"),
    ("sapientia", "sapientiae", "f", 1, False, "wisdom", "6"),
    ("doctrīna", "doctrīnae", "f", 1, False, "teaching, learning", "6"),
    ("error", "errōris", "m", 3, False, "mistake, wandering", "6"),
    ("occāsiō", "occāsiōnis", "f", 3, False, "opportunity", "11"),
    ("mōmentum", "mōmentī", "n", 2, False, "moment, importance", "11"),
    ("spatium", "spatiī", "n", 2, False, "space, distance, interval", "11"),
    ("intervāllum", "intervāllī", "n", 2, False, "interval, gap", "11"),
    ("mora", "morae", "f", 1, False, "delay", "11"),
    ("celeritās", "celeritātis", "f", 3, False, "speed", "11"),
    ("magnitūdō", "magnitūdinis", "f", 3, False, "size, greatness", "11"),
    ("multitūdō", "multitūdinis", "f", 3, False, "crowd, large number", "11"),
    ("altitūdō", "altitūdinis", "f", 3, False, "height, depth", "11"),
    ("lātitūdō", "lātitūdinis", "f", 3, False, "width", "11"),
    ("pondus", "ponderis", "n", 3, False, "weight", "11"),
    ("mēnsūra", "mēnsūrae", "f", 1, False, "measure", "11"),
    ("regiō", "regiōnis", "f", 3, False, "region, district", "10"),
    ("ōra", "ōrae", "f", 1, False, "shore, coast", "10"),
    ("prōmunturium", "prōmunturiī", "n", 2, False, "headland, cape", "10"),
    ("tempestās", "tempestātis", "f", 3, False, "storm, weather", "10"),
    ("procella", "procellae", "f", 1, False, "gale, squall", "10"),
    ("gubernātor", "gubernātōris", "m", 3, False, "helmsman, pilot", "10"),
    ("vestīgium", "vestīgiī", "n", 2, False, "footprint, trace", "10"),
    ("vehiculum", "vehiculī", "n", 2, False, "vehicle, cart", "10"),
    ("plaustrum", "plaustrī", "n", 2, False, "wagon, cart", "10"),
    ("sella", "sellae", "f", 1, False, "seat, chair", "2"),
    ("speculum", "speculī", "n", 2, False, "mirror", "2"),
    ("pecten", "pectinis", "m", 3, False, "comb", "2"),
    ("vās", "vāsis", "n", 3, False, "vessel, container", "2"),
    ("cista", "cistae", "f", 1, False, "box, chest", "2"),
    ("saccus", "saccī", "m", 2, False, "bag, sack", "2"),
    ("scāla", "scālae", "f", 1, False, "ladder, stair", "2"),
    ("pariēs", "parietis", "m", 3, False, "wall (of a house)", "2"),
    ("pavīmentum", "pavīmentī", "n", 2, False, "floor, pavement", "2"),
    ("focus", "focī", "m", 2, False, "hearth, fireplace", "2"),
    ("fūmus", "fūmī", "m", 2, False, "smoke", "2"),
    ("cinis", "cineris", "m", 3, False, "ash", "2"),
    ("carbō", "carbōnis", "m", 3, False, "coal, charcoal", "2"),
    ("umerus", "umerī", "m", 2, False, "shoulder", "5"),
    ("bracchium", "bracchiī", "n", 2, False, "arm", "5"),
    ("digitus", "digitī", "m", 2, False, "finger, toe", "5"),
    ("genū", "genūs", "n", 4, False, "knee", "5"),
    ("crūs", "crūris", "n", 3, False, "leg, shin", "5"),
    ("dēns", "dentis", "m", 3, True, "tooth", "5"),
    ("nāsus", "nāsī", "m", 2, False, "nose", "5"),
    ("capillus", "capillī", "m", 2, False, "hair", "5"),
    ("pectus", "pectoris", "n", 3, False, "chest, breast, heart", "5"),
    ("venter", "ventris", "m", 3, True, "belly, stomach", "5"),
    ("tergum", "tergī", "n", 2, False, "back", "5"),
    ("pellis", "pellis", "f", 3, True, "skin, hide", "5"),
    ("remedium", "remediī", "n", 2, False, "cure, remedy", "5"),
    ("medicīna", "medicīnae", "f", 1, False, "medicine", "5"),
    ("cicātrīx", "cicātrīcis", "f", 3, True, "scar", "5"),
    ("febris", "febris", "f", 3, True, "fever", "5"),
    ("convīvium", "convīviī", "n", 2, False, "feast, banquet", "4"),
    ("gustus", "gustūs", "m", 4, False, "taste", "4"),
    ("farīna", "farīnae", "f", 1, False, "flour, meal", "4"),
    ("holus", "holeris", "n", 3, False, "vegetable", "4"),
    ("pōmum", "pōmī", "n", 2, False, "fruit, apple", "4"),
    ("ūva", "ūvae", "f", 1, False, "grape", "4"),
    ("nux", "nucis", "f", 3, True, "nut", "4"),
    ("grānum", "grānī", "n", 2, False, "grain, seed", "4"),
    ("messis", "messis", "f", 3, True, "harvest", "4"),
    ("arātrum", "arātrī", "n", 2, False, "plough", "4"),
    ("falx", "falcis", "f", 3, True, "sickle, scythe", "4"),
    ("pāstor", "pāstōris", "m", 3, False, "shepherd", "4"),
    ("grex", "gregis", "m", 3, False, "flock, herd", "4"),
    ("stabulum", "stabulī", "n", 2, False, "stable, stall", "4"),
    ("porcus", "porcī", "m", 2, False, "pig", "12"),
    ("capra", "caprae", "f", 1, False, "goat", "12"),
    ("gallus", "gallī", "m", 2, False, "cock, rooster", "12"),
    ("columba", "columbae", "f", 1, False, "dove, pigeon", "12"),
    ("corvus", "corvī", "m", 2, False, "raven, crow", "12"),
    ("vulpēs", "vulpis", "f", 3, True, "fox", "12"),
    ("ursus", "ursī", "m", 2, False, "bear", "12"),
    ("elephantus", "elephantī", "m", 2, False, "elephant", "12"),
    ("āla", "ālae", "f", 1, False, "wing", "12"),
    ("penna", "pennae", "f", 1, False, "feather", "12"),
    ("cauda", "caudae", "f", 1, False, "tail", "12"),
    ("nīdus", "nīdī", "m", 2, False, "nest", "12"),
    ("fossa", "fossae", "f", 1, False, "ditch, trench", "7"),
    ("vāllum", "vāllī", "n", 2, False, "rampart, palisade", "7"),
    ("tēlum", "tēlī", "n", 2, False, "weapon, missile", "7"),
    ("caedēs", "caedis", "f", 3, True, "slaughter, murder", "7"),
    ("clādēs", "clādis", "f", 3, True, "disaster, defeat", "7"),
    ("fuga", "fugae", "f", 1, False, "flight, escape", "7"),
    ("triumphus", "triumphī", "m", 2, False, "triumph", "7"),
    ("statiō", "statiōnis", "f", 3, False, "post, station", "7"),
    ("centuriō", "centuriōnis", "m", 3, False, "centurion", "7"),
    ("eques", "equitis", "m", 3, False, "horseman, knight", "7"),
    ("pedes", "peditis", "m", 3, False, "foot-soldier", "7"),
    ("sacrāmentum", "sacrāmentī", "n", 2, False, "oath, sacred obligation", "9"),
    ("vōtum", "vōtī", "n", 2, False, "vow, prayer", "9"),
    ("simulācrum", "simulācrī", "n", 2, False, "image, statue", "9"),
    ("mysterium", "mysteriī", "n", 2, False, "mystery, secret rite", "9"),
    ("hērōs", "hērōis", "m", 3, False, "hero", "9"),
    ("gigās", "gigantis", "m", 3, False, "giant", "9"),
    ("nympha", "nymphae", "f", 1, False, "nymph", "9"),
]

# Plural-only nouns: (nom pl, GEN PL, gender, declension, i-stem?, English, lesson)
PLURAL_ONLY_NOUNS = [
    ("moenia", "moenium", "n", 3, True, "city walls", "3"),
    ("castra", "castrōrum", "n", 2, False, "camp", "7"),
    ("arma", "armōrum", "n", 2, False, "arms, weapons", "7"),
    ("tenebrae", "tenebrārum", "f", 1, False, "darkness", "11"),
    ("īnsidiae", "īnsidiārum", "f", 1, False, "ambush, trap", "7"),
    ("dīvitiae", "dīvitiārum", "f", 1, False, "riches, wealth", "8"),

    ("thermae", "thermārum", "f", 1, False, "public baths", "3"),
    ("līberī", "līberōrum", "m", 2, False, "children", "1"),
]

# ---------------------------------------------------------------------------
# VERBS: (principal parts, conjugation, English, lesson)
# ---------------------------------------------------------------------------
VERBS = [
    # --- L13 core verbs I: 1st & 2nd conjugation ---------------------------
    (["amō", "amāre", "amāvī", "amātum"], 1, "to love", "13"),
    (["laudō", "laudāre", "laudāvī", "laudātum"], 1, "to praise", "13"),
    (["portō", "portāre", "portāvī", "portātum"], 1, "to carry", "13"),
    (["vocō", "vocāre", "vocāvī", "vocātum"], 1, "to call", "13"),
    (["parō", "parāre", "parāvī", "parātum"], 1, "to prepare", "13"),
    (["pugnō", "pugnāre", "pugnāvī", "pugnātum"], 1, "to fight", "13"),
    (["ambulō", "ambulāre", "ambulāvī", "ambulātum"], 1, "to walk", "13"),
    (["labōrō", "labōrāre", "labōrāvī", "labōrātum"], 1, "to work", "13"),
    (["spectō", "spectāre", "spectāvī", "spectātum"], 1, "to watch, look at", "13"),
    (["intrō", "intrāre", "intrāvī", "intrātum"], 1, "to enter", "13"),
    (["nārrō", "nārrāre", "nārrāvī", "nārrātum"], 1, "to tell, relate", "13"),
    (["superō", "superāre", "superāvī", "superātum"], 1, "to overcome, surpass", "13"),
    (["servō", "servāre", "servāvī", "servātum"], 1, "to save, guard", "13"),
    (["oppugnō", "oppugnāre", "oppugnāvī", "oppugnātum"], 1, "to attack", "13"),
    (["exspectō", "exspectāre", "exspectāvī", "exspectātum"], 1, "to wait for, expect", "13"),
    (["rogō", "rogāre", "rogāvī", "rogātum"], 1, "to ask", "13"),
    (["dō", "dare", "dedī", "datum"], 1, "to give", "13"),
    (["stō", "stāre", "stetī", "statum"], 1, "to stand", "13"),
    (["habeō", "habēre", "habuī", "habitum"], 2, "to have, hold", "13"),
    (["videō", "vidēre", "vīdī", "vīsum"], 2, "to see", "13"),
    (["moneō", "monēre", "monuī", "monitum"], 2, "to warn, advise", "13"),
    (["teneō", "tenēre", "tenuī", "tentum"], 2, "to hold", "13"),
    (["timeō", "timēre", "timuī"], 2, "to fear", "13"),
    (["maneō", "manēre", "mānsī", "mānsum"], 2, "to remain, stay", "13"),
    (["moveō", "movēre", "mōvī", "mōtum"], 2, "to move", "13"),
    (["respondeō", "respondēre", "respondī", "respōnsum"], 2, "to reply", "13"),
    (["iubeō", "iubēre", "iussī", "iussum"], 2, "to order, bid", "13"),
    (["dēleō", "dēlēre", "dēlēvī", "dēlētum"], 2, "to destroy", "13"),
    (["terreō", "terrēre", "terruī", "territum"], 2, "to frighten", "13"),
    (["doceō", "docēre", "docuī", "doctum"], 2, "to teach", "13"),
    (["rīdeō", "rīdēre", "rīsī", "rīsum"], 2, "to laugh, smile", "13"),
    (["sedeō", "sedēre", "sēdī", "sessum"], 2, "to sit", "13"),

    # --- L14 core verbs II: 3rd, 4th & irregular ---------------------------
    (["regō", "regere", "rēxī", "rēctum"], 3, "to rule", "14"),
    (["dūcō", "dūcere", "dūxī", "ductum"], 3, "to lead", "14"),
    (["mittō", "mittere", "mīsī", "missum"], 3, "to send", "14"),
    (["dīcō", "dīcere", "dīxī", "dictum"], 3, "to say, speak", "14"),
    (["scrībō", "scrībere", "scrīpsī", "scrīptum"], 3, "to write", "14"),
    (["legō", "legere", "lēgī", "lēctum"], 3, "to read, choose", "14"),
    (["agō", "agere", "ēgī", "āctum"], 3, "to do, drive", "14"),
    (["pōnō", "pōnere", "posuī", "positum"], 3, "to place, put", "14"),
    (["vincō", "vincere", "vīcī", "victum"], 3, "to conquer", "14"),
    (["currō", "currere", "cucurrī", "cursum"], 3, "to run", "14"),
    (["petō", "petere", "petīvī", "petītum"], 3, "to seek, ask for", "14"),
    (["gerō", "gerere", "gessī", "gestum"], 3, "to carry on, wage", "14"),
    (["trahō", "trahere", "trāxī", "tractum"], 3, "to drag, draw", "14"),
    (["vīvō", "vīvere", "vīxī", "vīctum"], 3, "to live", "14"),
    (["bibō", "bibere", "bibī"], 3, "to drink", "14"),
    (["claudō", "claudere", "clausī", "clausum"], 3, "to close, shut", "14"),
    (["crēdō", "crēdere", "crēdidī", "crēditum"], 3, "to believe, trust", "14"),
    (["ostendō", "ostendere", "ostendī", "ostentum"], 3, "to show", "14"),
    (["capiō", "capere", "cēpī", "captum"], "3io", "to take, capture", "14"),
    (["faciō", "facere", "fēcī", "factum"], "3io", "to make, do", "14"),
    (["fugiō", "fugere", "fūgī", "fugitum"], "3io", "to flee", "14"),
    (["iaciō", "iacere", "iēcī", "iactum"], "3io", "to throw", "14"),
    (["accipiō", "accipere", "accēpī", "acceptum"], "3io", "to receive, accept", "14"),
    (["audiō", "audīre", "audīvī", "audītum"], 4, "to hear, listen to", "14"),
    (["veniō", "venīre", "vēnī", "ventum"], 4, "to come", "14"),
    (["inveniō", "invenīre", "invēnī", "inventum"], 4, "to find", "14"),
    (["dormiō", "dormīre", "dormīvī", "dormītum"], 4, "to sleep", "14"),
    (["sentiō", "sentīre", "sēnsī", "sēnsum"], 4, "to feel, perceive", "14"),
    (["custōdiō", "custōdīre", "custōdīvī", "custōdītum"], 4, "to guard", "14"),
    (["impediō", "impedīre", "impedīvī", "impedītum"], 4, "to hinder", "14"),
    (["sum", "esse", "fuī"], 1, "to be", "14"),
    (["possum", "posse", "potuī"], 1, "to be able, can", "14"),
    (["eō", "īre", "iī", "itum"], 1, "to go", "14"),
    (["ferō", "ferre", "tulī", "lātum"], 1, "to bring, carry, bear", "14"),
    (["volō", "velle", "voluī"], 1, "to wish, be willing", "14"),
    (["nōlō", "nōlle", "nōluī"], 1, "to be unwilling, refuse", "14"),
    (["mālō", "mālle", "māluī"], 1, "to prefer", "14"),

    # === batch 2 =========================================================
    (["nūntiō", "nūntiāre", "nūntiāvī", "nūntiātum"], 1, "to announce, report", "13"),
    (["cūrō", "cūrāre", "cūrāvī", "cūrātum"], 1, "to care for, look after", "13"),
    (["spērō", "spērāre", "spērāvī", "spērātum"], 1, "to hope", "13"),
    (["putō", "putāre", "putāvī", "putātum"], 1, "to think, consider", "13"),
    (["cōgitō", "cōgitāre", "cōgitāvī", "cōgitātum"], 1, "to think, ponder", "13"),
    (["festīnō", "festīnāre", "festīnāvī", "festīnātum"], 1, "to hurry", "13"),
    (["iuvō", "iuvāre", "iūvī", "iūtum"], 1, "to help, please", "13"),
    (["occupō", "occupāre", "occupāvī", "occupātum"], 1, "to seize, occupy", "13"),
    (["vulnerō", "vulnerāre", "vulnerāvī", "vulnerātum"], 1, "to wound", "13"),
    (["necō", "necāre", "necāvī", "necātum"], 1, "to kill", "13"),
    (["līberō", "līberāre", "līberāvī", "līberātum"], 1, "to free, set free", "13"),
    (["dubitō", "dubitāre", "dubitāvī", "dubitātum"], 1, "to doubt, hesitate", "13"),
    (["errō", "errāre", "errāvī", "errātum"], 1, "to wander, be wrong", "13"),
    (["habitō", "habitāre", "habitāvī", "habitātum"], 1, "to live, dwell", "13"),
    (["nāvigō", "nāvigāre", "nāvigāvī", "nāvigātum"], 1, "to sail", "13"),
    (["ōrō", "ōrāre", "ōrāvī", "ōrātum"], 1, "to beg, pray", "13"),
    (["cēlō", "cēlāre", "cēlāvī", "cēlātum"], 1, "to hide, conceal", "13"),
    (["mōnstrō", "mōnstrāre", "mōnstrāvī", "mōnstrātum"], 1, "to show, point out", "13"),
    (["temptō", "temptāre", "temptāvī", "temptātum"], 1, "to try, attempt", "13"),
    (["aedificō", "aedificāre", "aedificāvī", "aedificātum"], 1, "to build", "13"),
    (["cantō", "cantāre", "cantāvī", "cantātum"], 1, "to sing", "13"),
    (["salūtō", "salūtāre", "salūtāvī", "salūtātum"], 1, "to greet", "13"),
    (["clāmō", "clāmāre", "clāmāvī", "clāmātum"], 1, "to shout", "13"),
    (["lacrimō", "lacrimāre", "lacrimāvī", "lacrimātum"], 1, "to weep, cry", "13"),
    (["dēlectō", "dēlectāre", "dēlectāvī", "dēlectātum"], 1, "to delight, please", "13"),
    (["dēbeō", "dēbēre", "dēbuī", "dēbitum"], 2, "to owe, ought", "13"),
    (["iaceō", "iacēre", "iacuī"], 2, "to lie, lie down", "13"),
    (["noceō", "nocēre", "nocuī", "nocitum"], 2, "to harm (+ dat.)", "13"),
    (["pāreō", "pārēre", "pāruī"], 2, "to obey (+ dat.)", "13"),
    (["placeō", "placēre", "placuī", "placitum"], 2, "to please (+ dat.)", "13"),
    (["studeō", "studēre", "studuī"], 2, "to study, be eager for", "13"),
    (["taceō", "tacēre", "tacuī", "tacitum"], 2, "to be silent", "13"),
    (["valeō", "valēre", "valuī"], 2, "to be strong, be well", "13"),
    (["augeō", "augēre", "auxī", "auctum"], 2, "to increase", "13"),
    (["exerceō", "exercēre", "exercuī", "exercitum"], 2, "to train, exercise", "13"),
    (["praebeō", "praebēre", "praebuī", "praebitum"], 2, "to provide, offer", "13"),
    (["prohibeō", "prohibēre", "prohibuī", "prohibitum"], 2, "to prevent, forbid", "13"),
    (["sustineō", "sustinēre", "sustinuī", "sustentum"], 2, "to hold up, endure", "13"),
    (["cadō", "cadere", "cecidī", "cāsum"], 3, "to fall", "14"),
    (["cēdō", "cēdere", "cessī", "cessum"], 3, "to yield, withdraw", "14"),
    (["cognōscō", "cognōscere", "cognōvī", "cognitum"], 3, "to learn, get to know", "14"),
    (["cōgō", "cōgere", "coēgī", "coāctum"], 3, "to compel, gather", "14"),
    (["cōnstituō", "cōnstituere", "cōnstituī", "cōnstitūtum"], 3, "to decide, establish", "14"),
    (["contendō", "contendere", "contendī", "contentum"], 3, "to hurry, strive, contend", "14"),
    (["crēscō", "crēscere", "crēvī", "crētum"], 3, "to grow, increase", "14"),
    (["dēfendō", "dēfendere", "dēfendī", "dēfēnsum"], 3, "to defend", "14"),
    (["dēscendō", "dēscendere", "dēscendī", "dēscēnsum"], 3, "to come down, descend", "14"),
    (["discēdō", "discēdere", "discessī", "discessum"], 3, "to depart, go away", "14"),
    (["dīvidō", "dīvidere", "dīvīsī", "dīvīsum"], 3, "to divide, separate", "14"),
    (["emō", "emere", "ēmī", "ēmptum"], 3, "to buy", "14"),
    (["intellegō", "intellegere", "intellēxī", "intellēctum"], 3, "to understand", "14"),
    (["iungō", "iungere", "iūnxī", "iūnctum"], 3, "to join", "14"),
    (["pellō", "pellere", "pepulī", "pulsum"], 3, "to drive, push", "14"),
    (["prōmittō", "prōmittere", "prōmīsī", "prōmissum"], 3, "to promise", "14"),
    (["quaerō", "quaerere", "quaesīvī", "quaesītum"], 3, "to seek, ask", "14"),
    (["reddō", "reddere", "reddidī", "redditum"], 3, "to give back, restore", "14"),
    (["relinquō", "relinquere", "relīquī", "relictum"], 3, "to leave, abandon", "14"),
    (["rumpō", "rumpere", "rūpī", "ruptum"], 3, "to break, burst", "14"),
    (["solvō", "solvere", "solvī", "solūtum"], 3, "to loosen, release, pay", "14"),
    (["statuō", "statuere", "statuī", "statūtum"], 3, "to set up, decide", "14"),
    (["sūmō", "sūmere", "sūmpsī", "sūmptum"], 3, "to take up, assume", "14"),
    (["surgō", "surgere", "surrēxī", "surrēctum"], 3, "to rise, get up", "14"),
    (["tangō", "tangere", "tetigī", "tāctum"], 3, "to touch", "14"),
    (["tollō", "tollere", "sustulī", "sublātum"], 3, "to lift, raise, remove", "14"),
    (["trādō", "trādere", "trādidī", "trāditum"], 3, "to hand over, betray", "14"),
    (["vertō", "vertere", "vertī", "versum"], 3, "to turn", "14"),
    (["cupiō", "cupere", "cupīvī", "cupītum"], "3io", "to desire, want", "14"),
    (["incipiō", "incipere", "incēpī", "inceptum"], "3io", "to begin", "14"),
    (["interficiō", "interficere", "interfēcī", "interfectum"], "3io", "to kill", "14"),
    (["aperiō", "aperīre", "aperuī", "apertum"], 4, "to open", "14"),
    (["conveniō", "convenīre", "convēnī", "conventum"], 4, "to come together, meet", "14"),
    (["mūniō", "mūnīre", "mūnīvī", "mūnītum"], 4, "to fortify, build", "14"),
    (["nesciō", "nescīre", "nescīvī"], 4, "not to know", "14"),
    (["sciō", "scīre", "scīvī", "scītum"], 4, "to know", "14"),
    (["pūniō", "pūnīre", "pūnīvī", "pūnītum"], 4, "to punish", "14"),
    (["reperiō", "reperīre", "repperī", "repertum"], 4, "to find, discover", "14"),
    (["serviō", "servīre", "servīvī", "servītum"], 4, "to serve (+ dat.)", "14"),
    (["vestiō", "vestīre", "vestīvī", "vestītum"], 4, "to clothe, dress", "14"),

    # === batch 3 =========================================================
    (["abeō", "abīre", "abiī", "abitum"], 1, "to go away, depart", "14"),
    (["adeō", "adīre", "adiī", "aditum"], 1, "to approach, go to", "14"),
    (["exeō", "exīre", "exiī", "exitum"], 1, "to go out", "14"),
    (["redeō", "redīre", "rediī", "reditum"], 1, "to return, go back", "14"),
    (["pereō", "perīre", "periī", "peritum"], 1, "to perish, die", "14"),
    (["trānseō", "trānsīre", "trānsiī", "trānsitum"], 1, "to cross, go across", "14"),
    (["adsum", "adesse", "adfuī"], 1, "to be present, be here", "14"),
    (["absum", "abesse", "āfuī"], 1, "to be absent, be away", "14"),
    (["referō", "referre", "rettulī", "relātum"], 1, "to bring back, report", "14"),
    (["afferō", "afferre", "attulī", "allātum"], 1, "to bring to, deliver", "14"),
    (["auferō", "auferre", "abstulī", "ablātum"], 1, "to carry off, steal", "14"),
    (["offerō", "offerre", "obtulī", "oblātum"], 1, "to offer", "14"),
    (["accēdō", "accēdere", "accessī", "accessum"], 3, "to approach, come near", "14"),
    (["amittō", "amittere", "āmīsī", "āmissum"], 3, "to lose, let go", "14"),
    (["dīmittō", "dīmittere", "dīmīsī", "dīmissum"], 3, "to send away, dismiss", "14"),
    (["ēmittō", "ēmittere", "ēmīsī", "ēmissum"], 3, "to send out, release", "14"),
    (["permittō", "permittere", "permīsī", "permissum"], 3, "to allow, entrust", "14"),
    (["cōnsūmō", "cōnsūmere", "cōnsūmpsī", "cōnsūmptum"], 3, "to consume, use up", "14"),
    (["condō", "condere", "condidī", "conditum"], 3, "to found, store, hide", "14"),
    (["perdō", "perdere", "perdidī", "perditum"], 3, "to destroy, lose", "14"),
    (["dēpōnō", "dēpōnere", "dēposuī", "dēpositum"], 3, "to put down, lay aside", "14"),
    (["impōnō", "impōnere", "imposuī", "impositum"], 3, "to place on, impose", "14"),
    (["expōnō", "expōnere", "exposuī", "expositum"], 3, "to set out, explain", "14"),
    (["dīscō", "dīscere", "didicī"], 3, "to learn", "14"),
    (["dīligō", "dīligere", "dīlēxī", "dīlēctum"], 3, "to love, esteem", "14"),
    (["neglegō", "neglegere", "neglēxī", "neglēctum"], 3, "to neglect, disregard", "14"),
    (["premō", "premere", "pressī", "pressum"], 3, "to press, oppress", "14"),
    (["opprimō", "opprimere", "oppressī", "oppressum"], 3, "to crush, overwhelm", "14"),
    (["frangō", "frangere", "frēgī", "frāctum"], 3, "to break", "14"),
    (["fallō", "fallere", "fefellī", "falsum"], 3, "to deceive, cheat", "14"),
    (["fingō", "fingere", "fīnxī", "fictum"], 3, "to shape, invent, pretend", "14"),
    (["fluō", "fluere", "flūxī", "flūxum"], 3, "to flow", "14"),
    (["fundō", "fundere", "fūdī", "fūsum"], 3, "to pour, rout", "14"),
    (["laedō", "laedere", "laesī", "laesum"], 3, "to hurt, injure", "14"),
    (["lūdō", "lūdere", "lūsī", "lūsum"], 3, "to play, mock", "14"),
    (["mūtō", "mūtāre", "mūtāvī", "mūtātum"], 1, "to change", "13"),
    (["metuō", "metuere", "metuī"], 3, "to fear", "14"),
    (["misceō", "miscēre", "miscuī", "mixtum"], 2, "to mix, mingle", "13"),
    (["occīdō", "occīdere", "occīdī", "occīsum"], 3, "to kill, cut down", "14"),
    (["occurrō", "occurrere", "occurrī", "occursum"], 3, "to run to meet (+ dat.)", "14"),
    (["parcō", "parcere", "pepercī"], 3, "to spare (+ dat.)", "14"),
    (["pōscō", "pōscere", "popōscī"], 3, "to demand, ask for", "14"),
    (["prōcēdō", "prōcēdere", "prōcessī", "prōcessum"], 3, "to advance, proceed", "14"),
    (["prōdūcō", "prōdūcere", "prōdūxī", "prōductum"], 3, "to lead out, prolong", "14"),
    (["requīrō", "requīrere", "requīsīvī", "requīsītum"], 3, "to seek, ask for, need", "14"),
    (["resistō", "resistere", "restitī"], 3, "to resist (+ dat.)", "14"),
    (["scindō", "scindere", "scidī", "scissum"], 3, "to tear, split", "14"),
    (["tegō", "tegere", "tēxī", "tēctum"], 3, "to cover, protect", "14"),
    (["tendō", "tendere", "tetendī", "tentum"], 3, "to stretch, aim", "14"),
    (["tribuō", "tribuere", "tribuī", "tribūtum"], 3, "to grant, assign", "14"),
    (["vehō", "vehere", "vēxī", "vectum"], 3, "to carry, convey", "14"),
    (["vēndō", "vēndere", "vēndidī", "vēnditum"], 3, "to sell", "14"),
    (["vīsō", "vīsere", "vīsī"], 3, "to visit, go to see", "14"),
    (["cōnficiō", "cōnficere", "cōnfēcī", "cōnfectum"], "3io", "to finish, complete, exhaust", "14"),
    (["cōnspiciō", "cōnspicere", "cōnspexī", "cōnspectum"], "3io", "to catch sight of, observe", "14"),
    (["dēcipiō", "dēcipere", "dēcēpī", "dēceptum"], "3io", "to deceive", "14"),
    (["dēiciō", "dēicere", "dēiēcī", "dēiectum"], "3io", "to throw down", "14"),
    (["efficiō", "efficere", "effēcī", "effectum"], "3io", "to bring about, accomplish", "14"),
    (["effugiō", "effugere", "effūgī"], "3io", "to escape, flee from", "14"),
    (["ēiciō", "ēicere", "ēiēcī", "ēiectum"], "3io", "to throw out, expel", "14"),
    (["perficiō", "perficere", "perfēcī", "perfectum"], "3io", "to complete, achieve", "14"),
    (["rapiō", "rapere", "rapuī", "raptum"], "3io", "to seize, snatch", "14"),
    (["recipiō", "recipere", "recēpī", "receptum"], "3io", "to take back, receive", "14"),
    (["suscipiō", "suscipere", "suscēpī", "susceptum"], "3io", "to undertake, take up", "14"),
    (["pariō", "parere", "peperī", "partum"], "3io", "to give birth to, produce", "14"),
    (["ascendō", "ascendere", "ascendī", "ascēnsum"], 3, "to climb, go up", "14"),
    (["incendō", "incendere", "incendī", "incēnsum"], 3, "to set fire to, burn", "14"),
    (["ārdeō", "ārdēre", "ārsī"], 2, "to burn, be on fire", "13"),
    (["fleō", "flēre", "flēvī", "flētum"], 2, "to weep, cry", "13"),
    (["haereō", "haerēre", "haesī", "haesum"], 2, "to stick, cling", "13"),
    (["lūceō", "lūcēre", "lūxī"], 2, "to shine, be light", "13"),
    (["pateō", "patēre", "patuī"], 2, "to lie open, be open", "13"),
    (["persuādeō", "persuādēre", "persuāsī", "persuāsum"], 2, "to persuade (+ dat.)", "13"),
    (["pertineō", "pertinēre", "pertinuī"], 2, "to extend, pertain, concern", "13"),
    (["prōvideō", "prōvidēre", "prōvīdī", "prōvīsum"], 2, "to foresee, provide for", "13"),
    (["retineō", "retinēre", "retinuī", "retentum"], 2, "to hold back, retain", "13"),
    (["obtineō", "obtinēre", "obtinuī", "obtentum"], 2, "to hold, obtain", "13"),
    (["removeō", "removēre", "remōvī", "remōtum"], 2, "to remove, move back", "13"),
    (["torqueō", "torquēre", "torsī", "tortum"], 2, "to twist, torture", "13"),
    (["vetō", "vetāre", "vetuī", "vetitum"], 1, "to forbid", "13"),
    (["excitō", "excitāre", "excitāvī", "excitātum"], 1, "to rouse, wake, stir up", "13"),
    (["exclāmō", "exclāmāre", "exclāmāvī", "exclāmātum"], 1, "to shout out, exclaim", "13"),
    (["invītō", "invītāre", "invītāvī", "invītātum"], 1, "to invite", "13"),
    (["rēgnō", "rēgnāre", "rēgnāvī", "rēgnātum"], 1, "to reign, rule", "13"),
    (["recūsō", "recūsāre", "recūsāvī", "recūsātum"], 1, "to refuse", "13"),
    (["revocō", "revocāre", "revocāvī", "revocātum"], 1, "to call back, recall", "13"),
    (["verberō", "verberāre", "verberāvī", "verberātum"], 1, "to beat, flog", "13"),
    (["vigilō", "vigilāre", "vigilāvī", "vigilātum"], 1, "to stay awake, keep watch", "13"),
    (["vītō", "vītāre", "vītāvī", "vītātum"], 1, "to avoid", "13"),
    (["appellō", "appellāre", "appellāvī", "appellātum"], 1, "to call, name, address", "13"),
    (["adiuvō", "adiuvāre", "adiūvī", "adiūtum"], 1, "to help, assist", "13"),
    (["sepeliō", "sepelīre", "sepelīvī", "sepultum"], 4, "to bury", "14"),
    (["perveniō", "pervenīre", "pervēnī", "perventum"], 4, "to arrive, reach", "14"),
    (["vinciō", "vincīre", "vīnxī", "vīnctum"], 4, "to bind, tie up", "14"),
]

# ---------------------------------------------------------------------------
# ADJECTIVES: (nominative, type, base-or-None, English, lesson)
# ---------------------------------------------------------------------------
ADJECTIVES = [
    ("bonus", "us", None, "good", "15"),
    ("malus", "us", None, "bad, wicked", "15"),
    ("magnus", "us", None, "big, great", "15"),
    ("parvus", "us", None, "small", "15"),
    ("longus", "us", None, "long", "15"),
    ("altus", "us", None, "high, deep", "15"),
    ("lātus", "us", None, "wide, broad", "15"),
    ("novus", "us", None, "new", "15"),
    ("antīquus", "us", None, "ancient, old", "15"),
    ("multus", "us", None, "much, many", "15"),
    ("plēnus", "us", None, "full", "15"),
    ("clārus", "us", None, "clear, famous", "15"),
    ("cārus", "us", None, "dear, precious", "15"),
    ("dūrus", "us", None, "hard, harsh", "15"),
    ("laetus", "us", None, "happy, glad", "15"),
    ("īrātus", "us", None, "angry", "15"),
    ("validus", "us", None, "strong", "15"),
    ("beātus", "us", None, "blessed, happy", "15"),
    ("certus", "us", None, "certain, sure", "15"),
    ("dignus", "us", None, "worthy", "15"),
    ("prīmus", "us", None, "first", "15"),
    ("sōlus", "us", None, "alone, only", "15"),
    ("tōtus", "us", None, "whole, entire", "15"),
    ("meus", "us", None, "my", "15"),
    ("tuus", "us", None, "your (sg.)", "15"),
    ("noster", "er", "nostr", "our", "15"),
    ("vester", "er", "vestr", "your (pl.)", "15"),
    ("miser", "er", "miser", "wretched, unhappy", "15"),
    ("pulcher", "er", "pulchr", "beautiful, handsome", "15"),
    ("aeger", "er", "aegr", "sick, ill", "15"),
    ("sacer", "er", "sacr", "sacred", "15"),
    ("līber", "er", "līber", "free", "15"),
    ("fortis", "3-2", None, "brave, strong", "15"),
    ("omnis", "3-2", None, "all, every", "15"),
    ("gravis", "3-2", None, "heavy, serious", "15"),
    ("facilis", "3-2", None, "easy", "15"),
    ("difficilis", "3-2", None, "difficult", "15"),
    ("similis", "3-2", None, "similar, like", "15"),
    ("trīstis", "3-2", None, "sad", "15"),
    ("brevis", "3-2", None, "short, brief", "15"),
    ("nōbilis", "3-2", None, "noble, well-known", "15"),
    ("crūdēlis", "3-2", None, "cruel", "15"),
    ("dulcis", "3-2", None, "sweet", "15"),
    ("fidēlis", "3-2", None, "faithful", "15"),
    ("ūtilis", "3-2", None, "useful", "15"),
    ("ingēns", "3-1", "ingent", "huge, enormous", "15"),
    ("audāx", "3-1", "audāc", "bold, daring", "15"),
    ("fēlīx", "3-1", "fēlīc", "lucky, fortunate", "15"),
    ("sapiēns", "3-1", "sapient", "wise", "15"),
    ("potēns", "3-1", "potent", "powerful", "15"),
    ("ācer", "3-3", "ācr", "keen, fierce, sharp", "15"),
    ("celer", "3-3", "celer", "swift, quick", "15"),

    # === batch 2 =========================================================
    ("angustus", "us", None, "narrow", "15"),
    ("apertus", "us", None, "open", "15"),
    ("avārus", "us", None, "greedy", "15"),
    ("benignus", "us", None, "kind", "15"),
    ("caecus", "us", None, "blind", "15"),
    ("callidus", "us", None, "clever, cunning", "15"),
    ("candidus", "us", None, "white, bright", "15"),
    ("calidus", "us", None, "warm, hot", "15"),
    ("cupidus", "us", None, "eager, desirous", "15"),
    ("doctus", "us", None, "learned, skilled", "15"),
    ("fessus", "us", None, "tired", "15"),
    ("frīgidus", "us", None, "cold", "15"),
    ("idōneus", "us", None, "suitable", "15"),
    ("iūstus", "us", None, "just, fair", "15"),
    ("lentus", "us", None, "slow", "15"),
    ("maestus", "us", None, "sad, gloomy", "15"),
    ("necessārius", "us", None, "necessary", "15"),
    ("nūllus", "us", None, "no, none", "15"),
    ("obscūrus", "us", None, "dark, obscure", "15"),
    ("perpetuus", "us", None, "continuous, perpetual", "15"),
    ("pūblicus", "us", None, "public", "15"),
    ("reliquus", "us", None, "remaining, the rest of", "15"),
    ("rūsticus", "us", None, "rural, country", "15"),
    ("saevus", "us", None, "savage, fierce", "15"),
    ("secundus", "us", None, "second, favourable", "15"),
    ("sevērus", "us", None, "stern, severe", "15"),
    ("stultus", "us", None, "foolish, stupid", "15"),
    ("superbus", "us", None, "proud, arrogant", "15"),
    ("summus", "us", None, "highest, greatest", "15"),
    ("tacitus", "us", None, "silent", "15"),
    ("tardus", "us", None, "slow, late", "15"),
    ("ultimus", "us", None, "last, furthest", "15"),
    ("vacuus", "us", None, "empty", "15"),
    ("vērus", "us", None, "true", "15"),
    ("vīvus", "us", None, "alive, living", "15"),
    ("asper", "er", "asper", "rough, harsh", "15"),
    ("dexter", "er", "dextr", "right, right-hand", "15"),
    ("niger", "er", "nigr", "black", "15"),
    ("commūnis", "3-2", None, "common, shared", "15"),
    ("humilis", "3-2", None, "low, humble", "15"),
    ("immortālis", "3-2", None, "immortal", "15"),
    ("incolumis", "3-2", None, "safe, unharmed", "15"),
    ("levis", "3-2", None, "light, slight", "15"),
    ("mortālis", "3-2", None, "mortal", "15"),
    ("prūdēns", "3-1", "prūdent", "wise, prudent", "15"),
    ("clēmēns", "3-1", "clēment", "merciful, mild", "15"),
    ("ferōx", "3-1", "ferōc", "fierce, ferocious", "15"),

    # === batch 3 =========================================================
    ("aequus", "us", None, "level, fair, equal", "15"),
    ("alienus", "us", None, "belonging to another, foreign", "15"),
    ("amplus", "us", None, "large, spacious", "15"),
    ("cēterus", "us", None, "the other, the rest", "15"),
    ("dēnsus", "us", None, "thick, dense", "15"),
    ("dīversus", "us", None, "different, opposite", "15"),
    ("dubius", "us", None, "doubtful, uncertain", "15"),
    ("firmus", "us", None, "strong, firm", "15"),
    ("grātus", "us", None, "pleasing, grateful", "15"),
    ("honestus", "us", None, "honourable", "15"),
    ("hūmānus", "us", None, "human, humane", "15"),
    ("iniquus", "us", None, "unfair, uneven", "15"),
    ("largus", "us", None, "generous, abundant", "15"),
    ("medius", "us", None, "middle, the middle of", "15"),
    ("mīrus", "us", None, "wonderful, strange", "15"),
    ("molestus", "us", None, "troublesome, annoying", "15"),
    ("nōtus", "us", None, "known, familiar", "15"),
    ("proximus", "us", None, "nearest, next", "15"),
    ("pūrus", "us", None, "clean, pure", "15"),
    ("rārus", "us", None, "rare, scattered", "15"),
    ("rēctus", "us", None, "straight, right, correct", "15"),
    ("sānus", "us", None, "healthy, sane", "15"),
    ("siccus", "us", None, "dry", "15"),
    ("sōllicitus", "us", None, "anxious, worried", "15"),
    ("tūtus", "us", None, "safe", "15"),
    ("ūniversus", "us", None, "whole, entire", "15"),
    ("integer", "er", "integr", "whole, untouched, honest", "15"),
    ("crēber", "er", "crēbr", "frequent, crowded", "15"),
    ("tener", "er", "tener", "tender, soft, young", "15"),
    ("agrestis", "3-2", None, "rural, wild", "15"),
    ("familiāris", "3-2", None, "familiar, of the household", "15"),
    ("illūstris", "3-2", None, "distinguished, bright", "15"),
    ("inānis", "3-2", None, "empty, useless", "15"),
    ("mollis", "3-2", None, "soft, gentle", "15"),
    ("nāvālis", "3-2", None, "naval", "15"),
    ("salūbris", "3-2", None, "healthy, wholesome", "15"),
    ("singulāris", "3-2", None, "single, remarkable", "15"),
    ("suāvis", "3-2", None, "sweet, pleasant", "15"),
    ("turpis", "3-2", None, "shameful, ugly", "15"),
    ("vīlis", "3-2", None, "cheap, worthless", "15"),
    ("absēns", "3-1", "absent", "absent", "15"),
    ("dīligēns", "3-1", "dīligent", "careful, diligent", "15"),
    ("ēlegāns", "3-1", "ēlegant", "elegant, tasteful", "15"),
    ("libēns", "3-1", "libent", "willing, glad", "15"),
    ("recēns", "3-1", "recent", "recent, fresh", "15"),
    ("simplex", "3-1", "simplic", "simple, straightforward", "15"),
    ("falsus", "us", None, "false, deceptive", "15"),
    ("prīvātus", "us", None, "private, personal", "15"),
    ("mortuus", "us", None, "dead", "15"),
    ("modestus", "us", None, "modest, restrained", "15"),
    ("sinister", "er", "sinistr", "left, unlucky", "15"),
]

# ---------------------------------------------------------------------------
# Indeclinables and closed classes: (Latin, English, pos, lesson)
# ---------------------------------------------------------------------------
OTHERS = [
    # adverbs
    ("nōn", "not", "adverb", "1"), ("semper", "always", "adverb", "11"),
    ("saepe", "often", "adverb", "11"), ("numquam", "never", "adverb", "11"),
    ("nunc", "now", "adverb", "11"), ("tum", "then, at that time", "adverb", "11"),
    ("iam", "now, already", "adverb", "11"), ("hodiē", "today", "adverb", "11"),
    ("herī", "yesterday", "adverb", "11"), ("crās", "tomorrow", "adverb", "11"),
    ("diū", "for a long time", "adverb", "11"), ("statim", "immediately", "adverb", "11"),
    ("subitō", "suddenly", "adverb", "11"), ("mox", "soon", "adverb", "11"),
    ("ibi", "there", "adverb", "3"), ("hīc", "here", "adverb", "3"),
    ("ubi", "where, when", "adverb", "3"), ("undique", "from all sides", "adverb", "3"),
    ("bene", "well", "adverb", "15"), ("male", "badly", "adverb", "15"),
    ("valdē", "very, strongly", "adverb", "15"), ("tandem", "at last", "adverb", "15"),
    ("etiam", "also, even", "adverb", "15"), ("quoque", "also, too", "adverb", "15"),
    ("forte", "by chance", "adverb", "15"), ("frūstrā", "in vain", "adverb", "15"),
    ("celeriter", "quickly", "adverb", "15"), ("fortiter", "bravely", "adverb", "15"),
    ("facile", "easily", "adverb", "15"), ("cūr", "why", "adverb", "15"),
    # prepositions
    ("ad", "to, towards (+ acc.)", "preposition", "3"),
    ("in", "in, on (+ abl.); into (+ acc.)", "preposition", "3"),
    ("ex", "out of, from (+ abl.)", "preposition", "3"),
    ("ab", "from, by (+ abl.)", "preposition", "3"),
    ("cum", "with (+ abl.)", "preposition", "3"),
    ("sine", "without (+ abl.)", "preposition", "3"),
    ("per", "through (+ acc.)", "preposition", "3"),
    ("prope", "near (+ acc.)", "preposition", "3"),
    ("post", "after, behind (+ acc.)", "preposition", "3"),
    ("ante", "before, in front of (+ acc.)", "preposition", "3"),
    ("inter", "between, among (+ acc.)", "preposition", "3"),
    ("trāns", "across (+ acc.)", "preposition", "3"),
    ("sub", "under (+ abl./acc.)", "preposition", "3"),
    ("dē", "down from, about (+ abl.)", "preposition", "3"),
    ("prō", "in front of, on behalf of (+ abl.)", "preposition", "3"),
    ("contrā", "against (+ acc.)", "preposition", "7"),
    # conjunctions
    ("et", "and", "conjunction", "1"), ("sed", "but", "conjunction", "1"),
    ("aut", "or", "conjunction", "1"), ("nam", "for", "conjunction", "1"),
    ("quod", "because", "conjunction", "1"), ("quia", "because", "conjunction", "1"),
    ("sī", "if", "conjunction", "1"), ("ubi2", "when", "conjunction", "1"),
    ("dum", "while", "conjunction", "1"), ("tamen", "however, nevertheless", "conjunction", "1"),
    ("igitur", "therefore", "conjunction", "1"), ("enim", "for, indeed", "conjunction", "1"),
    ("atque", "and, and also", "conjunction", "1"), ("neque", "and not, nor", "conjunction", "1"),
    # pronouns
    ("ego", "I", "pronoun", "1"), ("tū", "you (sg.)", "pronoun", "1"),
    ("nōs", "we, us", "pronoun", "1"), ("vōs", "you (pl.)", "pronoun", "1"),
    ("is", "he, that", "pronoun", "1"), ("ea", "she, that", "pronoun", "1"),
    ("id", "it, that", "pronoun", "1"), ("hic", "this, this man", "pronoun", "1"),
    ("ille", "that, that man", "pronoun", "1"), ("quī", "who, which", "pronoun", "1"),
    ("quis", "who?", "pronoun", "1"), ("quid", "what?", "pronoun", "1"),
    ("sē", "himself, herself, themselves", "pronoun", "1"),
    ("nēmō", "no one", "pronoun", "1"), ("nihil", "nothing", "pronoun", "1"),
    ("omnia", "everything, all things", "pronoun", "1"),
    # numerals
    ("ūnus", "one", "number", "11"), ("duo", "two", "number", "11"),
    ("trēs", "three", "number", "11"), ("quattuor", "four", "number", "11"),
    ("quīnque", "five", "number", "11"), ("sex", "six", "number", "11"),
    ("septem", "seven", "number", "11"), ("octō", "eight", "number", "11"),
    ("novem", "nine", "number", "11"), ("decem", "ten", "number", "11"),
    ("centum", "a hundred", "number", "11"), ("mīlle", "a thousand", "number", "11"),

    # === batch 2 =========================================================
    ("iterum", "again", "adverb", "11"), ("deinde", "then, next", "adverb", "11"),
    ("posteā", "afterwards", "adverb", "11"), ("anteā", "before, previously", "adverb", "11"),
    ("simul", "at the same time", "adverb", "11"), ("ōlim", "once, formerly", "adverb", "11"),
    ("nūper", "recently", "adverb", "11"), ("adhūc", "still, up to now", "adverb", "11"),
    ("satis", "enough", "adverb", "15"), ("nimis", "too much", "adverb", "15"),
    ("paene", "almost", "adverb", "15"), ("vix", "scarcely, hardly", "adverb", "15"),
    ("procul", "far off", "adverb", "15"), ("quam", "how, than", "adverb", "15"),
    ("tam", "so, so much", "adverb", "15"), ("ita", "thus, so", "adverb", "15"),
    ("sīc", "thus, in this way", "adverb", "15"), ("fortasse", "perhaps", "adverb", "15"),
    ("certē", "certainly", "adverb", "15"), ("lentē", "slowly", "adverb", "15"),
    ("graviter", "seriously, heavily", "adverb", "15"), ("libenter", "gladly, willingly", "adverb", "15"),
    ("prīmum", "first, at first", "adverb", "15"), ("magnopere", "greatly", "adverb", "15"),
    ("autem", "however, moreover", "conjunction", "1"),
    ("itaque", "and so, therefore", "conjunction", "1"),
    ("ergō", "therefore", "conjunction", "1"),
    ("praetereā", "besides, moreover", "conjunction", "1"),
    ("nisi", "unless, if not", "conjunction", "1"),
    ("quamquam", "although", "conjunction", "1"),
    ("ut", "as, so that", "conjunction", "1"),
    ("nē", "lest, that not", "conjunction", "1"),
    ("apud", "at, among, at the house of (+ acc.)", "preposition", "3"),
    ("circum", "around (+ acc.)", "preposition", "3"),
    ("propter", "because of (+ acc.)", "preposition", "3"),
    ("super", "above, over (+ acc.)", "preposition", "3"),
    ("tertius", "third", "number", "11"), ("quārtus", "fourth", "number", "11"),
    ("quīntus", "fifth", "number", "11"), ("vīgintī", "twenty", "number", "11"),

    # === batch 3 =========================================================
    ("intereā", "meanwhile", "adverb", "11"), ("umquam", "ever", "adverb", "11"),
    ("aliquandō", "sometimes, at some time", "adverb", "11"),
    ("cotīdiē", "daily, every day", "adverb", "11"),
    ("prīdiē", "on the day before", "adverb", "11"),
    ("posthāc", "hereafter, from now on", "adverb", "11"),
    ("prīmō", "at first", "adverb", "11"), ("dēnique", "finally, at last", "adverb", "11"),
    ("ubīque", "everywhere", "adverb", "3"), ("illūc", "to that place, thither", "adverb", "3"),
    ("hūc", "to this place, hither", "adverb", "3"), ("inde", "from there, thence", "adverb", "3"),
    ("unde", "from where, whence", "adverb", "3"), ("quō", "to where, whither", "adverb", "3"),
    ("intrā", "within (+ acc.)", "preposition", "3"),
    ("extrā", "outside (+ acc.)", "preposition", "3"),
    ("suprā", "above (+ acc.)", "preposition", "3"),
    ("īnfrā", "below (+ acc.)", "preposition", "3"),
    ("ob", "on account of (+ acc.)", "preposition", "3"),
    ("praeter", "past, except (+ acc.)", "preposition", "3"),
    ("ūsque", "all the way, continuously", "adverb", "3"),
    ("magis", "more", "adverb", "15"), ("maximē", "most, especially", "adverb", "15"),
    ("minus", "less", "adverb", "15"), ("minimē", "least, not at all", "adverb", "15"),
    ("melius", "better", "adverb", "15"), ("peius", "worse", "adverb", "15"),
    ("saltem", "at least", "adverb", "15"), ("ferē", "almost, generally", "adverb", "15"),
    ("rūrsus", "again, back", "adverb", "15"), ("ūnā", "together", "adverb", "15"),
    ("sextus", "sixth", "number", "11"), ("septimus", "seventh", "number", "11"),
    ("octāvus", "eighth", "number", "11"), ("nōnus", "ninth", "number", "11"),
    ("decimus", "tenth", "number", "11"), ("undecim", "eleven", "number", "11"),
    ("duodecim", "twelve", "number", "11"), ("trīgintā", "thirty", "number", "11"),
    ("quīnquāgintā", "fifty", "number", "11"), ("ipse", "himself, herself, itself", "pronoun", "1"),
    ("īdem", "the same", "pronoun", "1"), ("alius", "other, another", "pronoun", "1"),
    ("alter", "the other (of two)", "pronoun", "1"),
    ("uterque", "each (of two), both", "pronoun", "1"),
    ("quisque", "each one, everyone", "pronoun", "1"),
    ("aliquis", "someone, anyone", "pronoun", "1"),
]

# Homographs differing only in part of speech (ubi adv. "where" / conj. "when")
# carry a numeric suffix in the source list purely to keep the Python keys
# unique; it is stripped here, and (la, pos) uniqueness does the real work.
DEDUPE_SUFFIX = {"ubi2": "ubi"}

# ---------------------------------------------------------------------------
# Cloze sentences: headword -> [(sentence with {target}, English), ...]
# ---------------------------------------------------------------------------
CLOZE = {
    "puella": [("{Puella} in viā ambulat.", "The girl walks in the road."),
               ("Magister {puellās} laudat.", "The teacher praises the girls.")],
    "puer": [("{Puerī} in hortō lūdunt.", "The boys play in the garden."),
             ("Pater {puerum} vocat.", "The father calls the boy.")],
    "via": [("In {viā} multī hominēs sunt.", "There are many people in the street."),
            ("{Viae} Rōmānae longae erant.", "Roman roads were long.")],
    "urbs": [("{Urbs} magna et clāra est.", "The city is great and famous."),
             ("Hostēs {urbem} oppugnāvērunt.", "The enemy attacked the city.")],
    "rēx": [("{Rēx} populum regit.", "The king rules the people."),
            ("Mīlitēs {rēgem} laudāvērunt.", "The soldiers praised the king.")],
    "mīles": [("{Mīles} fortiter pugnat.", "The soldier fights bravely."),
              ("Dux {mīlitēs} ad bellum dūxit.", "The leader led the soldiers to war.")],
    "corpus": [("{Corpus} mīlitis vulnerātum est.", "The soldier's body was wounded."),
               ("{Corpora} in lītore iacēbant.", "The bodies lay on the shore.")],
    "tempus": [("{Tempus} fugit.", "Time flies."),
               ("Illō {tempore} Rōma parva erat.", "At that time Rome was small.")],
    "diēs": [("{Diēs} longus est.", "The day is long."),
             ("Post trēs {diēs} vēnit.", "He came after three days.")],
    "nox": [("{Nox} erat obscūra.", "The night was dark."),
            ("{Nocte} mīlitēs vēnērunt.", "The soldiers came by night.")],
    "mare": [("{Mare} lātum est.", "The sea is wide."),
             ("Nāvis in {marī} nāvigat.", "The ship sails on the sea.")],
    "nāvis": [("{Nāvis} ad portum vēnit.", "The ship came to the harbour."),
              ("Multae {nāvēs} in portū erant.", "There were many ships in the harbour.")],
    "manus": [("{Manus} eius fortis est.", "His hand is strong."),
              ("In {manibus} gladiōs tenēbant.", "They held swords in their hands.")],
    "amō": [("Puella puerum {amat}.", "The girl loves the boy."),
            ("Nōs patriam {amāmus}.", "We love our country.")],
    "videō": [("Ego templum {videō}.", "I see the temple."),
              ("Herī rēgem {vīdimus}.", "Yesterday we saw the king.")],
    "sum": [("Puer in hortō {est}.", "The boy is in the garden."),
            ("Nōs Rōmānī {sumus}.", "We are Romans.")],
    "possum": [("Ego currere {possum}.", "I am able to run."),
               ("Mīlitēs urbem capere {poterant}.", "The soldiers were able to capture the city.")],
    "dūcō": [("Dux exercitum {dūcit}.", "The leader leads the army."),
             ("Caesar mīlitēs trāns flūmen {dūxit}.", "Caesar led the soldiers across the river.")],
    "dīcō": [("Quid {dīcis}?", "What are you saying?"),
             ("Poēta fābulam {dīxit}.", "The poet told a story.")],
    "faciō": [("Quid {facis}?", "What are you doing?"),
              ("Servī cēnam {fēcērunt}.", "The slaves made the dinner.")],
    "capiō": [("Hostēs oppidum {capiunt}.", "The enemy are capturing the town."),
              ("Mīlitēs multōs captīvōs {cēpērunt}.", "The soldiers captured many prisoners.")],
    "veniō": [("Amīcus meus {venit}.", "My friend is coming."),
              ("Nūntiī ad urbem {vēnērunt}.", "The messengers came to the city.")],
    "audiō": [("Vōcem {audiō}.", "I hear a voice."),
              ("{Audīvistīne} clāmōrem?", "Did you hear the shout?")],
    "scrībō": [("Poēta carmen {scrībit}.", "The poet is writing a poem."),
               ("Multās litterās {scrīpsī}.", "I wrote many letters.")],
    "eō": [("Ad forum {eō}.", "I am going to the forum."),
           ("Nōs ad templum {īmus}.", "We are going to the temple.")],
    "ferō": [("Servus aquam {fert}.", "The slave carries water."),
             ("Mīlitēs arma {tulērunt}.", "The soldiers carried arms.")],
    "volō": [("Ego venīre {volō}.", "I want to come."),
             ("Quid {vīs}?", "What do you want?")],
    "magnus": [("{Magna} urbs est.", "It is a great city."),
               ("{Magnī} mīlitēs pugnāvērunt.", "Great soldiers fought.")],
    "bonus": [("Puer {bonus} est.", "The boy is good."),
              ("{Bonae} puellae labōrant.", "The good girls work.")],
    "omnis": [("{Omnēs} cīvēs vēnērunt.", "All the citizens came."),
              ("{Omnia} bona sunt.", "All things are good.")],
    "fortis": [("Mīles {fortis} est.", "The soldier is brave."),
               ("{Fortēs} virī patriam servant.", "Brave men save their country.")],
    "ingēns": [("{Ingēns} mōnstrum vēnit.", "A huge monster came."),
               ("{Ingentēs} montēs vidēmus.", "We see huge mountains.")],
    "deus": [("{Deus} caelum regit.", "The god rules the sky."),
             ("Rōmānī {deōs} timēbant.", "The Romans feared the gods.")],
    "aqua": [("{Aqua} frīgida est.", "The water is cold."),
             ("Servī {aquam} portant.", "The slaves carry water.")],
    "liber": [("{Liber} in mēnsā est.", "The book is on the table."),
              ("Multōs {librōs} lēgī.", "I have read many books.")],

    "dux": [("{Dux} mīlitēs laudāvit.", "The leader praised the soldiers."),
            ("Mīlitēs {ducem} sequēbantur.", "The soldiers were following the leader.")],
    "bellum": [("{Bellum} longum erat.", "The war was long."),
               ("Rōmānī {bellum} gessērunt.", "The Romans waged war.")],
    "pāx": [("{Pāx} tandem vēnit.", "Peace came at last."),
            ("Cīvēs {pācem} petēbant.", "The citizens were seeking peace.")],
    "domus": [("In {domō} meā manēbam.", "I was staying in my house."),
              ("Ad {domum} rediērunt.", "They returned home.")],
    "terra": [("{Terra} fertilis est.", "The land is fertile."),
              ("Multās {terrās} vīdimus.", "We saw many lands.")],
    "hostis": [("{Hostis} appropinquat.", "The enemy is approaching."),
               ("{Hostēs} urbem oppugnāvērunt.", "The enemies attacked the city.")],
    "pater": [("{Pater} meus agricola est.", "My father is a farmer."),
              ("{Patrī} epistulam scrīpsī.", "I wrote a letter to my father.")],
    "māter": [("{Māter} fīlium amat.", "The mother loves her son."),
              ("Verba {mātris} audīvī.", "I heard my mother's words.")],
    "servus": [("{Servus} in hortō labōrat.", "The slave works in the garden."),
               ("Dominus {servōs} līberāvit.", "The master freed the slaves.")],
    "cibus": [("{Cibus} in mēnsā est.", "The food is on the table."),
              ("Servī {cibum} parāvērunt.", "The slaves prepared the food.")],
    "vīnum": [("{Vīnum} bonum bibimus.", "We drink good wine."),
              ("Poculum {vīnī} mihi dā.", "Give me a cup of wine.")],
    "equus": [("{Equus} celeriter currit.", "The horse runs quickly."),
              ("In {equō} sedēbat.", "He was sitting on a horse.")],
    "silva": [("In {silvā} ambulābāmus.", "We were walking in the wood."),
              ("{Silvae} dēnsae sunt.", "The woods are dense.")],
    "flūmen": [("{Flūmen} lātum est.", "The river is wide."),
               ("Trāns {flūmen} contendērunt.", "They hurried across the river.")],
    "mōns": [("{Mōns} altus est.", "The mountain is high."),
             ("Ad {montēs} iter fēcimus.", "We made a journey to the mountains.")],
    "sōl": [("{Sōl} lūcet.", "The sun is shining."),
            ("Post {sōlem} nox venit.", "After the sun comes night.")],
    "annus": [("Hic {annus} longus fuit.", "This year has been long."),
              ("Post multōs {annōs} rediit.", "He returned after many years.")],
    "lēx": [("{Lēx} omnēs tenet.", "The law binds everyone."),
            ("Cōnsul {lēgem} tulit.", "The consul proposed a law.")],
    "pecūnia": [("{Pecūnia} mihi nōn est.", "I have no money."),
                ("Multam {pecūniam} habet.", "He has a lot of money.")],
    "verbum": [("{Verba} eius audīvī.", "I heard his words."),
               ("Hoc {verbum} nōn intellegō.", "I do not understand this word.")],
    "labor": [("{Labor} difficilis est.", "The work is difficult."),
              ("Post {labōrem} dormīvimus.", "After the work we slept.")],
    "iter": [("Longum {iter} fēcimus.", "We made a long journey."),
             ("In {itinere} multa vīdimus.", "We saw many things on the journey.")],
    "habeō": [("Multōs amīcōs {habeō}.", "I have many friends."),
              ("Nihil {habēbāmus}.", "We had nothing.")],
    "dō": [("Librum mihi {dat}.", "He gives me a book."),
           ("Dōna puerīs {dedimus}.", "We gave gifts to the boys.")],
    "mittō": [("Nūntium ad rēgem {mittit}.", "He sends a messenger to the king."),
              ("Litterās {mīsī}.", "I sent a letter.")],
    "agō": [("Quid {agis}?", "How are you? / What are you doing?"),
            ("Grātiās tibi {agō}.", "I give you thanks.")],
    "pōnō": [("Librum in mēnsā {pōnit}.", "He places the book on the table."),
             ("Castra prope flūmen {posuērunt}.", "They pitched camp near the river.")],
    "vincō": [("Rōmānī hostēs {vīcērunt}.", "The Romans conquered the enemy."),
              ("Semper {vincimus}.", "We always win.")],
    "currō": [("Puer celeriter {currit}.", "The boy runs quickly."),
              ("Ad portum {cucurrimus}.", "We ran to the harbour.")],
    "petō": [("Auxilium {petimus}.", "We seek help."),
             ("Pācem ā rēge {petīvērunt}.", "They sought peace from the king.")],
    "vīvō": [("In urbe {vīvō}.", "I live in the city."),
             ("Diū {vīxit}.", "He lived a long time.")],
    "legō": [("Librum {legō}.", "I am reading a book."),
             ("Multōs librōs {lēgimus}.", "We have read many books.")],
    "maneō": [("Domī {maneō}.", "I stay at home."),
              ("Trēs diēs {mānsimus}.", "We stayed three days.")],
    "moneō": [("Magister discipulōs {monet}.", "The teacher warns the pupils."),
              ("Tē saepe {monuī}.", "I have often warned you.")],
    "teneō": [("Gladium {tenet}.", "He is holding a sword."),
              ("Urbem diū {tenuērunt}.", "They held the city for a long time.")],
    "timeō": [("Mortem nōn {timeō}.", "I do not fear death."),
              ("Hostēs {timēbant}.", "They were afraid of the enemy.")],
    "iubeō": [("Dux mīlitēs pugnāre {iubet}.", "The leader orders the soldiers to fight."),
              ("Servōs venīre {iussit}.", "He ordered the slaves to come.")],
    "sciō": [("Nihil {sciō}.", "I know nothing."),
             ("Omnia {scīvimus}.", "We knew everything.")],
    "cadō": [("Folia {cadunt}.", "The leaves are falling."),
             ("In terram {cecidit}.", "He fell to the ground.")],
    "surgō": [("Māne {surgō}.", "I get up in the morning."),
              ("Omnēs {surrēxērunt}.", "Everyone stood up.")],
    "aperiō": [("Iānuam {aperit}.", "He opens the door."),
               ("Portās {aperuērunt}.", "They opened the gates.")],
    "relinquō": [("Urbem {relinquimus}.", "We are leaving the city."),
                 ("Amīcōs suōs {relīquit}.", "He abandoned his friends.")],
    "intellegō": [("Verba tua {intellegō}.", "I understand your words."),
                  ("Nihil {intellēximus}.", "We understood nothing.")],
    "discēdō": [("Ex urbe {discēdunt}.", "They are departing from the city."),
                ("Statim {discessit}.", "He left immediately.")],
    "quaerō": [("Auxilium {quaerō}.", "I am looking for help."),
               ("Cūr hoc {quaesīvistī}?", "Why did you ask this?")],
    "dēbeō": [("Pecūniam mihi {dēbēs}.", "You owe me money."),
              ("Venīre {dēbēmus}.", "We ought to come.")],
    "parvus": [("{Parva} puella lacrimat.", "The little girl is crying."),
               ("In {parvō} oppidō habitāmus.", "We live in a small town.")],
    "longus": [("Via {longa} est.", "The road is long."),
               ("Post {longum} tempus rediit.", "He returned after a long time.")],
    "novus": [("{Nova} lēx scrīpta est.", "A new law was written."),
              ("{Novum} templum aedificāvērunt.", "They built a new temple.")],
    "multus": [("{Multī} hominēs aderant.", "Many people were present."),
               ("{Multa} vīdimus.", "We saw many things.")],
    "altus": [("Mūrus {altus} est.", "The wall is high."),
              ("In {altō} monte stat.", "It stands on a high mountain.")],
    "trīstis": [("Puella {trīstis} est.", "The girl is sad."),
                ("{Trīstēs} domum iērunt.", "They went home sad.")],
    "facilis": [("Hoc {facile} est.", "This is easy."),
                ("{Facilia} verba sunt.", "The words are easy.")],
    "gravis": [("Onus {grave} est.", "The burden is heavy."),
               ("{Gravēs} cūrās habēbat.", "He had serious worries.")],
}

# ---------------------------------------------------------------------------
# Antonym / synonym pairs, by headword.
# ---------------------------------------------------------------------------
ANTONYMS = [
    ("bonus", "malus"), ("magnus", "parvus"), ("longus", "brevis"),
    ("novus", "antīquus"), ("laetus", "trīstis"), ("facilis", "difficilis"),
    ("bellum", "pāx"), ("vīta", "mors"), ("diēs", "nox"), ("aestās", "hiems"),
    ("amīcus", "inimīcus"), ("dominus", "servus"), ("pater", "māter"),
    ("frāter", "soror"), ("fīlius", "fīlia"), ("puer", "puella"),
    ("vir", "fēmina"), ("rēx", "rēgīna"), ("deus", "dea"), ("terra", "caelum"),
    ("sōl", "lūna"), ("lūx", "tenebrae"), ("bene", "male"), ("semper", "numquam"),
    ("labor", "ōtium"), ("ante", "post"), ("hodiē", "crās"),
    ("laus", "culpa"), ("amor", "odium"), ("spēs", "metus"), ("libertās", "servitūs"),
    ("aperiō", "claudō"), ("emō", "vēndō"), ("adsum", "absum"), ("veniō", "abeō"),
    ("surgō", "cadō"), ("sciō", "nesciō"), ("dō", "accipiō"),
    ("stultus", "sapiēns"), ("vērus", "falsus"), ("plēnus", "vacuus"),
    ("prīmus", "ultimus"), ("summus", "humilis"), ("calidus", "frīgidus"),
    ("candidus", "niger"), ("pūblicus", "prīvātus"), ("vīvus", "mortuus"),
    ("saevus", "benignus"), ("superbus", "modestus"), ("iūstus", "iniquus"),
    ("angustus", "lātus"), ("dexter", "sinister"), ("magis", "minus"),
    ("intrā", "extrā"), ("suprā", "īnfrā"), ("hūc", "illūc"),
    ("unde", "quō"), ("prīmō", "dēnique"),
]
SYNONYMS = [
    ("urbs", "oppidum"), ("perīculum", "morbus"), ("cōnsilium", "sententia"),
    ("gladius", "hasta"), ("clāmor", "vōx"), ("quod", "quia"),
    ("etiam", "quoque"), ("animus", "mēns"), ("hostis", "inimīcus"),
    ("timeō", "terreō"),
    ("metus", "timor"), ("mōs", "cōnsuētūdō"), ("scelus", "culpa"),
    ("cōgitō", "putō"), ("necō", "interficiō"), ("cupiō", "volō"),
    ("contendō", "festīnō"), ("occīdō", "interficiō"), ("dīligō", "amō"),
    ("iter", "via"), ("labor", "negōtium"),
    ("tēlum", "sagitta"), ("lūdus", "spectāculum"), ("ōrātiō", "sententia"),
    ("ratiō", "cōnsilium"), ("magnitūdō", "multitūdō"),
]


def build():
    entries, by_head = [], {}
    n = 0

    def nid():
        nonlocal n
        n += 1
        return f"la{n:04d}"

    def add(entry, head_key):
        entries.append(entry)
        by_head.setdefault(head_key, entry)

    for nom, gen, gender, decl, istem, en, lesson in NOUNS:
        head = DEDUPE_SUFFIX.get(nom, nom)
        decl_forms = decline_noun(head, gen, gender, decl, istem=istem)
        e = {"la": head, "en": en, "pos": "noun", "id": nid(), "lesson": lesson,
             "gender": gender, "declension": decl, "gen_sg": gen, "noun_decl": decl_forms}
        add(e, nom)

    for nom, gen_pl, gender, decl, istem, en, lesson in PLURAL_ONLY_NOUNS:
        decl_forms = decline_noun(nom, gen_pl, gender, decl,
                                  istem=istem, plural_only=True)
        e = {"la": nom, "en": en, "pos": "noun", "id": nid(), "lesson": lesson,
             "gender": gender, "declension": decl, "gen_sg": gen_pl,
             "plural_only": True, "noun_decl": decl_forms}
        add(e, nom)

    for pp, conj, en, lesson in VERBS:
        head = pp[0]
        e = {"la": head, "en": en, "pos": "verb", "id": nid(), "lesson": lesson,
             "conjugation": conjugate_verb(pp, conj), "principal_parts": pp,
             "conj_class": conj}
        add(e, head)

    for nom, atype, base, en, lesson in ADJECTIVES:
        e = {"la": nom, "en": en, "pos": "adjective", "id": nid(), "lesson": lesson,
             "adj_type": atype, "declension_forms": atype,
             "declension": decline_adjective(nom, atype, base=base)}
        add(e, nom)

    for la, en, pos, lesson in OTHERS:
        head = DEDUPE_SUFFIX.get(la, la)
        e = {"la": head, "en": en, "pos": pos, "id": nid(), "lesson": lesson}
        add(e, la)

    # Cloze
    attached = 0
    for head, sents in CLOZE.items():
        e = by_head.get(head)
        assert e is not None, f"cloze references unknown headword {head!r}"
        e["cloze"] = [{"la": s, "en": t} for s, t in sents]
        attached += len(sents)

    # Antonyms / synonyms, linked both ways
    def link(pairs, field):
        for a, b in pairs:
            ea, eb = by_head.get(a), by_head.get(b)
            assert ea is not None, f"{field}: unknown headword {a!r}"
            assert eb is not None, f"{field}: unknown headword {b!r}"
            ea.setdefault(field, [])
            eb.setdefault(field, [])
            if eb["id"] not in ea[field]:
                ea[field].append(eb["id"])
            if ea["id"] not in eb[field]:
                eb[field].append(ea["id"])
    link(ANTONYMS, "antonyms")
    link(SYNONYMS, "synonyms")

    # ---- integrity checks -------------------------------------------------
    ids = [e["id"] for e in entries]
    assert len(ids) == len(set(ids)), "duplicate entry ids"
    keys = [(e["la"], e["pos"]) for e in entries]
    dupes = [k for k, c in collections.Counter(keys).items() if c > 1]
    assert not dupes, f"duplicate (la, pos) keys: {dupes}"
    byid = {e["id"]: e for e in entries}
    for e in entries:
        for field in ("antonyms", "synonyms"):
            for rid in e.get(field, []):
                assert rid in byid, f"{e['la']}: dangling {field} id {rid}"
        for c in e.get("cloze", []):
            assert c["la"].count("{") == 1 and c["la"].count("}") == 1, \
                f"{e['la']}: cloze must wrap exactly one target: {c['la']!r}"
        for group in ("noun_decl", "declension"):
            if isinstance(e.get(group), dict):
                for k, v in e[group].items():
                    assert v and v.strip(), f"{e['la']}: blank form for {group}.{k}"
        if e["pos"] == "verb":
            for tense, forms in e["conjugation"].items():
                assert len(forms) == 6, f"{e['la']}: {tense} has {len(forms)} persons"

    data = {
        "entries": entries,
        "meta": {"language": "Latin", "reference": "English",
                 "level": "school years 1-2", "version": "v1"},
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    counts = collections.Counter(e["pos"] for e in entries)
    print(f"wrote {os.path.normpath(OUT)}: {len(entries)} entries")
    print("  " + " · ".join(f"{v} {k}" for k, v in counts.most_common()))
    print(f"  cloze sentences: {attached} across {len(CLOZE)} words")
    print(f"  antonym pairs: {len(ANTONYMS)} · synonym pairs: {len(SYNONYMS)}")


if __name__ == "__main__":
    build()
