#!/usr/bin/env python3
"""Build vocab_fr.json — a French deck weighted towards SMALL TALK.

Same generated-data contract as the Latin and Italian decks: edit the lists
here, re-run, then rebuild + validate. Do not hand-edit vocab_fr.json.

What "small talk focus" means concretely, versus the other decks:
  * lessons are conversational SITUATIONS, not topic buckets;
  * a much larger share of ready-made PHRASES and fillers — the units you
    actually say — rather than isolated nouns;
  * cloze sentences are lines of dialogue;
  * the two special drills are the ones that decide whether small talk lands:
    tu/vous register, and the passé composé auxiliary you need to talk about
    what you did.

English glosses are written WITHOUT articles ("house", not "the house") because
this deck's FILLER list only strips "to" — see the note in the trainer.
"""
import json, os, sys, collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from french_morph import noun_forms, conjugate, decline_adjective, IMPERSONAL

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'vocab_fr.json')

# Lesson names, for reference:
#  1 greetings & introductions      2 politeness & social formulas
#  3 how are you / feelings         4 weather & seasons
#  5 family & personal life         6 work & studies
#  7 free time, weekend & hobbies   8 food, drink & eating out
#  9 travel & holidays             10 home & where you live
# 11 opinions, agreeing, disagreeing 12 plans & invitations
# 13 numbers, time & dates         14 core verbs
# 15 adjectives & adverbs          16 conversation fillers & connectors

# ---------------------------------------------------------------------------
# PHRASES — the heart of a small-talk deck. (French, English, lesson)
# ---------------------------------------------------------------------------
PHRASES = [
    # L1 greetings & introductions
    ("bonjour", "hello, good morning", "1"),
    ("bonsoir", "good evening", "1"),
    ("salut", "hi, bye (informal)", "1"),
    ("au revoir", "goodbye", "1"),
    ("bonne nuit", "good night", "1"),
    ("à bientôt", "see you soon", "1"),
    ("à plus tard", "see you later", "1"),
    ("à demain", "see you tomorrow", "1"),
    ("à tout à l'heure", "see you in a bit", "1"),
    ("bonne journée", "have a good day", "1"),
    ("bonne soirée", "have a good evening", "1"),
    ("bon week-end", "have a good weekend", "1"),
    ("comment allez-vous ?", "how are you? (formal)", "1"),
    ("comment vas-tu ?", "how are you? (informal)", "1"),
    ("ça va ?", "how's it going?", "1"),
    ("ça va bien, merci", "I'm fine, thanks", "1"),
    ("et toi ?", "and you? (informal)", "1"),
    ("et vous ?", "and you? (formal)", "1"),
    ("comment tu t'appelles ?", "what's your name? (informal)", "1"),
    ("comment vous appelez-vous ?", "what's your name? (formal)", "1"),
    ("je m'appelle...", "my name is...", "1"),
    ("enchanté", "pleased to meet you", "1"),
    ("ravi de vous rencontrer", "delighted to meet you", "1"),
    ("d'où venez-vous ?", "where are you from? (formal)", "1"),
    ("je viens de...", "I come from...", "1"),
    ("j'habite à...", "I live in...", "1"),
    ("voici mon ami", "this is my friend", "1"),
    ("je vous présente...", "let me introduce...", "1"),
    # L2 politeness
    ("s'il vous plaît", "please (formal)", "2"),
    ("s'il te plaît", "please (informal)", "2"),
    ("merci beaucoup", "thank you very much", "2"),
    ("de rien", "you're welcome", "2"),
    ("je vous en prie", "you're welcome (formal)", "2"),
    ("avec plaisir", "with pleasure", "2"),
    ("excusez-moi", "excuse me (formal)", "2"),
    ("pardon", "sorry, excuse me", "2"),
    ("je suis désolé", "I'm sorry", "2"),
    ("ce n'est pas grave", "it doesn't matter", "2"),
    ("pas de problème", "no problem", "2"),
    ("bien sûr", "of course", "2"),
    ("volontiers", "gladly, willingly", "2"),
    ("félicitations", "congratulations", "2"),
    ("bon appétit", "enjoy your meal", "2"),
    ("santé", "cheers", "2"),
    ("bonne chance", "good luck", "2"),
    ("bon courage", "hang in there, good luck", "2"),
    # L3 how are you / feelings
    ("ça va bien", "I'm well", "3"),
    ("ça va mal", "things are bad", "3"),
    ("comme ci comme ça", "so-so", "3"),
    ("pas mal", "not bad", "3"),
    ("très bien", "very well", "3"),
    ("je suis fatigué", "I'm tired", "3"),
    ("je suis content", "I'm happy", "3"),
    ("j'ai faim", "I'm hungry", "3"),
    ("j'ai soif", "I'm thirsty", "3"),
    ("j'ai froid", "I'm cold", "3"),
    ("j'ai chaud", "I'm hot", "3"),
    ("j'ai sommeil", "I'm sleepy", "3"),
    ("j'ai peur", "I'm afraid", "3"),
    ("ça me plaît", "I like it", "3"),
    ("quoi de neuf ?", "what's new?", "3"),
    ("ça fait longtemps", "it's been a long time", "3"),
    # L4 weather — the classic small-talk opener
    ("il fait beau", "the weather is nice", "4"),
    ("il fait mauvais", "the weather is bad", "4"),
    ("il fait chaud", "it's hot", "4"),
    ("il fait froid", "it's cold", "4"),
    ("il pleut", "it's raining", "4"),
    ("il neige", "it's snowing", "4"),
    ("il y a du vent", "it's windy", "4"),
    ("il y a du soleil", "it's sunny", "4"),
    ("quel temps fait-il ?", "what's the weather like?", "4"),
    ("quelle chaleur !", "how hot it is!", "4"),
    # L11 opinions & reactions
    ("je pense que...", "I think that...", "11"),
    ("à mon avis", "in my opinion", "11"),
    ("je suis d'accord", "I agree", "11"),
    ("je ne suis pas d'accord", "I disagree", "11"),
    ("tu as raison", "you're right", "11"),
    ("tu as tort", "you're wrong", "11"),
    ("c'est vrai", "that's true", "11"),
    ("c'est super", "that's great", "11"),
    ("c'est dommage", "that's a shame", "11"),
    ("quelle bonne idée", "what a good idea", "11"),
    ("ça dépend", "it depends", "11"),
    ("peut-être", "maybe", "11"),
    ("je ne sais pas", "I don't know", "11"),
    ("je ne comprends pas", "I don't understand", "11"),
    ("qu'est-ce que ça veut dire ?", "what does that mean?", "11"),
    ("pouvez-vous répéter ?", "can you repeat? (formal)", "11"),
    ("parlez plus lentement", "speak more slowly", "11"),
    ("comment dit-on... ?", "how do you say...?", "11"),
    ("je parle un peu français", "I speak a little French", "11"),
    # L12 plans & invitations
    ("tu veux venir ?", "do you want to come?", "12"),
    ("on y va ?", "shall we go?", "12"),
    ("qu'est-ce qu'on fait ?", "what shall we do?", "12"),
    ("ça te dit ?", "do you fancy it?", "12"),
    ("je suis libre", "I'm free", "12"),
    ("je suis occupé", "I'm busy", "12"),
    ("une autre fois", "another time", "12"),
    ("avec plaisir, oui", "yes, with pleasure", "12"),
    ("désolé, je ne peux pas", "sorry, I can't", "12"),
    ("on se voit quand ?", "when shall we meet?", "12"),
    ("rendez-vous à huit heures", "meeting at eight o'clock", "12"),
    # L8 eating out
    ("l'addition, s'il vous plaît", "the bill, please", "8"),
    ("je voudrais...", "I would like...", "8"),
    ("qu'est-ce que vous recommandez ?", "what do you recommend?", "8"),
    ("c'est délicieux", "it's delicious", "8"),
    ("une table pour deux", "a table for two", "8"),
    # L9 travel
    ("où est... ?", "where is...?", "9"),
    ("combien ça coûte ?", "how much does it cost?", "9"),
    ("je suis perdu", "I'm lost", "9"),
    ("pouvez-vous m'aider ?", "can you help me? (formal)", "9"),
    ("bon voyage", "have a good trip", "9"),
    ("bonnes vacances", "have a good holiday", "9"),

    # === batch 2: more small talk ==========================================
    ("ça marche", "that works, OK", "12"),
    ("d'accord", "OK, agreed", "11"),
    ("tant pis", "never mind, too bad", "11"),
    ("tant mieux", "so much the better", "11"),
    ("ça m'est égal", "I don't mind", "11"),
    ("je m'en fiche", "I don't care (informal)", "11"),
    ("n'importe quoi", "nonsense, whatever", "11"),
    ("tout à fait", "absolutely, exactly", "11"),
    ("pas du tout", "not at all", "11"),
    ("au contraire", "on the contrary", "11"),
    ("ça alors !", "well I never!", "11"),
    ("sans blague ?", "no kidding?", "11"),
    ("c'est pas vrai !", "you're kidding!", "11"),
    ("j'espère que oui", "I hope so", "11"),
    ("j'espère que non", "I hope not", "11"),
    ("si tu veux", "if you like", "12"),
    ("comme tu veux", "as you like", "12"),
    ("ça t'ennuie si... ?", "do you mind if...?", "12"),
    ("tu es sûr ?", "are you sure?", "12"),
    ("on verra", "we'll see", "12"),
    ("à votre santé", "to your health, cheers", "2"),
    ("bonne continuation", "keep it up, all the best", "2"),
    ("meilleurs vœux", "best wishes", "2"),
    ("joyeux anniversaire", "happy birthday", "2"),
    ("bonne année", "happy new year", "2"),
    ("toutes mes condoléances", "my condolences", "2"),
    ("prends soin de toi", "take care of yourself", "2"),
    ("passe le bonjour", "say hello from me", "2"),
    ("ça fait plaisir", "that's nice, I'm glad", "3"),
    ("je suis crevé", "I'm exhausted (informal)", "3"),
    ("j'en ai marre", "I'm fed up", "3"),
    ("ça m'énerve", "that annoys me", "3"),
    ("je me sens bien", "I feel good", "3"),
    ("je ne me sens pas bien", "I don't feel well", "3"),
    ("ça pourrait aller mieux", "could be better", "3"),
    ("il fait un temps horrible", "the weather is horrible", "4"),
    ("il fait doux", "it's mild", "4"),
    ("il fait gris", "it's overcast", "4"),
    ("le ciel est couvert", "the sky is cloudy", "4"),
    ("on annonce de la pluie", "rain is forecast", "4"),
    ("quel dommage pour le temps", "what a shame about the weather", "4"),
    ("tu fais quoi dans la vie ?", "what do you do for a living?", "6"),
    ("je travaille dans...", "I work in...", "6"),
    ("je suis étudiant", "I'm a student", "6"),
    ("ça se passe bien au travail ?", "is work going well?", "6"),
    ("j'ai beaucoup de travail", "I have a lot of work", "6"),
    ("tu as des frères et sœurs ?", "do you have brothers and sisters?", "5"),
    ("je suis marié", "I'm married", "5"),
    ("je suis célibataire", "I'm single", "5"),
    ("j'ai deux enfants", "I have two children", "5"),
    ("tu as passé un bon week-end ?", "did you have a good weekend?", "7"),
    ("qu'est-ce que tu as fait ?", "what did you do?", "7"),
    ("rien de spécial", "nothing special", "7"),
    ("je suis resté à la maison", "I stayed at home", "7"),
    ("on est sortis avec des amis", "we went out with friends", "7"),
    ("j'adore ça", "I love that", "7"),
    ("ce n'est pas mon truc", "it's not my thing", "7"),
    ("tu connais un bon restaurant ?", "do you know a good restaurant?", "8"),
    ("c'est ma tournée", "it's my round", "8"),
    ("encore un peu ?", "a little more?", "8"),
    ("c'était très bon", "that was very good", "8"),
    ("je n'ai plus faim", "I'm not hungry any more", "8"),
    ("tu pars en vacances ?", "are you going on holiday?", "9"),
    ("je reviens tout de suite", "I'll be right back", "9"),
    ("c'est loin d'ici ?", "is it far from here?", "9"),
    ("tout droit", "straight ahead", "9"),
    ("à gauche", "on the left", "9"),
    ("à droite", "on the right", "9"),
]

# ---------------------------------------------------------------------------
# NOUNS: (word, gender, English, lesson[, explicit plural])
# ---------------------------------------------------------------------------
NOUNS = [
    # L1 people
    ("homme", "m", "man", "1"), ("femme", "f", "woman", "1"),
    ("garçon", "m", "boy", "1"), ("fille", "f", "girl, daughter", "1"),
    ("enfant", "m", "child", "1"), ("personne", "f", "person", "1"),
    ("gens", "m", "people", "1", "gens"), ("monsieur", "m", "sir, Mr", "1"),
    ("madame", "f", "madam, Mrs", "1"), ("ami", "m", "friend", "1"),
    ("amie", "f", "friend (female)", "1"), ("copain", "m", "mate, boyfriend", "1"),
    ("voisin", "m", "neighbour", "1"), ("collègue", "m", "colleague", "1"),
    ("nom", "m", "name, surname", "1"), ("prénom", "m", "first name", "1"),
    ("âge", "m", "age", "1"), ("pays", "m", "country", "1"),
    ("ville", "f", "town, city", "1"), ("langue", "f", "language, tongue", "1"),
    # L5 family & personal life
    ("famille", "f", "family", "5"), ("père", "m", "father", "5"),
    ("mère", "f", "mother", "5"), ("parents", "m", "parents", "5", "parents"),
    ("fils", "m", "son", "5"), ("frère", "m", "brother", "5"),
    ("sœur", "f", "sister", "5"), ("mari", "m", "husband", "5"),
    ("épouse", "f", "wife", "5"), ("grand-père", "m", "grandfather", "5"),
    ("grand-mère", "f", "grandmother", "5"), ("oncle", "m", "uncle", "5"),
    ("tante", "f", "aunt", "5"), ("cousin", "m", "cousin", "5"),
    ("bébé", "m", "baby", "5"), ("vie", "f", "life", "5"),
    ("anniversaire", "m", "birthday, anniversary", "5"),
    ("mariage", "m", "wedding, marriage", "5"),
    ("chien", "m", "dog", "5"), ("chat", "m", "cat", "5"),
    # L3 feelings & body
    ("joie", "f", "joy", "3"), ("peur", "f", "fear", "3"),
    ("amour", "m", "love", "3"), ("colère", "f", "anger", "3"),
    ("humeur", "f", "mood", "3"), ("sourire", "m", "smile", "3"),
    ("santé", "f", "health", "3"), ("tête", "f", "head", "3"),
    ("main", "f", "hand", "3"), ("cœur", "m", "heart", "3"),
    ("œil", "m", "eye", "3", "yeux"), ("voix", "f", "voice", "3"),
    # L4 weather & seasons
    ("temps", "m", "weather, time", "4"), ("soleil", "m", "sun", "4"),
    ("pluie", "f", "rain", "4"), ("neige", "f", "snow", "4"),
    ("vent", "m", "wind", "4"), ("nuage", "m", "cloud", "4"),
    ("ciel", "m", "sky", "4", "cieux"), ("orage", "m", "storm", "4"),
    ("chaleur", "f", "heat", "4"), ("froid", "m", "cold", "4"),
    ("saison", "f", "season", "4"), ("printemps", "m", "spring", "4"),
    ("été", "m", "summer", "4"), ("automne", "m", "autumn", "4"),
    ("hiver", "m", "winter", "4"), ("température", "f", "temperature", "4"),
    # L6 work & studies
    ("travail", "m", "work, job", "6"), ("métier", "m", "job, trade", "6"),
    ("bureau", "m", "office, desk", "6"), ("entreprise", "f", "company", "6"),
    ("patron", "m", "boss", "6"), ("employé", "m", "employee", "6"),
    ("réunion", "f", "meeting", "6"), ("projet", "m", "project", "6"),
    ("salaire", "m", "salary", "6"), ("école", "f", "school", "6"),
    ("université", "f", "university", "6"), ("étudiant", "m", "student", "6"),
    ("professeur", "m", "teacher", "6"), ("cours", "m", "class, course", "6"),
    ("examen", "m", "exam", "6"), ("livre", "m", "book", "6"),
    ("question", "f", "question", "6"), ("réponse", "f", "answer", "6"),
    ("idée", "f", "idea", "6"), ("mot", "m", "word", "6"),
    # L7 free time & hobbies
    ("week-end", "m", "weekend", "7"), ("loisir", "m", "leisure, hobby", "7"),
    ("musique", "f", "music", "7"), ("film", "m", "film", "7"),
    ("sport", "m", "sport", "7"), ("match", "m", "match, game", "7"),
    ("fête", "f", "party, festival", "7"), ("concert", "m", "concert", "7"),
    ("restaurant", "m", "restaurant", "7"), ("café", "m", "coffee, café", "7"),
    ("promenade", "f", "walk, stroll", "7"), ("jeu", "m", "game", "7"),
    ("photo", "f", "photo", "7"), ("nouvelle", "f", "piece of news", "7"),
    ("histoire", "f", "story, history", "7"), ("journal", "m", "newspaper", "7"),
    # L8 food & drink
    ("repas", "m", "meal", "8"), ("petit-déjeuner", "m", "breakfast", "8"),
    ("déjeuner", "m", "lunch", "8"), ("dîner", "m", "dinner", "8"),
    ("pain", "m", "bread", "8"), ("fromage", "m", "cheese", "8"),
    ("viande", "f", "meat", "8"), ("poisson", "m", "fish", "8"),
    ("légume", "m", "vegetable", "8"), ("fruit", "m", "fruit", "8"),
    ("eau", "f", "water", "8", "eaux"), ("vin", "m", "wine", "8"),
    ("bière", "f", "beer", "8"), ("thé", "m", "tea", "8"),
    ("gâteau", "m", "cake", "8"), ("plat", "m", "dish, course", "8"),
    ("carte", "f", "menu, card, map", "8"), ("addition", "f", "bill", "8"),
    ("serveur", "m", "waiter", "8"), ("goût", "m", "taste", "8"),
    # L9 travel
    ("voyage", "m", "journey, trip", "9"), ("vacances", "f", "holidays", "9", "vacances"),
    ("train", "m", "train", "9"), ("voiture", "f", "car", "9"),
    ("avion", "m", "aeroplane", "9"), ("gare", "f", "station", "9"),
    ("aéroport", "m", "airport", "9"), ("billet", "m", "ticket", "9"),
    ("valise", "f", "suitcase", "9"), ("hôtel", "m", "hotel", "9"),
    ("plage", "f", "beach", "9"), ("mer", "f", "sea", "9"),
    ("montagne", "f", "mountain", "9"), ("route", "f", "road", "9"),
    ("rue", "f", "street", "9"), ("place", "f", "square, seat, room", "9"),
    ("magasin", "m", "shop", "9"), ("marché", "m", "market", "9"),
    ("argent", "m", "money, silver", "9"), ("prix", "m", "price", "9"),
    # L10 home
    ("maison", "f", "house", "10"), ("appartement", "m", "flat", "10"),
    ("chambre", "f", "bedroom", "10"), ("cuisine", "f", "kitchen, cooking", "10"),
    ("salle de bains", "f", "bathroom", "10"), ("salon", "m", "living room", "10"),
    ("jardin", "m", "garden", "10"), ("porte", "f", "door", "10"),
    ("fenêtre", "f", "window", "10"), ("table", "f", "table", "10"),
    ("chaise", "f", "chair", "10"), ("lit", "m", "bed", "10"),
    ("clé", "f", "key", "10"), ("quartier", "m", "neighbourhood", "10"),
    ("immeuble", "m", "building", "10"), ("étage", "m", "floor, storey", "10"),
    # L13 time & numbers
    ("heure", "f", "hour, time", "13"), ("minute", "f", "minute", "13"),
    ("jour", "m", "day", "13"), ("journée", "f", "day (duration)", "13"),
    ("semaine", "f", "week", "13"), ("mois", "m", "month", "13"),
    ("an", "m", "year", "13"), ("année", "f", "year (duration)", "13"),
    ("matin", "m", "morning", "13"), ("après-midi", "m", "afternoon", "13"),
    ("soir", "m", "evening", "13"), ("nuit", "f", "night", "13"),
    ("moment", "m", "moment", "13"), ("fois", "f", "time, occasion", "13"),
    ("date", "f", "date", "13"), ("lundi", "m", "Monday", "13"),
    ("mardi", "m", "Tuesday", "13"), ("mercredi", "m", "Wednesday", "13"),
    ("jeudi", "m", "Thursday", "13"), ("vendredi", "m", "Friday", "13"),
    ("samedi", "m", "Saturday", "13"), ("dimanche", "m", "Sunday", "13"),
    # misc abstract
    ("chose", "f", "thing", "11"), ("problème", "m", "problem", "11"),
    ("raison", "f", "reason", "11"), ("avis", "m", "opinion", "11"),
    ("exemple", "m", "example", "11"), ("différence", "f", "difference", "11"),
    ("monde", "m", "world, people", "11"), ("côté", "m", "side", "11"),
    ("fin", "f", "end", "11"), ("début", "m", "beginning", "11"),
    ("bruit", "m", "noise", "11"), ("silence", "m", "silence", "11"),
    ("cadeau", "m", "present, gift", "12"), ("invitation", "f", "invitation", "12"),
    ("rendez-vous", "m", "appointment, date", "12", "rendez-vous"),
    ("téléphone", "m", "telephone", "12"), ("message", "m", "message", "12"),
    ("adresse", "f", "address", "12"), ("numéro", "m", "number", "12"),

    # === batch 2 ===========================================================
    ("copine", "f", "friend (female), girlfriend", "1"),
    ("gars", "m", "guy, lad", "1", "gars"),
    ("type", "m", "guy, type", "1"),
    ("dame", "f", "lady", "1"),
    ("groupe", "m", "group", "1"),
    ("équipe", "f", "team", "1"),
    ("nationalité", "f", "nationality", "1"),
    ("accent", "m", "accent", "1"),
    ("neveu", "m", "nephew", "5"),
    ("nièce", "f", "niece", "5"),
    ("beau-père", "m", "father-in-law, stepfather", "5"),
    ("belle-mère", "f", "mother-in-law, stepmother", "5"),
    ("petit-fils", "m", "grandson", "5"),
    ("naissance", "f", "birth", "5"),
    ("souvenir", "m", "memory, souvenir", "5"),
    ("sentiment", "m", "feeling", "3"),
    ("caractère", "m", "character", "3"),
    ("bonheur", "m", "happiness", "3"),
    ("tristesse", "f", "sadness", "3"),
    ("surprise", "f", "surprise", "3"),
    ("chance", "f", "luck", "3"),
    ("espoir", "m", "hope", "3"),
    ("fatigue", "f", "tiredness", "3"),
    ("visage", "m", "face", "3"),
    ("bras", "m", "arm", "3"),
    ("jambe", "f", "leg", "3"),
    ("dos", "m", "back", "3"),
    ("bouche", "f", "mouth", "3"),
    ("oreille", "f", "ear", "3"),
    ("nez", "m", "nose", "3"),
    ("cheveu", "m", "hair (a single one)", "3"),
    ("degré", "m", "degree", "4"),
    ("nuit blanche", "f", "sleepless night", "4"),
    ("brouillard", "m", "fog", "4"),
    ("glace", "f", "ice, ice cream, mirror", "4"),
    ("parapluie", "m", "umbrella", "4"),
    ("manteau", "m", "coat", "4"),
    ("réponse rapide", "f", "quick answer", "6"),
    ("carrière", "f", "career", "6"),
    ("stage", "m", "internship", "6"),
    ("contrat", "m", "contract", "6"),
    ("chef", "m", "boss, chef", "6"),
    ("client", "m", "client, customer", "6"),
    ("service", "m", "service, department", "6"),
    ("ordinateur", "m", "computer", "6"),
    ("dossier", "m", "file, folder", "6"),
    ("note", "f", "mark, note", "6"),
    ("devoir", "m", "homework, duty", "6"),
    ("règle", "f", "rule, ruler", "6"),
    ("erreur", "f", "mistake", "6"),
    ("sujet", "m", "subject, topic", "6"),
    ("conversation", "f", "conversation", "11"),
    ("discussion", "f", "discussion", "11"),
    ("opinion", "f", "opinion", "11"),
    ("sens", "m", "meaning, sense, direction", "11"),
    ("vérité", "f", "truth", "11"),
    ("mensonge", "m", "lie", "11"),
    ("choix", "m", "choice", "11"),
    ("solution", "f", "solution", "11"),
    ("changement", "m", "change", "11"),
    ("situation", "f", "situation", "11"),
    ("résultat", "m", "result", "11"),
    ("détail", "m", "detail", "11"),
    ("genre", "m", "kind, sort", "11"),
    ("point", "m", "point", "11"),
    ("chanson", "f", "song", "7"),
    ("livre de poche", "m", "paperback", "7"),
    ("lecture", "f", "reading", "7"),
    ("spectacle", "m", "show", "7"),
    ("sortie", "f", "outing, exit", "7"),
    ("soirée", "f", "evening, party", "7"),
    ("vélo", "m", "bicycle", "7"),
    ("marche", "f", "walking, step", "7"),
    ("natation", "f", "swimming", "7"),
    ("équipe de foot", "f", "football team", "7"),
    ("instrument", "m", "instrument", "7"),
    ("dessert", "m", "dessert", "8"),
    ("entrée", "f", "starter, entrance", "8"),
    ("boisson", "f", "drink", "8"),
    ("verre", "m", "glass", "8"),
    ("bouteille", "f", "bottle", "8"),
    ("assiette", "f", "plate", "8"),
    ("couteau", "m", "knife", "8"),
    ("cuillère", "f", "spoon", "8"),
    ("sel", "m", "salt", "8"),
    ("sucre", "m", "sugar", "8"),
    ("œuf", "m", "egg", "8"),
    ("riz", "m", "rice", "8"),
    ("salade", "f", "salad", "8"),
    ("pomme", "f", "apple", "8"),
    ("boulangerie", "f", "bakery", "8"),
    ("terrasse", "f", "terrace", "8"),
    ("pourboire", "m", "tip", "8"),
    ("séjour", "m", "stay", "9"),
    ("départ", "m", "departure", "9"),
    ("arrivée", "f", "arrival", "9"),
    ("retard", "m", "delay", "9"),
    ("bagage", "m", "luggage", "9"),
    ("passeport", "m", "passport", "9"),
    ("chambre d'hôtel", "f", "hotel room", "9"),
    ("carte postale", "f", "postcard", "9"),
    ("monnaie", "f", "change, currency", "9"),
    ("caisse", "f", "checkout, till", "9"),
    ("pont", "m", "bridge", "9"),
    ("église", "f", "church", "9"),
    ("musée", "m", "museum", "9"),
    ("parc", "m", "park", "9"),
    ("centre-ville", "m", "town centre", "9"),
    ("campagne", "f", "countryside, campaign", "9"),
    ("lac", "m", "lake", "9"),
    ("forêt", "f", "forest", "9"),
    ("loyer", "m", "rent", "10"),
    ("voisinage", "m", "neighbourhood", "10"),
    ("escalier", "m", "staircase", "10"),
    ("ascenseur", "m", "lift", "10"),
    ("mur", "m", "wall", "10"),
    ("toit", "m", "roof", "10"),
    ("sol", "m", "floor, ground", "10"),
    ("meuble", "m", "piece of furniture", "10"),
    ("armoire", "f", "wardrobe", "10"),
    ("canapé", "m", "sofa", "10"),
    ("frigo", "m", "fridge", "10"),
    ("douche", "f", "shower", "10"),
    ("lumière", "f", "light", "10"),
    ("siècle", "m", "century", "13"),
    ("midi", "m", "midday", "13"),
    ("minuit", "m", "midnight", "13"),
    ("quart", "m", "quarter", "13"),
    ("demie", "f", "half", "13"),
    ("montre", "f", "watch", "13"),
    ("calendrier", "m", "calendar", "13"),
    ("janvier", "m", "January", "13"),
    ("février", "m", "February", "13"),
    ("mars", "m", "March", "13"),
    ("avril", "m", "April", "13"),
    ("mai", "m", "May", "13"),
    ("juin", "m", "June", "13"),
    ("juillet", "m", "July", "13"),
    ("août", "m", "August", "13"),
    ("septembre", "m", "September", "13"),
    ("octobre", "m", "October", "13"),
    ("novembre", "m", "November", "13"),
    ("décembre", "m", "December", "13"),
]

# ---------------------------------------------------------------------------
# VERBS: (infinitive, English, lesson[, group][, stem_changes])
# ---------------------------------------------------------------------------
VERBS = [
    ("être", "to be", "14"), ("avoir", "to have", "14"),
    ("aller", "to go", "14"), ("faire", "to do, make", "14"),
    ("dire", "to say, tell", "14"), ("pouvoir", "to be able, can", "14"),
    ("vouloir", "to want", "14"), ("devoir", "to have to, must", "14"),
    ("savoir", "to know (a fact)", "14"), ("connaître", "to know (a person)", "14"),
    ("voir", "to see", "14"), ("venir", "to come", "14"),
    ("prendre", "to take", "14"), ("mettre", "to put", "14"),
    ("parler", "to speak, talk", "14"), ("demander", "to ask", "14"),
    ("répondre", "to answer", "14", "re"), ("écouter", "to listen", "14"),
    ("regarder", "to look at, watch", "14"), ("aimer", "to like, love", "14"),
    ("adorer", "to adore, love", "14"), ("détester", "to hate", "14"),
    ("préférer", "to prefer", "14", None, {"je": "préfère", "tu": "préfères",
                                           "il_elle": "préfère", "ils_elles": "préfèrent"}),
    ("penser", "to think", "14"), ("croire", "to believe", "14"),
    ("trouver", "to find, think", "14"), ("chercher", "to look for", "14"),
    ("donner", "to give", "14"), ("montrer", "to show", "14"),
    ("apporter", "to bring", "14"), ("porter", "to carry, wear", "14"),
    ("travailler", "to work", "14"), ("étudier", "to study", "14"),
    ("apprendre", "to learn", "14"), ("comprendre", "to understand", "14"),
    ("expliquer", "to explain", "14"), ("commencer", "to begin", "14"),
    ("finir", "to finish", "14"), ("continuer", "to continue", "14"),
    ("arrêter", "to stop", "14"), ("attendre", "to wait for", "14", "re"),
    ("rester", "to stay", "14"), ("arriver", "to arrive, happen", "15"),
    ("partir", "to leave", "15", "ir2"), ("sortir", "to go out", "15", "ir2"),
    ("entrer", "to enter", "15"), ("rentrer", "to go home, return", "15"),
    ("monter", "to go up, get in", "15"), ("descendre", "to go down", "15", "re"),
    ("tomber", "to fall", "15"), ("passer", "to pass, spend (time)", "15"),
    ("marcher", "to walk, work (function)", "15"), ("courir", "to run", "15"),
    ("voyager", "to travel", "15"), ("visiter", "to visit (a place)", "15"),
    ("habiter", "to live, reside", "15"), ("acheter", "to buy", "15", None,
        {"je": "achète", "tu": "achètes", "il_elle": "achète", "ils_elles": "achètent"}),
    ("payer", "to pay", "15"), ("vendre", "to sell", "15", "re"),
    ("coûter", "to cost", "15"), ("manger", "to eat", "15"),
    ("boire", "to drink", "15"), ("cuisiner", "to cook", "15"),
    ("goûter", "to taste", "15"), ("dormir", "to sleep", "15", "ir2"),
    ("se lever", "to get up", "15", None, {"je": "me lève", "tu": "te lèves",
        "il_elle": "se lève", "nous": "nous levons", "vous": "vous levez",
        "ils_elles": "se lèvent"}),
    ("jouer", "to play", "15"), ("chanter", "to sing", "15"),
    ("danser", "to dance", "15"), ("rire", "to laugh", "15"),
    ("pleurer", "to cry", "15"), ("sourire", "to smile", "15"),
    ("écrire", "to write", "15"), ("lire", "to read", "15"),
    ("appeler", "to call", "15", None, {"je": "appelle", "tu": "appelles",
        "il_elle": "appelle", "ils_elles": "appellent"}),
    ("téléphoner", "to phone", "15"), ("inviter", "to invite", "15"),
    ("rencontrer", "to meet", "15"), ("aider", "to help", "15"),
    ("remercier", "to thank", "15"), ("oublier", "to forget", "15"),
    ("se souvenir", "to remember", "15", None, {"je": "me souviens",
        "tu": "te souviens", "il_elle": "se souvient", "nous": "nous souvenons",
        "vous": "vous souvenez", "ils_elles": "se souviennent"}),
    ("changer", "to change", "15"), ("choisir", "to choose", "15"),
    ("essayer", "to try", "15"), ("réussir", "to succeed", "15"),
    ("ouvrir", "to open", "15"), ("fermer", "to close", "15"),
    ("offrir", "to offer, give", "15"), ("recevoir", "to receive", "15"),
    ("perdre", "to lose", "15", "re"), ("gagner", "to win, earn", "15"),
    ("naître", "to be born", "15", None, {"je": "nais", "tu": "nais",
        "il_elle": "naît", "nous": "naissons", "vous": "naissez", "ils_elles": "naissent"}),
    ("mourir", "to die", "15"), ("vivre", "to live", "15"),
    ("devenir", "to become", "15", None, {"je": "deviens", "tu": "deviens",
        "il_elle": "devient", "nous": "devenons", "vous": "devenez",
        "ils_elles": "deviennent"}),
    ("retourner", "to return, go back", "15"),
    ("plaire", "to please", "15"), ("falloir", "to be necessary", "15"),
    ("pleuvoir", "to rain", "15"),

    # === batch 2 ===========================================================
    ("discuter", "to discuss, chat", "14"),
    ("bavarder", "to chat", "14"),
    ("raconter", "to tell, recount", "14"),
    ("proposer", "to suggest, offer", "14"),
    ("accepter", "to accept", "14"),
    ("refuser", "to refuse", "14"),
    ("décider", "to decide", "14"),
    ("préparer", "to prepare", "14"),
    ("organiser", "to organise", "14"),
    ("réserver", "to book, reserve", "14"),
    ("annuler", "to cancel", "14"),
    ("s'excuser", "to apologise", "14", None, {"je": "m'excuse", "tu": "t'excuses",
        "il_elle": "s'excuse", "nous": "nous excusons", "vous": "vous excusez",
        "ils_elles": "s'excusent"}),
    ("saluer", "to greet", "14"),
    ("présenter", "to introduce, present", "14"),
    ("répéter", "to repeat", "14", None, {"je": "répète", "tu": "répètes",
        "il_elle": "répète", "ils_elles": "répètent"}),
    ("prononcer", "to pronounce", "14"),
    ("traduire", "to translate", "14", None, {"je": "traduis", "tu": "traduis",
        "il_elle": "traduit", "nous": "traduisons", "vous": "traduisez",
        "ils_elles": "traduisent"}),
    ("signifier", "to mean", "14"),
    ("s'appeler", "to be called", "14", None, {"je": "m'appelle", "tu": "t'appelles",
        "il_elle": "s'appelle", "nous": "nous appelons", "vous": "vous appelez",
        "ils_elles": "s'appellent"}),
    ("espérer", "to hope", "14", None, {"je": "espère", "tu": "espères",
        "il_elle": "espère", "ils_elles": "espèrent"}),
    ("souhaiter", "to wish", "14"),
    ("remarquer", "to notice", "14"),
    ("sembler", "to seem", "14"),
    ("paraître", "to appear, seem", "14", None, {"je": "parais", "tu": "parais",
        "il_elle": "paraît", "nous": "paraissons", "vous": "paraissez",
        "ils_elles": "paraissent"}),
    ("s'intéresser", "to be interested", "14", None, {"je": "m'intéresse",
        "tu": "t'intéresses", "il_elle": "s'intéresse", "nous": "nous intéressons",
        "vous": "vous intéressez", "ils_elles": "s'intéressent"}),
    ("s'amuser", "to have fun", "14", None, {"je": "m'amuse", "tu": "t'amuses",
        "il_elle": "s'amuse", "nous": "nous amusons", "vous": "vous amusez",
        "ils_elles": "s'amusent"}),
    ("s'ennuyer", "to be bored", "14", None, {"je": "m'ennuie", "tu": "t'ennuies",
        "il_elle": "s'ennuie", "nous": "nous ennuyons", "vous": "vous ennuyez",
        "ils_elles": "s'ennuient"}),
    ("se reposer", "to rest", "14", None, {"je": "me repose", "tu": "te reposes",
        "il_elle": "se repose", "nous": "nous reposons", "vous": "vous reposez",
        "ils_elles": "se reposent"}),
    ("se dépêcher", "to hurry", "14", None, {"je": "me dépêche", "tu": "te dépêches",
        "il_elle": "se dépêche", "nous": "nous dépêchons", "vous": "vous dépêchez",
        "ils_elles": "se dépêchent"}),
    ("se promener", "to go for a walk", "14", None, {"je": "me promène",
        "tu": "te promènes", "il_elle": "se promène", "nous": "nous promenons",
        "vous": "vous promenez", "ils_elles": "se promènent"}),
    ("rendre", "to give back, make", "14", "re"),
    ("entendre", "to hear", "14", "re"),
    ("apercevoir", "to catch sight of", "14", None, {"je": "aperçois",
        "tu": "aperçois", "il_elle": "aperçoit", "nous": "apercevons",
        "vous": "apercevez", "ils_elles": "aperçoivent"}),
    ("suivre", "to follow", "14"),
    ("conduire", "to drive", "14", None, {"je": "conduis", "tu": "conduis",
        "il_elle": "conduit", "nous": "conduisons", "vous": "conduisez",
        "ils_elles": "conduisent"}),
    ("emmener", "to take (a person)", "15", None, {"je": "emmène", "tu": "emmènes",
        "il_elle": "emmène", "ils_elles": "emmènent"}),
    ("laisser", "to leave, let", "15"),
    ("garder", "to keep, look after", "15"),
    ("ranger", "to tidy", "15"),
    ("nettoyer", "to clean", "15"),
    ("réparer", "to repair", "15"),
    ("construire", "to build", "15", None, {"je": "construis", "tu": "construis",
        "il_elle": "construit", "nous": "construisons", "vous": "construisez",
        "ils_elles": "construisent"}),
    ("utiliser", "to use", "15"),
    ("compter", "to count", "15"),
    ("mesurer", "to measure", "15"),
    ("peser", "to weigh", "15", None, {"je": "pèse", "tu": "pèses",
        "il_elle": "pèse", "ils_elles": "pèsent"}),
    ("augmenter", "to increase", "15"),
    ("baisser", "to lower, go down", "15"),
    ("améliorer", "to improve", "15"),
    ("réfléchir", "to think, reflect", "15"),
    ("imaginer", "to imagine", "15"),
    ("douter", "to doubt", "15"),
    ("promettre", "to promise", "15", None, {"je": "promets", "tu": "promets",
        "il_elle": "promet", "nous": "promettons", "vous": "promettez",
        "ils_elles": "promettent"}),
    ("permettre", "to allow", "15", None, {"je": "permets", "tu": "permets",
        "il_elle": "permet", "nous": "permettons", "vous": "permettez",
        "ils_elles": "permettent"}),
    ("interdire", "to forbid", "15", None, {"je": "interdis", "tu": "interdis",
        "il_elle": "interdit", "nous": "interdisons", "vous": "interdisez",
        "ils_elles": "interdisent"}),
    ("empêcher", "to prevent", "15"),
    ("obliger", "to force, oblige", "15"),
    ("éviter", "to avoid", "15"),
    ("oser", "to dare", "15"),
    ("mériter", "to deserve", "15"),
    ("profiter", "to make the most of", "15"),
    ("participer", "to take part", "15"),
    ("féliciter", "to congratulate", "15"),
    ("embrasser", "to kiss, hug", "15"),
    ("plaisanter", "to joke", "15"),
    ("crier", "to shout", "15"),
    ("chuchoter", "to whisper", "15"),
    ("se taire", "to be quiet", "15", None, {"je": "me tais", "tu": "te tais",
        "il_elle": "se tait", "nous": "nous taisons", "vous": "vous taisez",
        "ils_elles": "se taisent"}),
]

# ---------------------------------------------------------------------------
# ADJECTIVES: (masc sg, English, lesson[, explicit feminine][, invariable])
# ---------------------------------------------------------------------------
ADJECTIVES = [
    ("bon", "good", "15"), ("mauvais", "bad", "15"),
    ("grand", "big, tall", "15"), ("petit", "small", "15"),
    ("nouveau", "new", "15"), ("vieux", "old", "15"),
    ("jeune", "young", "15"), ("beau", "beautiful, handsome", "15"),
    ("joli", "pretty", "15"), ("laid", "ugly", "15"),
    ("long", "long", "15"), ("court", "short", "15"),
    ("haut", "high", "15"), ("bas", "low", "15"),
    ("gros", "big, fat", "15"), ("mince", "thin, slim", "15"),
    ("chaud", "hot, warm", "15"), ("froid", "cold", "15"),
    ("facile", "easy", "15"), ("difficile", "difficult", "15"),
    ("fort", "strong, loud", "15"), ("faible", "weak", "15"),
    ("rapide", "fast", "15"), ("lent", "slow", "15"),
    ("riche", "rich", "15"), ("pauvre", "poor", "15"),
    ("heureux", "happy", "15"), ("triste", "sad", "15"),
    ("content", "pleased, glad", "15"), ("fâché", "angry", "15"),
    ("fatigué", "tired", "15"), ("malade", "ill", "15"),
    ("libre", "free", "15"), ("occupé", "busy", "15"),
    ("ouvert", "open", "15"), ("fermé", "closed", "15"),
    ("cher", "dear, expensive", "15"), ("gratuit", "free (of charge)", "15"),
    ("important", "important", "15"), ("intéressant", "interesting", "15"),
    ("ennuyeux", "boring", "15"), ("drôle", "funny", "15"),
    ("gentil", "kind, nice", "15"), ("sympa", "nice, friendly", "15", None, True),
    ("poli", "polite", "15"), ("timide", "shy", "15"),
    ("sérieux", "serious", "15"), ("célèbre", "famous", "15"),
    ("premier", "first", "15"), ("dernier", "last", "15"),
    ("prochain", "next", "15"), ("même", "same", "15"),
    ("autre", "other", "15"), ("tout", "all, whole", "15", "toute"),
    ("seul", "alone, only", "15"), ("plein", "full", "15"),
    ("vide", "empty", "15"), ("propre", "clean, own", "15"),
    ("sale", "dirty", "15"), ("vrai", "true, real", "15"),
    ("faux", "false", "15"), ("possible", "possible", "15"),
    ("sûr", "sure, safe", "15"), ("prêt", "ready", "15"),
    ("blanc", "white", "15"), ("noir", "black", "15"),
    ("rouge", "red", "15"), ("vert", "green", "15"),
    ("bleu", "blue", "15"), ("jaune", "yellow", "15"),
    ("gris", "grey", "15"), ("marron", "brown", "15", None, True),
    ("français", "French", "15"), ("anglais", "English", "15"),
    ("allemand", "German", "15"), ("espagnol", "Spanish", "15"),
    ("italien", "Italian", "15"), ("étranger", "foreign", "15"),
    ("national", "national", "15"), ("délicieux", "delicious", "15"),
    ("frais", "fresh, cool", "15"), ("sec", "dry", "15"),
    ("doux", "soft, sweet, mild", "15"), ("dur", "hard", "15"),
    ("léger", "light (weight)", "15"), ("lourd", "heavy", "15"),
    ("nécessaire", "necessary", "15"), ("normal", "normal", "15"),

    # === batch 2 ===========================================================
    ("agréable", "pleasant", "15"),
    ("désagréable", "unpleasant", "15"),
    ("aimable", "kind, friendly", "15"),
    ("bavard", "talkative", "15"),
    ("calme", "calm, quiet", "15"),
    ("bruyant", "noisy", "15"),
    ("curieux", "curious", "15"),
    ("généreux", "generous", "15"),
    ("égoïste", "selfish", "15"),
    ("honnête", "honest", "15"),
    ("patient", "patient", "15"),
    ("paresseux", "lazy", "15"),
    ("travailleur", "hard-working", "15"),
    ("intelligent", "intelligent", "15"),
    ("bête", "stupid, silly", "15"),
    ("fou", "mad, crazy", "15"),
    ("sage", "wise, well-behaved", "15"),
    ("étrange", "strange", "15"),
    ("surprenant", "surprising", "15"),
    ("inquiet", "worried", "15"),
    ("nerveux", "nervous", "15"),
    ("détendu", "relaxed", "15"),
    ("amoureux", "in love", "15"),
    ("marié", "married", "15"),
    ("célibataire", "single", "15"),
    ("proche", "close, nearby", "15"),
    ("lointain", "distant", "15"),
    ("récent", "recent", "15"),
    ("ancien", "former, ancient", "15"),
    ("moderne", "modern", "15"),
    ("actuel", "current", "15"),
    ("privé", "private", "15"),
    ("général", "general", "15"),
    ("particulier", "particular, private", "15"),
    ("spécial", "special", "15"),
    ("utile", "useful", "15"),
    ("inutile", "useless", "15"),
    ("dangereux", "dangerous", "15"),
    ("tranquille", "quiet, peaceful", "15"),
    ("confortable", "comfortable", "15"),
    ("agité", "restless, choppy", "15"),
    ("simple", "simple", "15"),
    ("compliqué", "complicated", "15"),
    ("clair", "clear, light", "15"),
    ("sombre", "dark", "15"),
    ("profond", "deep", "15"),
    ("large", "wide", "15"),
    ("étroit", "narrow", "15"),
    ("rond", "round", "15"),
    ("droit", "straight, right", "15"),
    ("gauche", "left, awkward", "15"),
    ("chaque", "each, every", "15"),
    ("plusieurs", "several", "15", None, True),
    ("quelques", "a few", "15", None, True),
    ("certain", "certain, some", "15"),
    ("différent", "different", "15"),
    ("pareil", "same, alike", "15"),
    ("nombreux", "numerous", "15"),
]

# ---------------------------------------------------------------------------
# Closed classes: (French, English, pos, lesson)
# ---------------------------------------------------------------------------
OTHERS = [
    ("je", "I", "pronoun", "1"), ("tu", "you (informal sg.)", "pronoun", "1"),
    ("il", "he, it", "pronoun", "1"), ("elle", "she, it", "pronoun", "1"),
    ("on", "one, we (informal)", "pronoun", "1"), ("nous", "we", "pronoun", "1"),
    ("vous", "you (formal or plural)", "pronoun", "1"), ("ils", "they (m)", "pronoun", "1"),
    ("elles", "they (f)", "pronoun", "1"), ("moi", "me", "pronoun", "1"),
    ("toi", "you (stressed)", "pronoun", "1"), ("ce", "this, that, it", "pronoun", "1"),
    ("qui", "who", "pronoun", "1"), ("que", "that, which, what", "pronoun", "1"),
    ("quoi", "what", "pronoun", "1"), ("mon", "my", "pronoun", "1"),
    ("ton", "your (informal)", "pronoun", "1"), ("son", "his, her, its", "pronoun", "1"),
    ("notre", "our", "pronoun", "1"), ("votre", "your (formal/plural)", "pronoun", "1"),
    ("leur", "their", "pronoun", "1"), ("quelqu'un", "someone", "pronoun", "1"),
    ("quelque chose", "something", "pronoun", "1"), ("rien", "nothing", "pronoun", "1"),
    ("tout le monde", "everyone", "pronoun", "1"),
    ("de", "of, from", "preposition", "9"), ("à", "to, at, in", "preposition", "9"),
    ("dans", "in, into", "preposition", "9"), ("sur", "on", "preposition", "9"),
    ("sous", "under", "preposition", "9"), ("avec", "with", "preposition", "9"),
    ("sans", "without", "preposition", "9"), ("pour", "for, in order to", "preposition", "9"),
    ("par", "by, through", "preposition", "9"), ("chez", "at the house of", "preposition", "9"),
    ("entre", "between", "preposition", "9"), ("devant", "in front of", "preposition", "9"),
    ("derrière", "behind", "preposition", "9"), ("près de", "near", "preposition", "9"),
    ("loin de", "far from", "preposition", "9"), ("avant", "before", "preposition", "13"),
    ("après", "after", "preposition", "13"), ("pendant", "during, for", "preposition", "13"),
    ("depuis", "since, for", "preposition", "13"), ("vers", "towards, around", "preposition", "13"),
    ("et", "and", "conjunction", "16"), ("mais", "but", "conjunction", "16"),
    ("ou", "or", "conjunction", "16"), ("donc", "so, therefore", "conjunction", "16"),
    ("parce que", "because", "conjunction", "16"), ("car", "for, because", "conjunction", "16"),
    ("si", "if", "conjunction", "16"), ("quand", "when", "conjunction", "16"),
    ("comme", "as, like", "conjunction", "16"), ("alors", "then, so", "conjunction", "16"),
    ("puis", "then, next", "conjunction", "16"), ("aussi", "also, too", "conjunction", "16"),
    ("pourtant", "however, yet", "conjunction", "16"), ("cependant", "however", "conjunction", "16"),
    ("en fait", "in fact, actually", "conjunction", "16"),
    ("du coup", "so, as a result", "conjunction", "16"),
    ("bref", "in short, anyway", "conjunction", "16"),
    ("d'ailleurs", "besides, by the way", "conjunction", "16"),
    ("par contre", "on the other hand", "conjunction", "16"),
    ("c'est-à-dire", "that is to say", "conjunction", "16"),
    ("quand même", "all the same, still", "conjunction", "16"),
    ("euh", "er, um", "conjunction", "16"),
    ("ben", "well (informal filler)", "conjunction", "16"),
    ("voilà", "there you go, that's it", "conjunction", "16"),
    ("oui", "yes", "adverb", "16"), ("non", "no", "adverb", "16"),
    ("si2", "yes (contradicting)", "adverb", "16"),
    ("ne... pas", "not", "adverb", "16"), ("jamais", "never", "adverb", "13"),
    ("toujours", "always", "adverb", "13"), ("souvent", "often", "adverb", "13"),
    ("parfois", "sometimes", "adverb", "13"), ("rarement", "rarely", "adverb", "13"),
    ("maintenant", "now", "adverb", "13"), ("aujourd'hui", "today", "adverb", "13"),
    ("hier", "yesterday", "adverb", "13"), ("demain", "tomorrow", "adverb", "13"),
    ("bientôt", "soon", "adverb", "13"), ("déjà", "already", "adverb", "13"),
    ("encore", "again, still", "adverb", "13"), ("enfin", "finally, at last", "adverb", "13"),
    ("tôt", "early", "adverb", "13"), ("tard", "late", "adverb", "13"),
    ("longtemps", "a long time", "adverb", "13"), ("ensuite", "then, next", "adverb", "13"),
    ("bien", "well", "adverb", "15"), ("mal", "badly", "adverb", "15"),
    ("mieux", "better", "adverb", "15"), ("beaucoup", "a lot, much", "adverb", "15"),
    ("peu", "little, few", "adverb", "15"), ("très", "very", "adverb", "15"),
    ("trop", "too, too much", "adverb", "15"), ("assez", "enough, quite", "adverb", "15"),
    ("plus", "more", "adverb", "15"), ("moins", "less", "adverb", "15"),
    ("presque", "almost", "adverb", "15"), ("vraiment", "really", "adverb", "15"),
    ("surtout", "especially, above all", "adverb", "15"),
    ("ensemble", "together", "adverb", "15"), ("vite", "quickly", "adverb", "15"),
    ("lentement", "slowly", "adverb", "15"), ("ici", "here", "adverb", "9"),
    ("là", "there", "adverb", "9"), ("où", "where", "adverb", "9"),
    ("partout", "everywhere", "adverb", "9"), ("comment", "how", "adverb", "11"),
    ("pourquoi", "why", "adverb", "11"), ("combien", "how much, how many", "adverb", "11"),
    ("peut-être2", "perhaps", "adverb", "11"),
    ("un", "one", "number", "13"), ("deux", "two", "number", "13"),
    ("trois", "three", "number", "13"), ("quatre", "four", "number", "13"),
    ("cinq", "five", "number", "13"), ("six", "six", "number", "13"),
    ("sept", "seven", "number", "13"), ("huit", "eight", "number", "13"),
    ("neuf", "nine", "number", "13"), ("dix", "ten", "number", "13"),
    ("onze", "eleven", "number", "13"), ("douze", "twelve", "number", "13"),
    ("vingt", "twenty", "number", "13"), ("trente", "thirty", "number", "13"),
    ("quarante", "forty", "number", "13"), ("cinquante", "fifty", "number", "13"),
    ("soixante", "sixty", "number", "13"), ("cent", "hundred", "number", "13"),
    ("mille", "thousand", "number", "13"),

    # === batch 2 ===========================================================
    ("bien sûr que oui", "of course (yes)", "adverb", "16"),
    ("carrément", "totally, absolutely", "adverb", "16"),
    ("franchement", "frankly", "adverb", "16"),
    ("apparemment", "apparently", "adverb", "16"),
    ("évidemment", "obviously", "adverb", "16"),
    ("heureusement", "fortunately", "adverb", "16"),
    ("malheureusement", "unfortunately", "adverb", "16"),
    ("normalement", "normally", "adverb", "16"),
    ("finalement", "finally, in the end", "adverb", "16"),
    ("généralement", "generally", "adverb", "16"),
    ("complètement", "completely", "adverb", "16"),
    ("absolument", "absolutely", "adverb", "16"),
    ("exactement", "exactly", "adverb", "16"),
    ("simplement", "simply", "adverb", "16"),
    ("sérieusement", "seriously", "adverb", "16"),
    ("doucement", "gently, slowly", "adverb", "16"),
    ("tellement", "so, so much", "adverb", "16"),
    ("plutôt", "rather", "adverb", "16"),
    ("environ", "about, approximately", "adverb", "16"),
    ("à peu près", "roughly", "adverb", "16"),
    ("tout de suite", "right away", "adverb", "13"),
    ("de temps en temps", "from time to time", "adverb", "13"),
    ("d'habitude", "usually", "adverb", "13"),
    ("en ce moment", "at the moment", "adverb", "13"),
    ("tout à l'heure", "in a while, a while ago", "adverb", "13"),
    ("avant-hier", "the day before yesterday", "adverb", "13"),
    ("après-demain", "the day after tomorrow", "adverb", "13"),
    ("dehors", "outside", "adverb", "9"),
    ("dedans", "inside", "adverb", "9"),
    ("en haut", "upstairs, at the top", "adverb", "9"),
    ("en bas", "downstairs, at the bottom", "adverb", "9"),
    ("là-bas", "over there", "adverb", "9"),
    ("quel", "which, what", "pronoun", "11"),
    ("lequel", "which one", "pronoun", "11"),
    ("celui", "the one", "pronoun", "11"),
    ("y", "there (pronoun)", "pronoun", "11"),
    ("en2", "of it, some", "pronoun", "11"),
    ("soixante-dix", "seventy", "number", "13"),
    ("quatre-vingts", "eighty", "number", "13"),
    ("quatre-vingt-dix", "ninety", "number", "13"),
    ("premier2", "first (ordinal)", "number", "13"),
    ("million", "million", "number", "13"),
]

DEDUPE_SUFFIX = {"si2": "si", "peut-être2": "peut-être",
                 "en2": "en", "premier2": "premier"}

# ---------------------------------------------------------------------------
# Cloze — lines of dialogue, not isolated sentences.
# ---------------------------------------------------------------------------
CLOZE = {
    "être": [("Je {suis} très content de te voir.", "I'm very glad to see you."),
             ("Vous {êtes} d'ici ?", "Are you from around here?")],
    "avoir": [("J'{ai} deux frères.", "I have two brothers."),
              ("Ils {ont} un petit chien.", "They have a little dog.")],
    "aller": [("Comment ça {va} aujourd'hui ?", "How are things today?"),
              ("Nous {allons} au restaurant ce soir.", "We're going to the restaurant tonight.")],
    "faire": [("Qu'est-ce que tu {fais} ce week-end ?", "What are you doing this weekend?"),
              ("Il {fait} beau aujourd'hui.", "The weather is nice today.")],
    "venir": [("Tu {viens} avec nous ?", "Are you coming with us?"),
              ("Ils {viennent} de Paris.", "They come from Paris.")],
    "pouvoir": [("Je ne {peux} pas venir ce soir.", "I can't come this evening."),
                ("Vous {pouvez} répéter, s'il vous plaît ?", "Can you repeat that, please?")],
    "vouloir": [("Tu {veux} un café ?", "Do you want a coffee?"),
                ("Nous {voulons} rester ici.", "We want to stay here.")],
    "savoir": [("Je ne {sais} pas.", "I don't know."),
               ("Vous {savez} où est la gare ?", "Do you know where the station is?")],
    "connaître": [("Tu {connais} ce restaurant ?", "Do you know this restaurant?"),
                  ("Je {connais} bien ce quartier.", "I know this neighbourhood well.")],
    "prendre": [("Je {prends} un thé, merci.", "I'll have a tea, thanks."),
                ("Nous {prenons} le train de huit heures.", "We're taking the eight o'clock train.")],
    "parler": [("Vous {parlez} anglais ?", "Do you speak English?"),
               ("Nous {parlons} de nos vacances.", "We're talking about our holidays.")],
    "habiter": [("J'{habite} près d'ici.", "I live near here."),
                ("Où {habitez}-vous ?", "Where do you live?")],
    "travailler": [("Je {travaille} dans un bureau.", "I work in an office."),
                   ("Tu {travailles} demain ?", "Are you working tomorrow?")],
    "aimer": [("J'{aime} beaucoup cette ville.", "I like this city a lot."),
              ("Vous {aimez} la cuisine française ?", "Do you like French cooking?")],
    "penser": [("Je {pense} que c'est une bonne idée.", "I think it's a good idea."),
               ("Qu'est-ce que tu en {penses} ?", "What do you think of it?")],
    "trouver": [("Je {trouve} ça très intéressant.", "I find that very interesting."),
                ("Comment {trouvez}-vous le film ?", "What do you think of the film?")],
    "manger": [("Nous {mangeons} vers huit heures.", "We eat around eight."),
               ("Tu {manges} avec nous ?", "Are you eating with us?")],
    "boire": [("Je {bois} un verre d'eau.", "I'm drinking a glass of water."),
              ("Qu'est-ce que vous {buvez} ?", "What are you drinking?")],
    "partir": [("Je {pars} demain matin.", "I'm leaving tomorrow morning."),
               ("À quelle heure {partez}-vous ?", "What time are you leaving?")],
    "attendre": [("J'{attends} un ami.", "I'm waiting for a friend."),
                 ("Nous {attendons} depuis vingt minutes.", "We've been waiting twenty minutes.")],
    "acheter": [("J'{achète} du pain tous les jours.", "I buy bread every day."),
                ("Ils {achètent} une nouvelle voiture.", "They're buying a new car.")],
    "préférer": [("Je {préfère} le thé au café.", "I prefer tea to coffee."),
                 ("Elles {préfèrent} rester à la maison.", "They prefer to stay at home.")],
    "appeler": [("Je t'{appelle} ce soir.", "I'll call you tonight."),
                ("Comment {appelles}-tu ce plat ?", "What do you call this dish?")],
    "commencer": [("Nous {commençons} à huit heures.", "We start at eight."),
                  ("Le film {commence} bientôt.", "The film starts soon.")],
    "payer": [("Je {paie} l'addition.", "I'll pay the bill."),
              ("Nous {payons} par carte.", "We're paying by card.")],
    "dormir": [("Je {dors} très mal en ce moment.", "I'm sleeping very badly at the moment."),
               ("Les enfants {dorment} déjà.", "The children are already asleep.")],
    "sortir": [("On {sort} ce soir ?", "Shall we go out tonight?"),
               ("Ils {sortent} souvent le samedi.", "They often go out on Saturdays.")],
    "voir": [("Je {vois} ce que tu veux dire.", "I see what you mean."),
             ("On se {voit} demain ?", "Shall we see each other tomorrow?")],
    "bon": [("C'est une {bonne} idée.", "That's a good idea."),
            ("Les gâteaux sont très {bons}.", "The cakes are very good.")],
    "beau": [("Quelle {belle} journée !", "What a beautiful day!"),
             ("Il fait {beau} aujourd'hui.", "The weather is nice today.")],
    "nouveau": [("C'est ma {nouvelle} voisine.", "That's my new neighbour."),
                ("J'ai un {nouveau} travail.", "I have a new job.")],
    "content": [("Je suis très {content} de te voir.", "I'm very glad to see you."),
                ("Elle est {contente} de son travail.", "She's happy with her job.")],
    "fatigué": [("Je suis {fatigué} ce soir.", "I'm tired this evening."),
                ("Elles sont {fatiguées} après le voyage.", "They're tired after the journey.")],
    "français": [("J'apprends la langue {française}.", "I'm learning the French language."),
                 ("Les vins {français} sont célèbres.", "French wines are famous.")],
    "premier": [("C'est la {première} fois.", "It's the first time."),
                ("Le {premier} train part à six heures.", "The first train leaves at six.")],
    "maison": [("Je rentre à la {maison}.", "I'm going home."),
               ("Les {maisons} ici sont très vieilles.", "The houses here are very old.")],
    "temps": [("Quel {temps} fait-il ?", "What's the weather like?"),
              ("Je n'ai pas le {temps}.", "I don't have time.")],
    "travail": [("J'aime beaucoup mon {travail}.", "I like my job a lot."),
                ("Les {travaux} dans la rue font du bruit.", "The roadworks in the street are noisy.")],
    "ami": [("C'est un vieil {ami}.", "He's an old friend."),
            ("Mes {amis} arrivent ce soir.", "My friends are arriving tonight.")],
    "eau": [("Une bouteille d'{eau}, s'il vous plaît.", "A bottle of water, please."),
            ("Les {eaux} de la rivière sont froides.", "The river waters are cold.")],
    "œil": [("J'ai quelque chose dans l'{œil}.", "I have something in my eye."),
            ("Elle a de beaux {yeux}.", "She has beautiful eyes.")],
    "journal": [("Je lis le {journal} le matin.", "I read the newspaper in the morning."),
                ("Les {journaux} en parlent beaucoup.", "The newspapers talk about it a lot.")],

    "dire": [("Qu'est-ce que tu {dis} ?", "What are you saying?"),
             ("Ils {disent} que c'est fermé.", "They say it's closed.")],
    "mettre": [("Je {mets} mon manteau.", "I'm putting on my coat."),
               ("Où est-ce que vous {mettez} les clés ?", "Where do you put the keys?")],
    "devoir": [("Je {dois} partir maintenant.", "I have to leave now."),
               ("Nous {devons} réserver une table.", "We have to book a table.")],
    "croire": [("Je {crois} qu'il a raison.", "I think he's right."),
               ("Vous {croyez} vraiment ?", "Do you really think so?")],
    "écrire": [("J'{écris} un message à Marie.", "I'm writing a message to Marie."),
               ("Nous {écrivons} souvent.", "We write often.")],
    "lire": [("Je {lis} le journal le matin.", "I read the paper in the morning."),
             ("Ils {lisent} beaucoup.", "They read a lot.")],
    "rester": [("Je {reste} à la maison ce soir.", "I'm staying home tonight."),
               ("Combien de temps {restez}-vous ?", "How long are you staying?")],
    "arriver": [("Le train {arrive} à huit heures.", "The train arrives at eight."),
                ("Nous {arrivons} demain.", "We arrive tomorrow.")],
    "rentrer": [("Je {rentre} vers minuit.", "I get home around midnight."),
                ("Tu {rentres} à pied ?", "Are you walking home?")],
    "jouer": [("Les enfants {jouent} dans le jardin.", "The children are playing in the garden."),
              ("Tu {joues} au tennis ?", "Do you play tennis?")],
    "écouter": [("J'{écoute} de la musique.", "I'm listening to music."),
                ("Vous {écoutez} la radio ?", "Do you listen to the radio?")],
    "regarder": [("On {regarde} un film ce soir ?", "Shall we watch a film tonight?"),
                 ("Ils {regardent} le match.", "They're watching the match.")],
    "chercher": [("Je {cherche} la gare.", "I'm looking for the station."),
                 ("Qu'est-ce que tu {cherches} ?", "What are you looking for?")],
    "donner": [("Tu me {donnes} ton numéro ?", "Will you give me your number?"),
               ("Ils nous {donnent} un cadeau.", "They're giving us a present.")],
    "apprendre": [("J'{apprends} le français.", "I'm learning French."),
                  ("Nous {apprenons} vite.", "We learn quickly.")],
    "comprendre": [("Je ne {comprends} pas bien.", "I don't understand well."),
                   ("Vous {comprenez} l'anglais ?", "Do you understand English?")],
    "finir": [("Je {finis} à six heures.", "I finish at six."),
              ("Ils {finissent} le travail.", "They're finishing the work.")],
    "choisir": [("Je {choisis} le poisson.", "I'll choose the fish."),
                ("Vous {choisissez} quoi ?", "What are you choosing?")],
    "ouvrir": [("J'{ouvre} la fenêtre.", "I'm opening the window."),
               ("Ils {ouvrent} à neuf heures.", "They open at nine.")],
    "recevoir": [("Je {reçois} beaucoup de messages.", "I get a lot of messages."),
                 ("Nous {recevons} des amis ce soir.", "We're having friends over tonight.")],
    "vivre": [("Je {vis} ici depuis dix ans.", "I've lived here for ten years."),
              ("Ils {vivent} à la campagne.", "They live in the countryside.")],
    "devenir": [("Il {devient} très bon.", "He's getting very good."),
                ("Les jours {deviennent} plus courts.", "The days are getting shorter.")],
    "s'appeler": [("Je {m'appelle} Pierre.", "My name is Pierre."),
                  ("Comment {s'appelle}-t-elle ?", "What is she called?")],
    "se lever": [("Je {me lève} à sept heures.", "I get up at seven."),
                 ("À quelle heure vous {vous levez} ?", "What time do you get up?")],
    "espérer": [("J'{espère} que ça va aller.", "I hope it'll be all right."),
                ("Nous {espérons} te voir bientôt.", "We hope to see you soon.")],
    "discuter": [("On {discute} de nos vacances.", "We're talking about our holidays."),
                 ("Ils {discutent} depuis une heure.", "They've been chatting for an hour.")],
    "grand": [("C'est une {grande} maison.", "It's a big house."),
              ("Mes {grands} frères habitent à Paris.", "My big brothers live in Paris.")],
    "petit": [("Elle habite dans une {petite} ville.", "She lives in a small town."),
              ("Les {petits} détails comptent.", "The small details matter.")],
    "heureux": [("Je suis {heureux} de te voir.", "I'm happy to see you."),
                ("Elle est très {heureuse} ici.", "She's very happy here.")],
    "cher": [("C'est trop {cher} pour moi.", "It's too expensive for me."),
             ("La vie est {chère} ici.", "Life is expensive here.")],
    "gentil": [("Il est très {gentil} avec moi.", "He's very kind to me."),
               ("Elle est {gentille} avec tout le monde.", "She's kind to everyone.")],
    "blanc": [("Il a une chemise {blanche}.", "He has a white shirt."),
              ("Les murs sont {blancs}.", "The walls are white.")],
    "long": [("C'est une {longue} histoire.", "It's a long story."),
             ("Les jours sont {longs} en été.", "The days are long in summer.")],
    "vent": [("Il y a beaucoup de {vent} aujourd'hui.", "It's very windy today."),
             ("Les {vents} d'automne sont froids.", "The autumn winds are cold.")],
    "ville": [("J'aime cette {ville}.", "I like this city."),
              ("Les grandes {villes} sont bruyantes.", "Big cities are noisy.")],
    "heure": [("Quelle {heure} est-il ?", "What time is it?"),
              ("J'ai attendu deux {heures}.", "I waited two hours.")],
    "café": [("Tu veux un {café} ?", "Do you want a coffee?"),
             ("Les {cafés} sont pleins le dimanche.", "The cafés are full on Sundays.")],
    "gâteau": [("Ce {gâteau} est délicieux.", "This cake is delicious."),
               ("Elle fait de très bons {gâteaux}.", "She makes very good cakes.")],
    "voiture": [("Ma {voiture} est en panne.", "My car has broken down."),
                ("Il y a trop de {voitures} ici.", "There are too many cars here.")],
    "enfant": [("Leur {enfant} a cinq ans.", "Their child is five."),
               ("Les {enfants} jouent dehors.", "The children are playing outside.")],
    "cheveu": [("J'ai un {cheveu} sur la veste.", "I have a hair on my jacket."),
               ("Elle a les {cheveux} courts.", "She has short hair.")],
    "bureau": [("Je vais au {bureau} en métro.", "I go to the office by metro."),
               ("Les {bureaux} ferment à six heures.", "The offices close at six.")],
}

ANTONYMS = [
    ("grand", "petit"), ("bon", "mauvais"), ("nouveau", "vieux"),
    ("long", "court"), ("haut", "bas"), ("chaud", "froid"),
    ("facile", "difficile"), ("fort", "faible"), ("rapide", "lent"),
    ("riche", "pauvre"), ("heureux", "triste"), ("ouvert", "fermé"),
    ("plein", "vide"), ("propre", "sale"), ("vrai", "faux"),
    ("premier", "dernier"), ("blanc", "noir"), ("libre", "occupé"),
    ("jeune", "vieux"), ("léger", "lourd"), ("beau", "laid"),
    ("homme", "femme"), ("père", "mère"), ("frère", "sœur"),
    ("mari", "épouse"), ("jour", "nuit"), ("matin", "soir"),
    ("été", "hiver"), ("début", "fin"), ("question", "réponse"),
    ("bruit", "silence"), ("joie", "peur"),
    ("oui", "non"), ("toujours", "jamais"), ("bien", "mal"),
    ("beaucoup", "peu"), ("plus", "moins"), ("ici", "là"),
    ("avant", "après"), ("tôt", "tard"), ("aujourd'hui", "demain"),
    ("avec", "sans"), ("devant", "derrière"), ("sur", "sous"),
    ("arriver", "partir"), ("entrer", "sortir"), ("monter", "descendre"),
    ("acheter", "vendre"), ("ouvrir", "fermer"), ("gagner", "perdre"),
    ("rire", "pleurer"), ("aimer", "détester"), ("commencer", "finir"),
    ("naître", "mourir"), ("demander", "répondre"),
]
SYNONYMS = [
    ("aimer", "adorer"), ("penser", "croire"), ("rester", "habiter"),
    ("travail", "métier"), ("avis", "idée"), ("voyage", "vacances"),
    ("bientôt", "vite"), ("parfois", "souvent"), ("alors", "donc"),
    ("cependant", "pourtant"), ("gentil", "sympa"), ("drôle", "intéressant"),
    ("ville", "quartier"), ("chose", "problème"), ("enfin", "ensuite"),
]

# ---------------------------------------------------------------------------
# SPECIAL BANK 1: tu vs vous — the register decision small talk lives or dies on.
# ---------------------------------------------------------------------------
TU_VOUS = [
    ("Bonjour madame, comment {allez-vous} ?", "Good morning madam, how are you?", "vas-tu", "vous: a stranger, and a formal title"),
    ("Salut Marie ! Comment {vas-tu} ?", "Hi Marie! How are you?", "allez-vous", "tu: a friend, first-name terms"),
    ("Excusez-moi monsieur, {pouvez-vous} m'aider ?", "Excuse me sir, can you help me?", "peux-tu", "vous: stranger in the street"),
    ("Papa, {tu} viens manger ?", "Dad, are you coming to eat?", "vous", "tu: close family"),
    ("Monsieur le directeur, {vous} avez raison.", "Director, you are right.", "tu", "vous: hierarchy at work"),
    ("Chérie, {tu} as vu mes clés ?", "Darling, have you seen my keys?", "vous", "tu: partner"),
    ("Bonjour, {vous} désirez ?", "Hello, what would you like?", "tu", "vous: shop assistant to a customer"),
    ("Alors les enfants, {vous} êtes prêts ?", "So kids, are you ready?", "tu", "vous: plural — several people, however close"),
    ("Mamie, {tu} veux du thé ?", "Granny, do you want some tea?", "vous", "tu: grandparent, close family"),
    ("Madame, {votre} table est prête.", "Madam, your table is ready.", "ta", "vous: possessive follows the register"),
    ("Marc, je {t}'appelle ce soir.", "Marc, I'll call you tonight.", "vous", "tu: a friend — object pronoun follows too"),
    ("Docteur, {vous} pensez que c'est grave ?", "Doctor, do you think it's serious?", "tu", "vous: professional you don't know"),
    ("Tom, {ton} vélo est dans le jardin.", "Tom, your bike is in the garden.", "votre", "tu: child you know well"),
    ("Bonjour, {vous} avez réservé ?", "Hello, have you booked?", "tu", "vous: restaurant staff to a guest"),
    ("Julie, {viens} voir !", "Julie, come and see!", "venez", "tu: imperative to a friend"),
    ("Messieurs-dames, {asseyez-vous} je vous en prie.", "Ladies and gentlemen, please sit down.", "assieds-toi", "vous: a group, formally"),
    ("Mon amour, {tu} me manques.", "My love, I miss you.", "vous", "tu: intimate"),
    ("Madame la présidente, {puis-je} vous poser une question ?", "Madam President, may I ask you a question?", "peux-tu", "vous: very formal address"),
    ("Salut, ça {te} dit un ciné ?", "Hi, do you fancy a cinema trip?", "vous", "tu: informal invitation to a mate"),
    ("Pardon monsieur, {savez-vous} où est la gare ?", "Excuse me sir, do you know where the station is?", "sais-tu", "vous: asking a stranger directions"),
    ("Léa, {tes} parents vont bien ?", "Léa, are your parents well?", "vos", "tu: friend — plural possessive still tu-form"),
    ("Bonjour, je {vous} présente ma collègue.", "Hello, let me introduce my colleague.", "te", "vous: introducing in a professional setting"),
    ("Grand-père, {raconte}-moi une histoire.", "Grandpa, tell me a story.", "racontez", "tu: close family, imperative"),
    ("Cher client, nous {vous} remercions.", "Dear customer, we thank you.", "te", "vous: business writing"),
    ("Hé, {tu} fais quoi ce soir ?", "Hey, what are you doing tonight?", "vous", "tu: casual, among friends"),
    ("Madame, {pourriez-vous} patienter ?", "Madam, could you wait?", "pourrais-tu", "vous: polite request to a customer"),
    ("Paul, on {se} tutoie ?", "Paul, shall we use tu with each other?", "vous", "the moment you switch register — se tutoyer"),
    ("On peut {se} tutoyer, si vous voulez.", "We can use tu, if you like.", "nous", "offering the switch — note the vous while still asking"),
    ("Bonjour, {vous} êtes monsieur Dupont ?", "Hello, are you Mr Dupont?", "tu", "vous: meeting someone for the first time"),
    ("Salut les gars, {vous} venez ?", "Hi guys, are you coming?", "tu", "vous: plural of tu — friends, but more than one"),
]

# ---------------------------------------------------------------------------
# SPECIAL BANK 2: avoir vs être as the passé composé auxiliary.
# ---------------------------------------------------------------------------
AVOIR_ETRE = [
    ("Hier, j'{ai} mangé au restaurant.", "Yesterday I ate at a restaurant.", "suis", "avoir: transitive verb with an object"),
    ("Elle {a} acheté une nouvelle voiture.", "She bought a new car.", "est", "avoir: transitive"),
    ("Nous {avons} vu un très bon film.", "We saw a very good film.", "sommes", "avoir: transitive"),
    ("Ils {ont} pris le train de huit heures.", "They took the eight o'clock train.", "sont", "avoir: transitive"),
    ("Tu {as} fini ton travail ?", "Have you finished your work?", "es", "avoir: transitive"),
    ("J'{ai} parlé avec le patron.", "I spoke with the boss.", "suis", "avoir: parler takes avoir"),
    ("Vous {avez} bien dormi ?", "Did you sleep well?", "êtes", "avoir: dormir takes avoir"),
    ("Il {a} travaillé toute la journée.", "He worked all day.", "est", "avoir: travailler takes avoir"),
    ("Nous {avons} beaucoup marché.", "We walked a lot.", "sommes", "avoir: marcher takes avoir"),
    ("Elle {a} téléphoné ce matin.", "She phoned this morning.", "est", "avoir: téléphoner takes avoir"),
    ("J'{ai} attendu une heure.", "I waited an hour.", "suis", "avoir: attendre takes avoir"),
    ("Ils {ont} bien ri.", "They laughed a lot.", "sont", "avoir: rire takes avoir"),
    ("Tu {as} payé l'addition ?", "Did you pay the bill?", "es", "avoir: transitive"),
    ("On {a} passé une bonne soirée.", "We had a good evening.", "est", "avoir: passer with an object takes avoir"),
    ("Elle {a} été malade la semaine dernière.", "She was ill last week.", "est", "avoir: être itself takes avoir in French"),
    ("Je {suis} allé au cinéma.", "I went to the cinema.", "ai", "être: aller — one of the DR & MRS VANDERTRAMP verbs"),
    ("Elle {est} venue avec nous.", "She came with us.", "a", "être: venir"),
    ("Nous {sommes} arrivés en retard.", "We arrived late.", "avons", "être: arriver"),
    ("Ils {sont} partis ce matin.", "They left this morning.", "ont", "être: partir"),
    ("Tu {es} sorti hier soir ?", "Did you go out last night?", "as", "être: sortir"),
    ("Je {suis} entré dans le magasin.", "I went into the shop.", "ai", "être: entrer"),
    ("Elle {est} rentrée très tard.", "She got home very late.", "a", "être: rentrer"),
    ("Nous {sommes} montés au premier étage.", "We went up to the first floor.", "avons", "être: monter without an object"),
    ("Ils {sont} descendus par l'escalier.", "They came down the stairs.", "ont", "être: descendre without an object"),
    ("Le verre {est} tombé.", "The glass fell.", "a", "être: tomber"),
    ("Mon grand-père {est} mort il y a deux ans.", "My grandfather died two years ago.", "a", "être: mourir"),
    ("Elle {est} née à Lyon.", "She was born in Lyon.", "a", "être: naître"),
    ("Il {est} devenu médecin.", "He became a doctor.", "a", "être: devenir"),
    ("Nous {sommes} restés à la maison.", "We stayed at home.", "avons", "être: rester"),
    ("Ils {sont} retournés en France.", "They went back to France.", "ont", "être: retourner without an object"),
    ("Je me {suis} levé à six heures.", "I got up at six.", "ai", "être: reflexive verbs always take être"),
    ("Elle s'{est} habillée rapidement.", "She got dressed quickly.", "a", "être: reflexive"),
    ("Nous nous {sommes} bien amusés.", "We enjoyed ourselves.", "avons", "être: reflexive"),
    ("Tu t'{es} souvenu de son nom ?", "Did you remember his name?", "as", "être: reflexive"),
    ("Ils se {sont} rencontrés à Paris.", "They met in Paris.", "ont", "être: reciprocal reflexive"),
    ("Je me {suis} couché tôt.", "I went to bed early.", "ai", "être: reflexive"),
    ("Elle {est} passée te voir.", "She dropped by to see you.", "a", "être: passer WITHOUT an object takes être"),
    ("Il {a} monté les valises.", "He carried the suitcases up.", "est", "avoir: monter WITH an object takes avoir"),
    ("Nous {avons} descendu la poubelle.", "We took the bin down.", "sommes", "avoir: descendre WITH an object takes avoir"),
    ("Elle {a} sorti son téléphone.", "She took out her phone.", "est", "avoir: sortir WITH an object takes avoir"),
]


def build():
    entries, by_head = [], {}
    n = 0

    def nid():
        nonlocal n
        n += 1
        return f"fr{n:04d}"

    for row in PHRASES:
        fr, en, lesson = row
        e = {"fr": fr, "en": en, "pos": "phrase", "id": nid(), "lesson": lesson}
        entries.append(e); by_head.setdefault(fr, e)

    for row in NOUNS:
        word, gender, en, lesson = row[0], row[1], row[2], row[3]
        explicit_pl = row[4] if len(row) > 4 else None
        forms = noun_forms(word, gender, plural=explicit_pl)
        e = {"fr": word, "en": en, "pos": "noun", "id": nid(), "lesson": lesson,
             "gender": gender, "plural": forms["plural"], "noun_decl": forms}
        entries.append(e); by_head.setdefault(word, e)

    for row in VERBS:
        inf, en, lesson = row[0], row[1], row[2]
        group = row[3] if len(row) > 3 else None
        changes = row[4] if len(row) > 4 else None
        e = {"fr": inf, "en": en, "pos": "verb", "id": nid(), "lesson": lesson}
        if inf not in IMPERSONAL:
            e["conjugation"] = conjugate(inf, group=group, stem_changes=changes)
        else:
            e["note"] = "impersonal — 3rd person singular only"
        entries.append(e); by_head.setdefault(inf, e)

    for row in ADJECTIVES:
        word, en, lesson = row[0], row[1], row[2]
        fem = row[3] if len(row) > 3 else None
        invariable = row[4] if len(row) > 4 else False
        e = {"fr": word, "en": en, "pos": "adjective", "id": nid(), "lesson": lesson,
             "declension": decline_adjective(word, feminine_form=fem, invariable=invariable)}
        entries.append(e); by_head.setdefault(word, e)

    for word, en, pos, lesson in OTHERS:
        head = DEDUPE_SUFFIX.get(word, word)
        e = {"fr": head, "en": en, "pos": pos, "id": nid(), "lesson": lesson}
        entries.append(e); by_head.setdefault(word, e)

    attached = 0
    for head, sents in CLOZE.items():
        if sents is None:
            continue
        e = by_head.get(head)
        assert e is not None, f"cloze references unknown headword {head!r}"
        e["cloze"] = [{"fr": s, "en": t} for s, t in sents]
        attached += len(sents)

    def link(pairs, field):
        for a, b in pairs:
            ea, eb = by_head.get(a), by_head.get(b)
            assert ea is not None, f"{field}: unknown headword {a!r}"
            assert eb is not None, f"{field}: unknown headword {b!r}"
            ea.setdefault(field, []); eb.setdefault(field, [])
            if eb["id"] not in ea[field]: ea[field].append(eb["id"])
            if ea["id"] not in eb[field]: eb[field].append(ea["id"])
    link(ANTONYMS, "antonyms")
    link(SYNONYMS, "synonyms")

    special = {
        "tu_vous": [{"id": f"tv{i+1:03d}", "fr": fr, "en": en, "wrong": w, "note": note}
                    for i, (fr, en, w, note) in enumerate(TU_VOUS)],
        "avoir_etre": [{"id": f"ae{i+1:03d}", "fr": fr, "en": en, "wrong": w, "note": note}
                       for i, (fr, en, w, note) in enumerate(AVOIR_ETRE)],
    }

    # ---- integrity ---------------------------------------------------------
    ids = [e["id"] for e in entries]
    assert len(ids) == len(set(ids)), "duplicate entry ids"
    keys = [(e["fr"], e["pos"]) for e in entries]
    dupes = [k for k, c in collections.Counter(keys).items() if c > 1]
    assert not dupes, f"duplicate (fr, pos) keys: {dupes}"
    byid = {e["id"]: e for e in entries}
    for e in entries:
        for field in ("antonyms", "synonyms"):
            for rid in e.get(field, []):
                assert rid in byid, f"{e['fr']}: dangling {field} id {rid}"
        for c in e.get("cloze", []):
            assert c["fr"].count("{") == 1 and c["fr"].count("}") == 1, \
                f"{e['fr']}: cloze must wrap exactly one target: {c['fr']!r}"
        for group in ("noun_decl", "declension", "conjugation"):
            if isinstance(e.get(group), dict):
                for k, v in e[group].items():
                    assert v and v.strip(), f"{e['fr']}: blank form for {group}.{k}"
        if e["pos"] == "verb" and "conjugation" in e:
            assert len(e["conjugation"]) == 6, f"{e['fr']}: {len(e['conjugation'])} persons"
    seen_special = set()
    for bank, items in special.items():
        assert items, f"{bank}: empty bank"
        for it in items:
            assert it["id"] not in seen_special, f"duplicate special id {it['id']}"
            seen_special.add(it["id"])
            assert it["fr"].count("{") == 1 and it["fr"].count("}") == 1, \
                f"{bank} {it['id']}: must wrap exactly one target"
            answer = it["fr"].split("{")[1].split("}")[0]
            assert it["wrong"], f"{bank} {it['id']}: missing counterpart"
            assert answer != it["wrong"], f"{bank} {it['id']}: answer equals counterpart"
            assert it["note"], f"{bank} {it['id']}: missing rule note"

    data = {"entries": entries,
            "meta": {"language": "French", "reference": "English",
                     "level": "A1-A2", "focus": "small talk", "version": "v1"},
            "special": special}
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    counts = collections.Counter(e["pos"] for e in entries)
    print(f"wrote {os.path.normpath(OUT)}: {len(entries)} entries")
    print("  " + " · ".join(f"{v} {k}" for k, v in counts.most_common()))
    print(f"  cloze: {attached} sentences across {sum(1 for v in CLOZE.values() if v)} words")
    print(f"  antonyms: {len(ANTONYMS)} pairs · synonyms: {len(SYNONYMS)} pairs")
    print(f"  special: tu_vous {len(special['tu_vous'])} · avoir_etre {len(special['avoir_etre'])}")


if __name__ == "__main__":
    build()
