#!/usr/bin/env python3
"""Built terms, plurals, confusable pairs, anatomy and prescription Latin.

TERMS carries (term, meaning, parts, lesson). `parts` is the decomposition a
student is expected to produce, and the generator checks that the parts can
actually spell the term (see segment_ok in build_medical_vocab.py) — a wrong
root, a wrong order or a typo fails the build.

EXTRA_ROOTS / EXTRA_SUFFIXES hold elements needed only to decompose terms here;
they are merged into the main element lists so they are drillable in their own
right too.
"""

EXTRA_ROOTS = [
    ("electr/o", "electricity, electrical activity", "G", "General & colour roots",
     "Gk elektron 'amber', which attracts when rubbed. Electrocardiogram, electroencephalogram."),
    ("appendic/o", "appendix", "L", "Gastrointestinal",
     "The stem used before a suffix: appendicitis, appendicectomy."),
    ("radi/o", "x-ray, radiation; also the radius bone", "L", "General & colour roots",
     "L radius 'ray, spoke'. Radiology, radiography — and the radius of the forearm."),
    ("son/o", "sound", "L", "General & colour roots", "L sonus. Sonography, ultrasound."),
    ("bronchi/o", "bronchus", "G", "Respiratory", "The stem seen in bronchiectasis."),
    ("cyst/i", "sac, cyst; bladder", "G", "Renal & urinary", "The -i- form seen in cystic fibrosis."),
    ("fasci/o", "fascia, band of connective tissue", "L", "Musculoskeletal",
     "L fascia 'band'. Fasciitis, fasciotomy."),
    ("men/i", "membrane", "G", "Musculoskeletal", "As in meniscus, the crescent of knee cartilage."),
]

EXTRA_SUFFIXES = [
    ("-cardia", "heart condition, heart rate", "G", "Suffixes: conditions & disease",
     "The compound suffix in tachycardia, bradycardia."),
    ("-thorax", "chest, pleural cavity", "G", "Suffixes: conditions & disease",
     "Pneumothorax (air), haemothorax (blood), hydrothorax (fluid)."),
    ("-ia", "condition, state of", "G", "Suffixes: conditions & disease",
     "The commonest condition ending: anaemia, pneumonia, hypoxia."),
    ("-ism", "condition, process, state", "G", "Suffixes: conditions & disease",
     "Hyperthyroidism, embolism, alcoholism."),
    ("-osmia", "sense of smell", "G", "Suffixes: conditions & disease",
     "Gk osme 'smell'. Anosmia — loss of smell."),
]

# (term, meaning, parts, lesson)
TERMS = [
    # --- cardiovascular
    ("carditis", "inflammation of the heart", ["cardi/o", "-itis"], "Cardiovascular"),
    ("cardiology", "the study of the heart", ["cardi/o", "-logy"], "Cardiovascular"),
    ("cardiomegaly", "enlargement of the heart", ["cardi/o", "-megaly"], "Cardiovascular"),
    ("cardiomyopathy", "disease of the heart muscle", ["cardi/o", "my/o", "-pathy"], "Cardiovascular"),
    ("pericarditis", "inflammation of the sac around the heart", ["peri-", "cardi/o", "-itis"], "Cardiovascular"),
    ("endocarditis", "inflammation of the inner lining of the heart", ["endo-", "cardi/o", "-itis"], "Cardiovascular"),
    ("myocarditis", "inflammation of the heart muscle", ["my/o", "cardi/o", "-itis"], "Cardiovascular"),
    ("tachycardia", "abnormally fast heart rate", ["tachy-", "-cardia"], "Cardiovascular"),
    ("bradycardia", "abnormally slow heart rate", ["brady-", "-cardia"], "Cardiovascular"),
    ("angiography", "imaging of the blood vessels", ["angi/o", "-graphy"], "Cardiovascular"),
    ("angioplasty", "surgical repair or widening of a vessel", ["angi/o", "-plasty"], "Cardiovascular"),
    ("arteriosclerosis", "hardening of the arteries", ["arteri/o", "-sclerosis"], "Cardiovascular"),
    ("atherosclerosis", "hardening of arteries from fatty plaque", ["ather/o", "-sclerosis"], "Cardiovascular"),
    ("phlebitis", "inflammation of a vein", ["phleb/o", "-itis"], "Cardiovascular"),
    ("phlebotomy", "incision into a vein, drawing blood", ["phleb/o", "-otomy"], "Cardiovascular"),
    ("thrombosis", "abnormal condition of clotting", ["thromb/o", "-osis"], "Cardiovascular"),
    ("thrombocytopenia", "deficiency of platelets", ["thromb/o", "cyt/o", "-penia"], "Cardiovascular"),
    ("thrombolysis", "breakdown of a clot", ["thromb/o", "-lysis"], "Cardiovascular"),
    ("embolectomy", "surgical removal of an embolus", ["embol/o", "-ectomy"], "Cardiovascular"),
    ("vasectomy", "surgical removal of part of the vas deferens", ["vas/o", "-ectomy"], "Cardiovascular"),
    ("electrocardiogram", "the record of the heart's electrical activity", ["electr/o", "cardi/o", "-gram"], "Cardiovascular"),
    ("valvuloplasty", "surgical repair of a valve", ["valvul/o", "-plasty"], "Cardiovascular"),
    ("aortography", "imaging of the aorta", ["aort/o", "-graphy"], "Cardiovascular"),

    # --- respiratory
    ("pneumonectomy", "surgical removal of a lung", ["pneumon/o", "-ectomy"], "Respiratory"),
    ("pneumothorax", "air in the pleural cavity", ["pneum/o", "-thorax"], "Respiratory"),
    ("bronchitis", "inflammation of the bronchi", ["bronch/o", "-itis"], "Respiratory"),
    ("bronchoscopy", "visual examination of the bronchi", ["bronch/o", "-scopy"], "Respiratory"),
    ("bronchiectasis", "abnormal dilation of the bronchi", ["bronchi/o", "-ectasis"], "Respiratory"),
    ("tracheostomy", "surgical opening into the trachea", ["trache/o", "-ostomy"], "Respiratory"),
    ("tracheotomy", "incision into the trachea", ["trache/o", "-otomy"], "Respiratory"),
    ("laryngitis", "inflammation of the larynx", ["laryng/o", "-itis"], "Respiratory"),
    ("laryngoscopy", "visual examination of the larynx", ["laryng/o", "-scopy"], "Respiratory"),
    ("pharyngitis", "inflammation of the pharynx", ["pharyng/o", "-itis"], "Respiratory"),
    ("rhinitis", "inflammation of the nasal lining", ["rhin/o", "-itis"], "Respiratory"),
    ("rhinorrhea", "discharge from the nose", ["rhin/o", "-rrhea"], "Respiratory"),
    ("rhinoplasty", "surgical reshaping of the nose", ["rhin/o", "-plasty"], "Respiratory"),
    ("sinusitis", "inflammation of a sinus", ["sinus/o", "-itis"], "Respiratory"),
    ("thoracotomy", "incision into the chest wall", ["thorac/o", "-otomy"], "Respiratory"),
    ("thoracocentesis", "puncture of the chest to drain fluid", ["thorac/o", "-centesis"], "Respiratory"),
    ("pleuritis", "inflammation of the pleura", ["pleur/o", "-itis"], "Respiratory"),
    ("apnea", "absence of breathing", ["a-", "-pnea"], "Respiratory"),
    ("dyspnea", "difficult or laboured breathing", ["dys-", "-pnea"], "Respiratory"),
    ("tachypnea", "abnormally rapid breathing", ["tachy-", "-pnea"], "Respiratory"),
    ("orthopnea", "breathlessness when lying flat", ["ortho-", "-pnea"], "Respiratory"),
    ("hypoxia", "deficient oxygen in the tissues", ["hypo-", "ox/i", "-ia"], "Respiratory"),
    ("hypercapnia", "excess carbon dioxide in the blood", ["hyper-", "capn/o", "-ia"], "Respiratory"),
    ("spirometry", "measurement of breathing", ["spir/o", "-metry"], "Respiratory"),
    ("hemoptysis", "coughing up blood from the lungs", ["hem/o", "-ptysis"], "Respiratory"),

    # --- gastrointestinal
    ("gastritis", "inflammation of the stomach lining", ["gastr/o", "-itis"], "Gastrointestinal"),
    ("gastroscopy", "visual examination of the stomach", ["gastr/o", "-scopy"], "Gastrointestinal"),
    ("gastrectomy", "surgical removal of the stomach", ["gastr/o", "-ectomy"], "Gastrointestinal"),
    ("gastroenterology", "the study of the stomach and intestines", ["gastr/o", "enter/o", "-logy"], "Gastrointestinal"),
    ("gastroenteritis", "inflammation of the stomach and intestines", ["gastr/o", "enter/o", "-itis"], "Gastrointestinal"),
    ("esophagitis", "inflammation of the oesophagus", ["esophag/o", "-itis"], "Gastrointestinal"),
    ("enteritis", "inflammation of the small intestine", ["enter/o", "-itis"], "Gastrointestinal"),
    ("colitis", "inflammation of the colon", ["col/o", "-itis"], "Gastrointestinal"),
    ("colonoscopy", "visual examination of the colon", ["colon/o", "-scopy"], "Gastrointestinal"),
    ("colostomy", "surgical opening from the colon to the surface", ["col/o", "-ostomy"], "Gastrointestinal"),
    ("colectomy", "surgical removal of the colon", ["col/o", "-ectomy"], "Gastrointestinal"),
    ("proctology", "the study of the rectum and anus", ["proct/o", "-logy"], "Gastrointestinal"),
    ("sigmoidoscopy", "visual examination of the sigmoid colon", ["sigmoid/o", "-scopy"], "Gastrointestinal"),
    ("appendicitis", "inflammation of the appendix", ["appendic/o", "-itis"], "Gastrointestinal"),
    ("appendectomy", "surgical removal of the appendix", ["append/o", "-ectomy"], "Gastrointestinal"),
    ("hepatitis", "inflammation of the liver", ["hepat/o", "-itis"], "Gastrointestinal"),
    ("hepatomegaly", "enlargement of the liver", ["hepat/o", "-megaly"], "Gastrointestinal"),
    ("hepatology", "the study of the liver", ["hepat/o", "-logy"], "Gastrointestinal"),
    ("cholecystitis", "inflammation of the gallbladder", ["cholecyst/o", "-itis"], "Gastrointestinal"),
    ("cholecystectomy", "surgical removal of the gallbladder", ["cholecyst/o", "-ectomy"], "Gastrointestinal"),
    ("cholelithiasis", "the condition of having gallstones", ["chol/e", "-lithiasis"], "Gastrointestinal"),
    ("pancreatitis", "inflammation of the pancreas", ["pancreat/o", "-itis"], "Gastrointestinal"),
    ("splenomegaly", "enlargement of the spleen", ["splen/o", "-megaly"], "Gastrointestinal"),
    ("splenectomy", "surgical removal of the spleen", ["splen/o", "-ectomy"], "Gastrointestinal"),
    ("laparotomy", "surgical incision into the abdomen", ["lapar/o", "-otomy"], "Gastrointestinal"),
    ("laparoscopy", "visual examination inside the abdomen", ["lapar/o", "-scopy"], "Gastrointestinal"),
    ("peritonitis", "inflammation of the peritoneum", ["periton/o", "-itis"], "Gastrointestinal"),
    ("gingivitis", "inflammation of the gums", ["gingiv/o", "-itis"], "Gastrointestinal"),
    ("glossitis", "inflammation of the tongue", ["gloss/o", "-itis"], "Gastrointestinal"),
    ("stomatitis", "inflammation of the mouth", ["stomat/o", "-itis"], "Gastrointestinal"),
    ("dysphagia", "difficulty swallowing", ["dys-", "-phagia"], "Gastrointestinal"),
    ("hematemesis", "vomiting blood", ["hemat/o", "-emesis"], "Gastrointestinal"),
    ("steatorrhea", "fatty stools", ["steat/o", "-rrhea"], "Gastrointestinal"),
    ("diarrhea", "frequent loose or liquid stools", ["dia-", "-rrhea"], "Gastrointestinal"),
    ("ileostomy", "surgical opening from the ileum to the surface", ["ile/o", "-ostomy"], "Gastrointestinal"),

    # --- renal and urinary
    ("nephritis", "inflammation of the kidney", ["nephr/o", "-itis"], "Renal & urinary"),
    ("nephrectomy", "surgical removal of a kidney", ["nephr/o", "-ectomy"], "Renal & urinary"),
    ("nephrology", "the study of the kidney", ["nephr/o", "-logy"], "Renal & urinary"),
    ("nephrolithiasis", "the condition of having kidney stones", ["nephr/o", "-lithiasis"], "Renal & urinary"),
    ("nephropathy", "disease of the kidney", ["nephr/o", "-pathy"], "Renal & urinary"),
    ("hydronephrosis", "swelling of a kidney from obstructed urine", ["hydr/o", "nephr/o", "-osis"], "Renal & urinary"),
    ("pyelonephritis", "inflammation of the renal pelvis and kidney", ["pyel/o", "nephr/o", "-itis"], "Renal & urinary"),
    ("glomerulonephritis", "inflammation of the glomeruli of the kidney", ["glomerul/o", "nephr/o", "-itis"], "Renal & urinary"),
    ("cystitis", "inflammation of the bladder", ["cyst/o", "-itis"], "Renal & urinary"),
    ("cystoscopy", "visual examination of the bladder", ["cyst/o", "-scopy"], "Renal & urinary"),
    ("urethritis", "inflammation of the urethra", ["urethr/o", "-itis"], "Renal & urinary"),
    ("ureteroscopy", "visual examination of the ureter", ["ureter/o", "-scopy"], "Renal & urinary"),
    ("urology", "the study of the urinary tract", ["ur/o", "-logy"], "Renal & urinary"),
    ("hematuria", "blood in the urine", ["hemat/o", "-uria"], "Renal & urinary"),
    ("polyuria", "passing abnormally large volumes of urine", ["poly-", "-uria"], "Renal & urinary"),
    ("dysuria", "painful or difficult urination", ["dys-", "-uria"], "Renal & urinary"),
    ("anuria", "absence of urine output", ["an-", "-uria"], "Renal & urinary"),
    ("oliguria", "abnormally scanty urine output", ["oligo-", "-uria"], "Renal & urinary"),
    ("nocturia", "waking at night to pass urine", ["noct/i", "-uria"], "Renal & urinary"),
    ("lithotripsy", "crushing of a stone", ["lith/o", "-tripsy"], "Renal & urinary"),

    # --- nervous system
    ("neuritis", "inflammation of a nerve", ["neur/o", "-itis"], "Nervous system"),
    ("neuralgia", "nerve pain", ["neur/o", "-algia"], "Nervous system"),
    ("neuropathy", "disease of the nerves", ["neur/o", "-pathy"], "Nervous system"),
    ("neurology", "the study of the nervous system", ["neur/o", "-logy"], "Nervous system"),
    ("encephalitis", "inflammation of the brain", ["encephal/o", "-itis"], "Nervous system"),
    ("encephalopathy", "disease or dysfunction of the brain", ["encephal/o", "-pathy"], "Nervous system"),
    ("electroencephalogram", "the record of the brain's electrical activity", ["electr/o", "encephal/o", "-gram"], "Nervous system"),
    ("meningitis", "inflammation of the meninges", ["mening/o", "-itis"], "Nervous system"),
    ("meningocele", "protrusion of the meninges through a defect", ["mening/o", "-cele"], "Nervous system"),
    ("myelitis", "inflammation of the spinal cord", ["myel/o", "-itis"], "Nervous system"),
    ("poliomyelitis", "inflammation of the grey matter of the spinal cord", ["poli/o", "myel/o", "-itis"], "Nervous system"),
    ("hemiplegia", "paralysis of one side of the body", ["hemi-", "-plegia"], "Nervous system"),
    ("paraplegia", "paralysis of both legs and the lower trunk", ["para-", "-plegia"], "Nervous system"),
    ("quadriplegia", "paralysis of all four limbs", ["quadri-", "-plegia"], "Nervous system"),
    ("hemiparesis", "weakness of one side of the body", ["hemi-", "-paresis"], "Nervous system"),
    ("aphasia", "loss of the ability to speak or understand speech", ["a-", "-phasia"], "Nervous system"),
    ("dysphasia", "impaired speech", ["dys-", "-phasia"], "Nervous system"),
    ("anesthesia", "loss of sensation", ["an-", "-esthesia"], "Nervous system"),
    ("paresthesia", "abnormal sensation such as pins and needles", ["para-", "-esthesia"], "Nervous system"),
    ("hydrocephalus", "accumulation of fluid within the brain", ["hydr/o", "cephal/o", "-us"], "Nervous system"),
    ("radiculopathy", "disease of a nerve root", ["radicul/o", "-pathy"], "Nervous system"),
    ("psychosis", "abnormal condition of the mind", ["psych/o", "-osis"], "Nervous system"),
    ("psychiatry", "the medical treatment of the mind", ["psych/o", "-iatry"], "Nervous system"),
    ("narcolepsy", "a disorder of sudden uncontrollable sleep", ["narc/o", "-lepsy"], "Nervous system"),
    ("bradykinesia", "abnormal slowness of movement", ["brady-", "-kinesia"], "Nervous system"),
    ("craniotomy", "surgical incision into the skull", ["crani/o", "-otomy"], "Nervous system"),
    ("glioma", "a tumour of the neuroglial cells", ["gli/o", "-oma"], "Nervous system"),

    # --- musculoskeletal
    ("osteitis", "inflammation of bone", ["oste/o", "-itis"], "Musculoskeletal"),
    ("osteomyelitis", "infection of bone and bone marrow", ["oste/o", "myel/o", "-itis"], "Musculoskeletal"),
    ("osteoarthritis", "degenerative inflammation of bone and joint", ["oste/o", "arthr/o", "-itis"], "Musculoskeletal"),
    ("osteomalacia", "abnormal softening of bone", ["oste/o", "-malacia"], "Musculoskeletal"),
    ("osteoporosis", "abnormal condition of porous, brittle bone", ["oste/o", "por/o", "-osis"], "Musculoskeletal"),
    ("osteotomy", "surgical cutting of a bone", ["oste/o", "-otomy"], "Musculoskeletal"),
    ("arthritis", "inflammation of a joint", ["arthr/o", "-itis"], "Musculoskeletal"),
    ("arthralgia", "joint pain", ["arthr/o", "-algia"], "Musculoskeletal"),
    ("arthroscopy", "visual examination inside a joint", ["arthr/o", "-scopy"], "Musculoskeletal"),
    ("arthroplasty", "surgical repair or replacement of a joint", ["arthr/o", "-plasty"], "Musculoskeletal"),
    ("arthrodesis", "surgical fusion of a joint", ["arthr/o", "-desis"], "Musculoskeletal"),
    ("arthrocentesis", "puncture of a joint to withdraw fluid", ["arthr/o", "-centesis"], "Musculoskeletal"),
    ("myalgia", "muscle pain", ["my/o", "-algia"], "Musculoskeletal"),
    ("myopathy", "disease of muscle", ["my/o", "-pathy"], "Musculoskeletal"),
    ("myositis", "inflammation of muscle", ["myos/o", "-itis"], "Musculoskeletal"),
    ("chondromalacia", "abnormal softening of cartilage", ["chondr/o", "-malacia"], "Musculoskeletal"),
    ("costochondritis", "inflammation of the rib cartilage", ["cost/o", "chondr/o", "-itis"], "Musculoskeletal"),
    ("tendinitis", "inflammation of a tendon", ["tendin/o", "-itis"], "Musculoskeletal"),
    ("tenosynovitis", "inflammation of a tendon and its sheath", ["ten/o", "synovi/o", "-itis"], "Musculoskeletal"),
    ("bursitis", "inflammation of a bursa", ["burs/o", "-itis"], "Musculoskeletal"),
    ("fasciitis", "inflammation of the fascia", ["fasci/o", "-itis"], "Musculoskeletal"),
    ("spondylitis", "inflammation of the vertebrae", ["spondyl/o", "-itis"], "Musculoskeletal"),
    ("kyphosis", "abnormal outward curvature of the spine", ["kyph/o", "-osis"], "Musculoskeletal"),
    ("lordosis", "abnormal inward curvature of the lower spine", ["lord/o", "-osis"], "Musculoskeletal"),
    ("scoliosis", "abnormal sideways curvature of the spine", ["scoli/o", "-osis"], "Musculoskeletal"),
    ("laminectomy", "surgical removal of a vertebral lamina", ["lamin/o", "-ectomy"], "Musculoskeletal"),
    ("osteoblast", "a bone-forming cell", ["oste/o", "-blast"], "Musculoskeletal"),
    ("osteoclast", "a cell that breaks down bone", ["oste/o", "-clast"], "Musculoskeletal"),

    # --- integumentary
    ("dermatitis", "inflammation of the skin", ["dermat/o", "-itis"], "Integumentary"),
    ("dermatology", "the study of the skin", ["dermat/o", "-logy"], "Integumentary"),
    ("epidermis", "the outer layer of the skin", ["epi-", "derm/o", "-is"], "Integumentary"),
    ("melanoma", "a malignant tumour of pigment cells", ["melan/o", "-oma"], "Integumentary"),
    ("onychomycosis", "a fungal infection of the nail", ["onych/o", "myc/o", "-osis"], "Integumentary"),
    ("hyperhidrosis", "excessive sweating", ["hyper-", "hidr/o", "-osis"], "Integumentary"),
    ("seborrhea", "excessive discharge of sebum", ["seb/o", "-rrhea"], "Integumentary"),
    ("xerosis", "abnormal dryness of the skin", ["xer/o", "-osis"], "Integumentary"),
    ("scleroderma", "abnormal hardening of the skin", ["scler/o", "derm/o", "-a"], "Integumentary"),
    ("cellulitis", "inflammation of the deep skin and soft tissue", ["cellul/o", "-itis"], "Integumentary"),
    ("lipoma", "a benign tumour of fat", ["lip/o", "-oma"], "Integumentary"),

    # --- blood, immune and lymphatic
    ("anemia", "a deficiency of red cells or haemoglobin", ["an-", "-emia"], "Blood & immune"),
    ("leukemia", "a malignant increase of white cells in the blood", ["leuk/o", "-emia"], "Blood & immune"),
    ("leukocytosis", "an abnormal increase in white cells", ["leuk/o", "cyt/o", "-osis"], "Blood & immune"),
    ("leukopenia", "a deficiency of white cells", ["leuk/o", "-penia"], "Blood & immune"),
    ("erythrocyte", "a red blood cell", ["erythr/o", "-cyte"], "Blood & immune"),
    ("leukocyte", "a white blood cell", ["leuk/o", "-cyte"], "Blood & immune"),
    ("hematology", "the study of the blood", ["hemat/o", "-logy"], "Blood & immune"),
    ("hematoma", "a localised collection of clotted blood", ["hemat/o", "-oma"], "Blood & immune"),
    ("hemolysis", "the breakdown of red blood cells", ["hem/o", "-lysis"], "Blood & immune"),
    ("hemostasis", "the stopping of bleeding", ["hem/o", "-stasis"], "Blood & immune"),
    ("hemorrhage", "an excessive escape of blood", ["hem/o", "-rrhage"], "Blood & immune"),
    ("septicemia", "the presence of infection in the blood", ["septic/o", "-emia"], "Blood & immune"),
    ("lymphadenopathy", "disease or enlargement of the lymph nodes", ["lymphaden/o", "-pathy"], "Blood & immune"),
    ("lymphoma", "a malignant tumour of lymphoid tissue", ["lymph/o", "-oma"], "Blood & immune"),
    ("phagocyte", "a cell that engulfs and digests debris", ["phag/o", "-cyte"], "Blood & immune"),
    ("erythropoiesis", "the formation of red blood cells", ["erythr/o", "-poiesis"], "Blood & immune"),
    ("thymectomy", "surgical removal of the thymus", ["thym/o", "-ectomy"], "Blood & immune"),

    # --- endocrine and metabolic
    ("adenoma", "a benign tumour of glandular tissue", ["aden/o", "-oma"], "Endocrine & metabolic"),
    ("adenopathy", "disease or enlargement of a gland", ["aden/o", "-pathy"], "Endocrine & metabolic"),
    ("thyroidectomy", "surgical removal of the thyroid gland", ["thyroid/o", "-ectomy"], "Endocrine & metabolic"),
    ("hyperthyroidism", "overactivity of the thyroid gland", ["hyper-", "thyroid/o", "-ism"], "Endocrine & metabolic"),
    ("hypothyroidism", "underactivity of the thyroid gland", ["hypo-", "thyroid/o", "-ism"], "Endocrine & metabolic"),
    ("hyperglycemia", "abnormally high blood sugar", ["hyper-", "glyc/o", "-emia"], "Endocrine & metabolic"),
    ("hypoglycemia", "abnormally low blood sugar", ["hypo-", "glyc/o", "-emia"], "Endocrine & metabolic"),
    ("glycosuria", "sugar in the urine", ["glycos/o", "-uria"], "Endocrine & metabolic"),
    ("ketoacidosis", "an abnormal condition of acid and ketones in the blood", ["ket/o", "acid/o", "-osis"], "Endocrine & metabolic"),
    ("hypercalcemia", "abnormally high blood calcium", ["hyper-", "calc/i", "-emia"], "Endocrine & metabolic"),
    ("hyponatremia", "abnormally low blood sodium", ["hypo-", "natr/o", "-emia"], "Endocrine & metabolic"),
    ("hyperkalemia", "abnormally high blood potassium", ["hyper-", "kal/i", "-emia"], "Endocrine & metabolic"),
    ("acromegaly", "enlargement of the extremities from excess growth hormone", ["acr/o", "-megaly"], "Endocrine & metabolic"),
    ("endocrinology", "the study of the endocrine glands", ["endo-", "crin/o", "-logy"], "Endocrine & metabolic"),
    ("adrenalectomy", "surgical removal of an adrenal gland", ["adrenal/o", "-ectomy"], "Endocrine & metabolic"),

    # --- reproductive and obstetric
    ("gynecology", "the study of the female reproductive system", ["gynec/o", "-logy"], "Reproductive & obstetric"),
    ("gynecomastia", "enlargement of breast tissue in a male", ["gynec/o", "mast/o", "-ia"], "Reproductive & obstetric"),
    ("hysterectomy", "surgical removal of the uterus", ["hyster/o", "-ectomy"], "Reproductive & obstetric"),
    ("hysteroscopy", "visual examination of the uterine cavity", ["hyster/o", "-scopy"], "Reproductive & obstetric"),
    ("oophorectomy", "surgical removal of an ovary", ["oophor/o", "-ectomy"], "Reproductive & obstetric"),
    ("salpingitis", "inflammation of a fallopian tube", ["salping/o", "-itis"], "Reproductive & obstetric"),
    ("salpingectomy", "surgical removal of a fallopian tube", ["salping/o", "-ectomy"], "Reproductive & obstetric"),
    ("endometriosis", "endometrial tissue growing outside the uterus", ["endo-", "metri/o", "-osis"], "Reproductive & obstetric"),
    ("endometritis", "inflammation of the lining of the uterus", ["endo-", "metr/o", "-itis"], "Reproductive & obstetric"),
    ("colposcopy", "visual examination of the vagina and cervix", ["colp/o", "-scopy"], "Reproductive & obstetric"),
    ("vaginitis", "inflammation of the vagina", ["vagin/o", "-itis"], "Reproductive & obstetric"),
    ("mastectomy", "surgical removal of a breast", ["mast/o", "-ectomy"], "Reproductive & obstetric"),
    ("mastitis", "inflammation of the breast", ["mast/o", "-itis"], "Reproductive & obstetric"),
    ("mammography", "x-ray imaging of the breast", ["mamm/o", "-graphy"], "Reproductive & obstetric"),
    ("orchiectomy", "surgical removal of a testis", ["orchi/o", "-ectomy"], "Reproductive & obstetric"),
    ("orchitis", "inflammation of a testis", ["orchi/o", "-itis"], "Reproductive & obstetric"),
    ("prostatitis", "inflammation of the prostate", ["prostat/o", "-itis"], "Reproductive & obstetric"),
    ("prostatectomy", "surgical removal of the prostate", ["prostat/o", "-ectomy"], "Reproductive & obstetric"),
    ("amenorrhea", "absence of menstruation", ["a-", "men/o", "-rrhea"], "Reproductive & obstetric"),
    ("dysmenorrhea", "painful menstruation", ["dys-", "men/o", "-rrhea"], "Reproductive & obstetric"),
    ("menorrhagia", "abnormally heavy menstrual bleeding", ["men/o", "-rrhagia"], "Reproductive & obstetric"),
    ("amniocentesis", "puncture of the amniotic sac to sample fluid", ["amni/o", "-centesis"], "Reproductive & obstetric"),
    ("episiotomy", "surgical incision of the perineum during delivery", ["episi/o", "-otomy"], "Reproductive & obstetric"),
    ("dystocia", "difficult or obstructed labour", ["dys-", "-tocia"], "Reproductive & obstetric"),
    ("galactorrhea", "inappropriate discharge of milk", ["galact/o", "-rrhea"], "Reproductive & obstetric"),
    ("neonatology", "the medical care of the newborn", ["neo-", "nat/o", "-logy"], "Reproductive & obstetric"),
    ("cryptorchidism", "failure of a testis to descend", ["crypt-", "orchid/o", "-ism"], "Reproductive & obstetric"),

    # --- eye and ENT
    ("ophthalmology", "the study of the eye", ["ophthalm/o", "-logy"], "Eye & ENT"),
    ("ophthalmoscope", "an instrument for examining the eye", ["ophthalm/o", "-scope"], "Eye & ENT"),
    ("conjunctivitis", "inflammation of the conjunctiva", ["conjunctiv/o", "-itis"], "Eye & ENT"),
    ("keratitis", "inflammation of the cornea", ["kerat/o", "-itis"], "Eye & ENT"),
    ("iridectomy", "surgical removal of part of the iris", ["irid/o", "-ectomy"], "Eye & ENT"),
    ("retinopathy", "disease of the retina", ["retin/o", "-pathy"], "Eye & ENT"),
    ("blepharitis", "inflammation of the eyelid", ["blephar/o", "-itis"], "Eye & ENT"),
    ("blepharoptosis", "drooping of the upper eyelid", ["blephar/o", "-ptosis"], "Eye & ENT"),
    ("dacryocystitis", "inflammation of the tear sac", ["dacry/o", "cyst/o", "-itis"], "Eye & ENT"),
    ("exophthalmos", "abnormal protrusion of the eyeball", ["exo-", "ophthalm/o", "-os"], "Eye & ENT"),
    ("otitis", "inflammation of the ear", ["ot/o", "-itis"], "Eye & ENT"),
    ("otoscope", "an instrument for examining the ear", ["ot/o", "-scope"], "Eye & ENT"),
    ("otorrhea", "discharge from the ear", ["ot/o", "-rrhea"], "Eye & ENT"),
    ("otolaryngology", "the study of the ear, nose and throat", ["ot/o", "laryng/o", "-logy"], "Eye & ENT"),
    ("myringotomy", "surgical incision of the eardrum", ["myring/o", "-otomy"], "Eye & ENT"),
    ("tympanoplasty", "surgical repair of the eardrum", ["tympan/o", "-plasty"], "Eye & ENT"),
    ("audiometry", "measurement of hearing", ["audi/o", "-metry"], "Eye & ENT"),
    ("anosmia", "loss of the sense of smell", ["an-", "-osmia"], "Eye & ENT"),

    # --- general and oncology
    ("cytology", "the study of cells", ["cyt/o", "-logy"], "General & colour roots"),
    ("histology", "the study of tissues", ["hist/o", "-logy"], "General & colour roots"),
    ("pathology", "the study of disease", ["path/o", "-logy"], "General & colour roots"),
    ("pathogenic", "capable of producing disease", ["path/o", "-genic"], "General & colour roots"),
    ("oncology", "the study of tumours", ["onc/o", "-logy"], "General & colour roots"),
    ("carcinoma", "a malignant tumour of epithelial tissue", ["carcin/o", "-oma"], "General & colour roots"),
    ("carcinogenic", "capable of causing cancer", ["carcin/o", "-genic"], "General & colour roots"),
    ("sarcoma", "a malignant tumour of connective tissue", ["sarc/o", "-oma"], "General & colour roots"),
    ("metastasis", "the spread of disease to a distant site", ["meta-", "-stasis"], "General & colour roots"),
    ("necrosis", "the death of tissue", ["necr/o", "-osis"], "General & colour roots"),
    ("cyanosis", "a bluish discolouration from poor oxygenation", ["cyan/o", "-osis"], "General & colour roots"),
    ("biopsy", "the removal of living tissue for examination", ["bi/o", "-opsy"], "General & colour roots"),
    ("prognosis", "the forecast of the course of a disease", ["pro-", "-gnosis"], "General & colour roots"),
    ("diagnosis", "the identification of a disease", ["dia-", "-gnosis"], "General & colour roots"),
    ("iatrogenic", "caused by medical examination or treatment", ["iatr/o", "-genic"], "General & colour roots"),
    ("idiopathic", "of unknown cause", ["idi/o", "-pathic"], "General & colour roots"),
    ("nosocomial", "originating in a hospital", ["nosocomi/o", "-al"], "General & colour roots"),
    ("hyperplasia", "an increase in the number of cells", ["hyper-", "-plasia"], "General & colour roots"),
    ("hypertrophy", "an increase in the size of cells", ["hyper-", "-trophy"], "General & colour roots"),
    ("atrophy", "wasting away from lack of use or nourishment", ["a-", "-trophy"], "General & colour roots"),
    ("dysplasia", "abnormal or disordered development of cells", ["dys-", "-plasia"], "General & colour roots"),
    ("aplasia", "failure of an organ or tissue to develop", ["a-", "-plasia"], "General & colour roots"),
    ("radiography", "imaging using x-rays", ["radi/o", "-graphy"], "General & colour roots"),
    ("sonography", "imaging using sound waves", ["son/o", "-graphy"], "General & colour roots"),
    ("pyrexia", "fever", ["pyr/o", "-exia"], "General & colour roots"),
    ("hypothermia", "abnormally low body temperature", ["hypo-", "therm/o", "-ia"], "General & colour roots"),
    ("geriatrics", "the branch of medicine dealing with old age", ["ger/o", "-iatrics"], "General & colour roots"),
    ("pediatrics", "the branch of medicine dealing with children", ["ped/o", "-iatrics"], "General & colour roots"),
    ("antipyretic", "an agent that reduces fever", ["anti-", "pyret/o", "-ic"], "General & colour roots"),
    ("antibiotic", "an agent that acts against bacterial life", ["anti-", "bi/o", "-tic"], "General & colour roots"),
    ("anticoagulant", "an agent that prevents clotting", ["anti-", "coagul/o", "-ant"], "General & colour roots"),
]

# Roots used only by the terms above; merged into the drillable element list.
EXTRA_ROOTS += [
    ("metri/o", "uterus", "G", "Reproductive & obstetric", "The -i- stem: endometriosis, endometrium."),
    ("por/o", "pore, passage, cavity", "G", "Musculoskeletal", "Gk poros. Osteoporosis — bone full of pores."),
    ("lamin/o", "lamina, thin plate of vertebral bone", "L", "Musculoskeletal", "L lamina. Laminectomy relieves cord compression."),
    ("myos/o", "muscle", "G", "Musculoskeletal", "The stem seen in myositis."),
    ("cellul/o", "cell; small compartment", "L", "Integumentary", "L cellula. Cellulitis, cellular."),
    ("septic/o", "infection, putrefaction", "G", "Blood & immune", "Gk septikos. Septicaemia, septic shock."),
    ("glycos/o", "sugar, glucose", "G", "Endocrine & metabolic", "The stem used before -uria: glycosuria."),
    ("acid/o", "acid, acidity", "L", "Endocrine & metabolic", "L acidus. Acidosis, ketoacidosis."),
    ("thyroid/o", "thyroid gland", "G", "Endocrine & metabolic", "The full stem: thyroidectomy, hypothyroidism."),
    ("adrenal/o", "adrenal gland", "L", "Endocrine & metabolic", "Adrenalectomy, adrenal insufficiency."),
    ("orchid/o", "testis", "G", "Reproductive & obstetric", "The -id- stem: orchidopexy, cryptorchidism."),
    ("idi/o", "individual, one's own, unknown", "G", "General & colour roots", "Gk idios. Idiopathic — arising on its own, cause unknown."),
    ("nosocomi/o", "hospital", "G", "General & colour roots", "Gk nosokomeion. Nosocomial infection — hospital-acquired."),
    ("pyret/o", "fever", "G", "General & colour roots", "Gk pyretos. Antipyretic."),
    ("ger/o", "old age", "G", "General & colour roots", "Gk geras. Geriatrics, gerontology."),
]

EXTRA_SUFFIXES += [
    ("-lepsy", "seizure, sudden attack", "G", "Suffixes: conditions & disease", "Gk lepsis 'a seizing'. Epilepsy, narcolepsy."),
    ("-rrhage", "bursting forth of blood", "G", "Suffixes: conditions & disease", "The noun beside -rrhagia: haemorrhage."),
    ("-opsy", "process of viewing, examination", "G", "Suffixes: procedures & surgery", "Gk opsis 'sight'. Biopsy, autopsy, necropsy."),
    ("-gnosis", "knowledge, recognition", "G", "Suffixes: procedures & surgery", "Gk gnosis. Diagnosis (through-knowing), prognosis (fore-knowing)."),
    ("-pathic", "pertaining to disease", "G", "Suffixes: conditions & disease", "Idiopathic, neuropathic."),
    ("-exia", "condition", "G", "Suffixes: conditions & disease", "Pyrexia, anorexia, cachexia."),
    ("-tic", "pertaining to", "G", "Suffixes: specialties & study", "Antibiotic, diagnostic, necrotic."),
    ("-ant", "agent, one that does", "L", "Suffixes: specialties & study", "Anticoagulant, stimulant, decongestant."),
    ("-us", "singular noun ending", "L", "Plurals & word forms", "Hydrocephalus, bronchus, thrombus — plural in -i."),
    ("-is", "singular noun ending", "G", "Plurals & word forms", "Epidermis, diagnosis, pubis."),
    ("-a", "singular noun ending", "L", "Plurals & word forms", "Vertebra, scapula, bursa — plural in -ae."),
    ("-os", "Greek noun ending", "G", "Plurals & word forms", "Exophthalmos."),
]

# (singular, plural, rule, meaning)
PLURALS = [
    ("vertebra", "vertebrae", "-a → -ae (Latin, 1st declension)", "a bone of the spinal column"),
    ("scapula", "scapulae", "-a → -ae (Latin)", "the shoulder blade"),
    ("bursa", "bursae", "-a → -ae (Latin)", "a fluid-filled sac cushioning a joint"),
    ("sclera", "sclerae", "-a → -ae (Latin)", "the white outer coat of the eyeball"),
    ("conjunctiva", "conjunctivae", "-a → -ae (Latin)", "the membrane lining the eyelid and eye"),
    ("axilla", "axillae", "-a → -ae (Latin)", "the armpit"),
    ("lamina", "laminae", "-a → -ae (Latin)", "a thin plate of vertebral bone"),
    ("thrombus", "thrombi", "-us → -i (Latin, 2nd declension)", "a blood clot within a vessel"),
    ("bronchus", "bronchi", "-us → -i (Latin)", "a main airway of the lung"),
    ("nucleus", "nuclei", "-us → -i (Latin)", "the control centre of a cell"),
    ("alveolus", "alveoli", "-us → -i (Latin)", "an air sac of the lung"),
    ("embolus", "emboli", "-us → -i (Latin)", "a plug carried in the bloodstream"),
    ("calculus", "calculi", "-us → -i (Latin)", "a stone, such as a kidney stone"),
    ("bacillus", "bacilli", "-us → -i (Latin)", "a rod-shaped bacterium"),
    ("villus", "villi", "-us → -i (Latin)", "a small projection of the intestinal lining"),
    ("meniscus", "menisci", "-us → -i (Latin)", "a crescent of cartilage in the knee"),
    ("ovum", "ova", "-um → -a (Latin, neuter)", "an egg cell"),
    ("bacterium", "bacteria", "-um → -a (Latin)", "a single-celled microorganism"),
    ("atrium", "atria", "-um → -a (Latin)", "an upper chamber of the heart"),
    ("septum", "septa", "-um → -a (Latin)", "a dividing wall between two cavities"),
    ("ilium", "ilia", "-um → -a (Latin)", "the flared upper part of the hip bone"),
    ("labium", "labia", "-um → -a (Latin)", "a lip or lip-like structure"),
    ("diverticulum", "diverticula", "-um → -a (Latin)", "an outpouching of the bowel wall"),
    ("ganglion", "ganglia", "-on → -a (Greek)", "a cluster of nerve cell bodies"),
    ("spermatozoon", "spermatozoa", "-on → -a (Greek)", "a mature male sex cell"),
    ("phenomenon", "phenomena", "-on → -a (Greek)", "an observed fact or event"),
    ("diagnosis", "diagnoses", "-is → -es (Greek)", "the identification of a disease"),
    ("prognosis", "prognoses", "-is → -es (Greek)", "the forecast of a disease's course"),
    ("metastasis", "metastases", "-is → -es (Greek)", "a secondary tumour distant from the original"),
    ("anastomosis", "anastomoses", "-is → -es (Greek)", "a surgical join between two tubular structures"),
    ("prosthesis", "prostheses", "-is → -es (Greek)", "an artificial replacement for a body part"),
    ("pelvis", "pelves", "-is → -es (Latin)", "the bony basin at the base of the trunk"),
    ("testis", "testes", "-is → -es (Latin)", "the male gonad"),
    ("epiphysis", "epiphyses", "-is → -es (Greek)", "the growing end of a long bone"),
    ("symphysis", "symphyses", "-is → -es (Greek)", "a joint where bones are joined by cartilage"),
    ("apex", "apices", "-ex → -ices (Latin)", "the tip or pointed end of a structure"),
    ("cortex", "cortices", "-ex → -ices (Latin)", "the outer layer of an organ"),
    ("index", "indices", "-ex → -ices (Latin)", "a pointer or measure"),
    ("appendix", "appendices", "-ix → -ices (Latin)", "the blind-ended tube off the caecum"),
    ("varix", "varices", "-ix → -ices (Latin)", "an abnormally dilated vein"),
    ("cervix", "cervices", "-ix → -ices (Latin)", "a neck-like part, especially of the uterus"),
    ("foramen", "foramina", "-men → -mina (Latin)", "a natural opening through a bone"),
    ("lumen", "lumina", "-men → -mina (Latin)", "the interior space of a tubular structure"),
    ("stoma", "stomata", "-ma → -mata (Greek)", "a mouth-like opening"),
    ("carcinoma", "carcinomata", "-ma → -mata (Greek); carcinomas is also accepted", "a malignant epithelial tumour"),
    ("adenoma", "adenomata", "-ma → -mata (Greek); adenomas is also accepted", "a benign glandular tumour"),
    ("phalanx", "phalanges", "-nx → -nges (Greek)", "a bone of a finger or toe"),
    ("larynx", "larynges", "-nx → -nges (Greek)", "the voice box"),
    ("pharynx", "pharynges", "-nx → -nges (Greek)", "the throat"),
    ("meninx", "meninges", "-nx → -nges (Greek)", "one of the membranes covering the brain"),
    ("coccus", "cocci", "-us → -i (Latin)", "a spherical bacterium"),
    ("fungus", "fungi", "-us → -i (Latin)", "a member of the fungal kingdom"),
    ("serum", "sera", "-um → -a (Latin)", "the fluid part of blood after clotting"),
    ("speculum", "specula", "-um → -a (Latin)", "an instrument for opening a body passage"),
    ("crisis", "crises", "-is → -es (Greek)", "a turning point in the course of a disease"),
    ("neurosis", "neuroses", "-is → -es (Greek)", "a mild mental disorder"),
    ("psychosis", "psychoses", "-is → -es (Greek)", "a severe disorder with loss of contact with reality"),
]

# (term_a, gloss_a, term_b, gloss_b, note, lesson)
CONFUSABLES = [
    ("ilium", "the flared upper bone of the pelvis", "ileum", "the final part of the small intestine",
     "Both from Latin. Remember the bone has an i in the middle like 'hip', or that ilEum is Enteric — intestinal.",
     "Confusable pairs"),
    ("-otomy", "cutting into, an incision", "-ostomy", "creating a lasting opening",
     "A tracheotomy is cut and closed; a tracheostomy leaves a stoma. Gk stoma means 'mouth'.",
     "Confusable pairs"),
    ("-ectomy", "surgical removal of a structure", "-ostomy", "creating a lasting opening",
     "Colectomy takes the colon out; colostomy brings it to the skin as an opening.",
     "Confusable pairs"),
    ("dysphagia", "difficulty swallowing", "dysphasia", "impaired speech",
     "-phagia is Gk phagein 'to eat'; -phasia is Gk phasis 'speech'. One letter, and a completely different lesion.",
     "Confusable pairs"),
    ("hydr/o", "water, fluid", "hidr/o", "sweat",
     "Hydronephrosis is fluid in the kidney; hyperhidrosis is excessive sweating.",
     "Confusable pairs"),
    ("py/o", "pus", "pyr/o", "fever, heat",
     "Pyuria is pus in the urine; pyrexia is fever. The r is the tell.",
     "Confusable pairs"),
    ("arteriosclerosis", "hardening and loss of elasticity of artery walls",
     "atherosclerosis", "narrowing of arteries by fatty plaque",
     "Atherosclerosis (Gk athere 'gruel') is one specific cause of arteriosclerosis, not a synonym for it.",
     "Confusable pairs"),
    ("ureter", "the tube from kidney to bladder", "urethra", "the tube from bladder to outside",
     "UreTER is the upper tube; ureTHra is the one that exits. Ureteroscopy and urethritis are different territories.",
     "Confusable pairs"),
    ("hyper-", "above normal, excessive", "hypo-", "below normal, deficient",
     "Hyperglycaemia is too much blood sugar, hypoglycaemia too little. The commonest and most dangerous prefix mix-up.",
     "Confusable pairs"),
    ("-emia", "a condition of the blood", "-uria", "a condition of the urine",
     "Haematuria is blood in the urine; uraemia is urea in the blood. The two are frequently swapped.",
     "Confusable pairs"),
    ("hypertrophy", "increase in cell SIZE", "hyperplasia", "increase in cell NUMBER",
     "Both enlarge an organ. Prostatic hyperplasia adds cells; cardiac hypertrophy enlarges existing ones.",
     "Confusable pairs"),
    ("arteri/o", "artery", "arthr/o", "joint",
     "Arteriography images vessels; arthroscopy looks inside a joint. The th is the joint.",
     "Confusable pairs"),
    ("-algia", "pain", "-plegia", "paralysis",
     "Neuralgia hurts; hemiplegia cannot move. Both are Greek, both are common in exams.",
     "Confusable pairs"),
    ("melena", "black tarry stool from digested blood", "melanoma", "a malignant tumour of pigment cells",
     "Both from Gk melas 'black' — one describes stool colour, the other a skin cancer.",
     "Confusable pairs"),
    ("prostate", "the male gland below the bladder", "prostrate", "lying face down",
     "Only the second r differs. The gland has no r after the first t.",
     "Confusable pairs"),
    ("perineal", "pertaining to the perineum", "peroneal", "pertaining to the fibular side of the leg",
     "A perineal tear follows childbirth; a peroneal nerve palsy causes foot drop.",
     "Confusable pairs"),
    ("mucus", "the secretion (a noun)", "mucous", "pertaining to mucus (an adjective)",
     "The mucous membrane produces mucus. The -ous spelling is always the adjective.",
     "Confusable pairs"),
    ("-cyte", "a cell", "-cyst", "a sac or bladder",
     "Leukocyte is a white cell; cholecystitis is inflammation of the gallbladder sac.",
     "Confusable pairs"),
    ("aphasia", "loss of speech", "aphagia", "inability to swallow",
     "The same s/g distinction as dysphasia and dysphagia.",
     "Confusable pairs"),
    ("osteoblast", "a cell that BUILDS bone", "osteoclast", "a cell that BREAKS DOWN bone",
     "Gk blastos 'sprout' builds; klastos 'broken' resorbs. B for build, C for consume.",
     "Confusable pairs"),
]

# (term, meaning, origin, note)
ANATOMICAL = [
    ("superior", "above, toward the head", "L", "L superus. The heart is superior to the diaphragm."),
    ("inferior", "below, toward the feet", "L", "L inferus. The stomach is inferior to the lungs."),
    ("anterior", "toward the front", "L", "L ante 'before'. Synonym: ventral."),
    ("posterior", "toward the back", "L", "L post 'after'. Synonym: dorsal."),
    ("ventral", "pertaining to the belly side", "L", "L venter 'belly'."),
    ("dorsal", "pertaining to the back", "L", "L dorsum 'back'."),
    ("medial", "toward the midline", "L", "L medius 'middle'. The ulna is medial to the radius."),
    ("lateral", "away from the midline, toward the side", "L", "L latus 'side'."),
    ("proximal", "nearer to the trunk or point of origin", "L", "L proximus 'nearest'. The elbow is proximal to the wrist."),
    ("distal", "farther from the trunk or point of origin", "L", "L distare 'to stand apart'."),
    ("superficial", "near the surface", "L", "L superficies 'surface'."),
    ("deep", "farther from the surface", "L", "The counterpart of superficial."),
    ("supine", "lying face up", "L", "L supinus. Remember: supine is on your spine."),
    ("prone", "lying face down", "L", "L pronus 'bent forward'."),
    ("sagittal", "the plane dividing the body into left and right", "L", "L sagitta 'arrow'."),
    ("coronal", "the plane dividing the body into front and back", "L", "L corona 'crown'. Also called frontal."),
    ("transverse", "the plane dividing the body into upper and lower", "L", "L transversus. Also called axial or horizontal."),
    ("unilateral", "affecting one side", "L", "uni- + later/o + -al."),
    ("bilateral", "affecting both sides", "L", "bi- + later/o + -al."),
    ("ipsilateral", "on the same side", "L", "L ipse 'self'. The same side as the lesion."),
    ("contralateral", "on the opposite side", "L", "contra- + later/o + -al."),
    ("flexion", "bending, decreasing the angle of a joint", "L", "L flectere 'to bend'."),
    ("extension", "straightening, increasing the angle of a joint", "L", "L extendere 'to stretch out'."),
    ("abduction", "movement away from the midline", "L", "ab- 'away' + ducere 'to lead'."),
    ("adduction", "movement toward the midline", "L", "ad- 'toward' + ducere. Adduction adds to the body."),
    ("pronation", "turning the palm downward", "L", "The forearm rotation that faces the palm down."),
    ("supination", "turning the palm upward", "L", "As if holding a bowl of soup."),
    ("afferent", "carrying toward a centre", "L", "L ad + ferre 'to carry'. Sensory nerves are afferent."),
    ("efferent", "carrying away from a centre", "L", "L ex + ferre. Motor nerves are efferent."),
    ("lumen", "the interior space of a tube", "L", "L lumen 'light, opening'."),
    ("viscera", "the internal organs", "L", "L viscus. Visceral pain is poorly localised."),
    ("parietal", "pertaining to the wall of a cavity", "L", "L paries 'wall'. Contrast visceral, which covers the organ."),
    ("cephalad", "toward the head", "G", "Gk kephale + -ad 'toward'."),
    ("caudal", "toward the tail or lower end", "L", "L cauda 'tail'."),
    ("palmar", "pertaining to the palm of the hand", "L", "L palma."),
    ("plantar", "pertaining to the sole of the foot", "L", "L planta. Plantar fasciitis."),
]

# (abbreviation, latin, meaning)
PRESCRIPTION = [
    ("b.i.d.", "bis in die", "twice a day"),
    ("t.i.d.", "ter in die", "three times a day"),
    ("q.i.d.", "quater in die", "four times a day"),
    ("q.d.", "quaque die", "every day"),
    ("q.h.", "quaque hora", "every hour"),
    ("p.r.n.", "pro re nata", "as needed, as the situation arises"),
    ("p.o.", "per os", "by mouth"),
    ("p.r.", "per rectum", "by the rectum"),
    ("a.c.", "ante cibum", "before meals"),
    ("p.c.", "post cibum", "after meals"),
    ("h.s.", "hora somni", "at bedtime"),
    ("stat", "statim", "immediately, at once"),
    ("NPO", "nil per os", "nothing by mouth"),
    ("Rx", "recipe", "take, prescription"),
    ("Sig.", "signa", "label, write on the label"),
    ("q.s.", "quantum satis", "a sufficient quantity"),
    ("ad lib.", "ad libitum", "freely, as desired"),
    ("gtt.", "guttae", "drops"),
    ("o.d.", "oculus dexter", "right eye"),
    ("o.s.", "oculus sinister", "left eye"),
    ("o.u.", "oculi uterque", "both eyes"),
    ("a.d.", "auris dextra", "right ear"),
    ("a.s.", "auris sinistra", "left ear"),
    ("i.m.", "intra musculum", "into the muscle, intramuscular"),
    ("i.v.", "intra venam", "into the vein, intravenous"),
    ("in vivo", "in vivo", "in the living organism"),
    ("in vitro", "in vitro", "in glass, in the laboratory"),
    ("in situ", "in situ", "in its original place"),
    ("post mortem", "post mortem", "after death"),
    ("per se", "per se", "by itself, intrinsically"),
]

# Clinical sentences with the target term wrapped in braces.
CLOZE = [
    ("gastritis", "Endoscopy showed diffuse {gastritis} without ulceration."),
    ("hepatomegaly", "On palpation the liver edge was 4 cm below the costal margin, confirming {hepatomegaly}."),
    ("splenomegaly", "Massive {splenomegaly} in a young adult should raise the possibility of a haematological malignancy."),
    ("tachycardia", "She was febrile with a {tachycardia} of 130 beats per minute."),
    ("bradycardia", "The athlete's resting {bradycardia} of 48 was a normal finding for him."),
    ("dyspnea", "He described {dyspnea} on climbing a single flight of stairs."),
    ("orthopnea", "Needing three pillows at night is a classic history of {orthopnea}."),
    ("hemoptysis", "Any patient over 40 with {hemoptysis} needs a chest x-ray."),
    ("dysphagia", "Progressive {dysphagia} for solids then liquids suggests an obstructing lesion."),
    ("hematemesis", "The patient presented with {hematemesis} and melaena from a bleeding ulcer."),
    ("hematuria", "Painless visible {hematuria} is a red flag for urinary tract malignancy."),
    ("dysuria", "Burning {dysuria} and frequency suggested a simple urinary tract infection."),
    ("oliguria", "Postoperative {oliguria} of under 0.5 ml/kg/hour prompted a fluid review."),
    ("polyuria", "The triad of {polyuria}, polydipsia and weight loss suggests new diabetes."),
    ("nocturia", "Increasing {nocturia} in an older man may reflect prostatic enlargement."),
    ("jaundice", "Painless {jaundice} with a palpable gallbladder is a worrying combination."),
    ("cyanosis", "Central {cyanosis} was visible on the tongue and lips."),
    ("pyrexia", "He remained in {pyrexia} despite 48 hours of antibiotics."),
    ("hemiplegia", "The infarct in the left middle cerebral artery left a right-sided {hemiplegia}."),
    ("aphasia", "A dominant hemisphere stroke may produce {aphasia} as well as weakness."),
    ("paresthesia", "She reported {paresthesia} in a glove-and-stocking distribution."),
    ("anesthesia", "The procedure was performed under general {anesthesia}."),
    ("neuropathy", "Long-standing diabetes is the commonest cause of peripheral {neuropathy}."),
    ("meningitis", "Neck stiffness, photophobia and fever point to {meningitis}."),
    ("appendicitis", "Migratory right iliac fossa pain is the classic history of {appendicitis}."),
    ("peritonitis", "Board-like abdominal rigidity indicates {peritonitis}."),
    ("cholecystitis", "Right upper quadrant pain after a fatty meal suggested {cholecystitis}."),
    ("cholelithiasis", "Ultrasound confirmed {cholelithiasis} with a thickened gallbladder wall."),
    ("pancreatitis", "A serum amylase three times the upper limit supports acute {pancreatitis}."),
    ("diverticulitis", "Left iliac fossa pain with fever in an older patient suggests {diverticulitis}."),
    ("nephrolithiasis", "Severe loin-to-groin colic is typical of {nephrolithiasis}."),
    ("pyelonephritis", "Fever and loin tenderness with pyuria indicate {pyelonephritis}."),
    ("hydronephrosis", "The obstructing stone had caused {hydronephrosis} on the affected side."),
    ("cystitis", "Uncomplicated {cystitis} in a young woman is usually treated with a short antibiotic course."),
    ("anemia", "Iron deficiency {anemia} in an older man warrants investigation of the gut."),
    ("leukemia", "The blood film showed blast cells, raising the suspicion of acute {leukemia}."),
    ("thrombocytopenia", "Spontaneous bruising prompted a platelet count, which confirmed {thrombocytopenia}."),
    ("thrombosis", "A swollen, tender calf raises the possibility of deep vein {thrombosis}."),
    ("lymphadenopathy", "Painless cervical {lymphadenopathy} persisting beyond six weeks needs investigation."),
    ("hyperglycemia", "Persistent {hyperglycemia} despite treatment prompted a review of his insulin."),
    ("hypoglycemia", "Sweating, tremor and confusion resolved after treating the {hypoglycemia}."),
    ("hyponatremia", "The patient's confusion was attributed to profound {hyponatremia}."),
    ("hyperkalemia", "Peaked T waves on the ECG suggested {hyperkalemia}."),
    ("hypothyroidism", "Fatigue, cold intolerance and weight gain suggested {hypothyroidism}."),
    ("acromegaly", "Enlarging hands, coarse features and a prominent jaw suggested {acromegaly}."),
    ("osteoporosis", "A low-trauma vertebral fracture prompted assessment for {osteoporosis}."),
    ("osteoarthritis", "Pain worse with use and better with rest is typical of {osteoarthritis}."),
    ("osteomyelitis", "A non-healing ulcer probing to bone raises the suspicion of {osteomyelitis}."),
    ("arthralgia", "She reported migratory {arthralgia} affecting several joints."),
    ("scoliosis", "The adolescent's {scoliosis} was detected on the forward-bend test."),
    ("cellulitis", "A spreading area of warm erythema was diagnosed as {cellulitis}."),
    ("melanoma", "An irregular, asymmetrical pigmented lesion was excised and confirmed as {melanoma}."),
    ("conjunctivitis", "A red eye with discharge but normal vision suggests {conjunctivitis}."),
    ("otitis", "The child's ear pain and a bulging drum indicated acute {otitis} media."),
    ("metastasis", "Staging imaging revealed hepatic {metastasis}."),
    ("prognosis", "The {prognosis} was discussed frankly with the family."),
    ("biopsy", "A core {biopsy} was taken to establish the tissue diagnosis."),
    ("iatrogenic", "The pneumothorax was {iatrogenic}, following central line insertion."),
    ("nosocomial", "The infection was {nosocomial}, acquired more than 48 hours after admission."),
    ("idiopathic", "No cause was found, and the condition was labelled {idiopathic}."),
]

# Terms used only in cloze sentences; defined so the deck can gloss them.
CLOZE_ONLY = [
    ("jaundice", "yellow discolouration of skin and eyes from bilirubin", "Gastrointestinal",
     "From French jaune 'yellow'. The Greek-derived synonym is icterus."),
    ("diverticulitis", "inflammation of an outpouching of the bowel wall", "Gastrointestinal",
     "diverticul/o + -itis. Diverticulosis is the presence of them; diverticulitis is inflammation."),
]
