#!/usr/bin/env python3
"""Curated word-building elements for the medical terminology trainer.

Each element is (form, meaning, origin, lesson, note), where

  form    the element as students learn it: "hyper-", "cardi/o", "-itis".
          The slash marks the combining vowel; hyphens mark the attachment side.
  origin  "G" (Greek) or "L" (Latin). This matters clinically, not just
          historically: the Greek form usually builds the pathology/surgery word
          and the Latin form the plain anatomical one (nephrectomy vs renal
          artery), which is why the doublet drill exists.
  lesson  the filter group the entry appears under.
  note    etymology / usage, shown in the element panel after answering.

DOUBLETS pairs the Greek and Latin roots for the same structure; the generator
links them in both directions and fails if either side is missing.
"""

# ---------------------------------------------------------------- prefixes

PREFIXES = [
    # --- number, size and amount
    ("mono-", "one, single", "G", "Prefixes: number & size", "Gk monos 'alone'. Mononucleosis, monocyte."),
    ("uni-", "one", "L", "Prefixes: number & size", "L unus. Unilateral — one side only."),
    ("bi-", "two, twice", "L", "Prefixes: number & size", "L bis. Bilateral, bicuspid."),
    ("di-", "two", "G", "Prefixes: number & size", "Gk dis. Diplegia, diplopia (double vision)."),
    ("tri-", "three", "G/L", "Prefixes: number & size", "Same in both. Tricuspid, trimester."),
    ("quadri-", "four", "L", "Prefixes: number & size", "L quattuor. Quadriplegia."),
    ("tetra-", "four", "G", "Prefixes: number & size", "Gk tettares. Tetralogy of Fallot."),
    ("hemi-", "half", "G", "Prefixes: number & size", "Gk hemi. Hemiplegia — one side of the body."),
    ("semi-", "half, partly", "L", "Prefixes: number & size", "L semi. Semilunar valve — half-moon shaped."),
    ("poly-", "many, much", "G", "Prefixes: number & size", "Gk polys. Polyuria, polycystic."),
    ("multi-", "many", "L", "Prefixes: number & size", "L multus. Multipara, multifocal."),
    ("oligo-", "few, scanty", "G", "Prefixes: number & size", "Gk oligos. Oliguria — scanty urine output."),
    ("pan-", "all, entire", "G", "Prefixes: number & size", "Gk pas/pan. Pancytopenia — all cell lines low."),
    ("macro-", "large, long", "G", "Prefixes: number & size", "Gk makros. Macrocytic, macroglossia."),
    ("micro-", "small", "G", "Prefixes: number & size", "Gk mikros. Microcephaly, microscope."),
    ("megalo-", "enlarged, great", "G", "Prefixes: number & size", "Gk megas. Also the suffix -megaly."),
    ("hyper-", "above normal, excessive", "G", "Prefixes: negation & degree", "Gk hyper 'over'. Hypertension, hyperglycaemia."),
    ("hypo-", "below normal, deficient; under", "G", "Prefixes: negation & degree", "Gk hypo 'under'. Hypoglycaemia; also positional — hypodermic."),
    ("iso-", "equal, same", "G", "Prefixes: number & size", "Gk isos. Isotonic, isometric."),
    ("hetero-", "different, other", "G", "Prefixes: negation & degree", "Gk heteros. Heterogeneous."),
    ("homo-", "same, alike", "G", "Prefixes: negation & degree", "Gk homos. Homeostasis, homograft."),
    ("primi-", "first", "L", "Prefixes: number & size", "L primus. Primigravida — first pregnancy."),
    ("nulli-", "none", "L", "Prefixes: number & size", "L nullus. Nullipara — has borne no children."),

    # --- position and direction
    ("ab-", "away from", "L", "Prefixes: position & direction", "L ab. Abduction moves a limb away from the midline."),
    ("ad-", "toward, near", "L", "Prefixes: position & direction", "L ad. Adduction adds the limb back to the midline."),
    ("ante-", "before, in front of", "L", "Prefixes: position & direction", "L ante. Antepartum, anteflexion."),
    ("pre-", "before, in front of", "L", "Prefixes: position & direction", "L prae. Prenatal, preoperative."),
    ("post-", "after, behind", "L", "Prefixes: position & direction", "L post. Postpartum, postprandial (after a meal)."),
    ("retro-", "backward, behind", "L", "Prefixes: position & direction", "L retro. Retroperitoneal, retroversion."),
    ("circum-", "around", "L", "Prefixes: position & direction", "L circum. Circumcision, circumduction."),
    ("peri-", "around, surrounding", "G", "Prefixes: position & direction", "Gk peri. Pericardium — the sac around the heart."),
    ("endo-", "within, inner", "G", "Prefixes: position & direction", "Gk endon. Endoscopy, endocardium."),
    ("intra-", "within, inside", "L", "Prefixes: position & direction", "L intra. Intravenous, intramuscular."),
    ("inter-", "between", "L", "Prefixes: position & direction", "L inter. Intercostal — between the ribs."),
    ("extra-", "outside of, beyond", "L", "Prefixes: position & direction", "L extra. Extracellular, extrahepatic."),
    ("exo-", "outside, outward", "G", "Prefixes: position & direction", "Gk exo. Exophthalmos — bulging eyes."),
    ("ecto-", "outer, outside", "G", "Prefixes: position & direction", "Gk ektos. Ectopic — out of the normal place."),
    ("meso-", "middle", "G", "Prefixes: position & direction", "Gk mesos. Mesoderm, mesentery."),
    ("epi-", "upon, on, above", "G", "Prefixes: position & direction", "Gk epi. Epidermis, epigastric, epidural."),
    ("sub-", "under, below", "L", "Prefixes: position & direction", "L sub. Subcutaneous, sublingual."),
    ("infra-", "beneath, below", "L", "Prefixes: position & direction", "L infra. Infraorbital."),
    ("supra-", "above, over", "L", "Prefixes: position & direction", "L supra. Suprapubic, suprarenal."),
    ("trans-", "across, through", "L", "Prefixes: position & direction", "L trans. Transdermal, transurethral."),
    ("dia-", "through, complete", "G", "Prefixes: position & direction", "Gk dia. Diarrhoea, dialysis, diagnosis."),
    ("para-", "beside, near; abnormal", "G", "Prefixes: position & direction", "Gk para. Parathyroid (beside the thyroid); paraesthesia (abnormal sensation)."),
    ("meta-", "beyond, change, after", "G", "Prefixes: position & direction", "Gk meta. Metastasis, metacarpal, metabolism."),
    ("ana-", "up, apart, again", "G", "Prefixes: position & direction", "Gk ana. Anatomy — literally 'cutting up'."),
    ("cata-", "down, under", "G", "Prefixes: position & direction", "Gk kata. Catabolism — breaking down."),
    ("ex-", "out, away from", "L", "Prefixes: position & direction", "L ex. Excision, exhalation."),
    ("de-", "down, from; removal of", "L", "Prefixes: negation & degree", "L de. Dehydration, defibrillation."),
    ("syn-", "together, with", "G", "Prefixes: position & direction", "Gk syn; becomes sym- before b, m, p. Syndrome, symphysis."),
    ("con-", "with, together", "L", "Prefixes: position & direction", "L cum. Congenital — present at birth."),
    ("juxta-", "near, beside", "L", "Prefixes: position & direction", "L iuxta. Juxtaglomerular apparatus."),
    ("contra-", "against, opposite", "L", "Prefixes: negation & degree", "L contra. Contraindication, contralateral."),
    ("anti-", "against, opposing", "G", "Prefixes: negation & degree", "Gk anti. Antibiotic, antipyretic, anticoagulant."),
    ("pro-", "before, forward; in favour of", "G/L", "Prefixes: position & direction", "Prodrome — the symptoms running before the illness."),

    # --- negation, quality and rate
    ("a-", "without, absence of", "G", "Prefixes: negation & degree", "Gk a-. Becomes an- before a vowel: apnoea, but anaemia."),
    ("an-", "without, absence of", "G", "Prefixes: negation & degree", "The form of a- used before a vowel or h: anuria, anhidrosis."),
    ("dys-", "painful, difficult, abnormal", "G", "Prefixes: negation & degree", "Gk dys. Dyspnoea, dysuria, dysplasia."),
    ("eu-", "good, normal, easy", "G", "Prefixes: negation & degree", "Gk eu. Euthyroid, eupnoea — the counterpart of dys-."),
    ("brady-", "slow", "G", "Prefixes: negation & degree", "Gk bradys. Bradycardia — under 60 beats per minute."),
    ("tachy-", "fast, rapid", "G", "Prefixes: negation & degree", "Gk tachys. Tachycardia, tachypnoea."),
    ("mal-", "bad, poor", "L", "Prefixes: negation & degree", "L malus. Malabsorption, malignant, malaise."),
    ("neo-", "new", "G", "Prefixes: negation & degree", "Gk neos. Neonate, neoplasm."),
    ("auto-", "self", "G", "Prefixes: negation & degree", "Gk autos. Autoimmune, autograft, autolysis."),
    ("allo-", "other, different", "G", "Prefixes: negation & degree", "Gk allos. Allograft — tissue from another person."),
    ("pseudo-", "false", "G", "Prefixes: negation & degree", "Gk pseudes. Pseudocyst, pseudohypertrophy."),
    ("ortho-", "straight, correct, upright", "G", "Prefixes: negation & degree", "Gk orthos. Orthopaedics, orthopnoea."),
    ("crypt-", "hidden", "G", "Prefixes: negation & degree", "Gk kryptos. Cryptorchidism — an undescended testis."),
    ("steno-", "narrow", "G", "Prefixes: negation & degree", "Gk stenos. Also the suffix -stenosis."),
    ("re-", "again, back", "L", "Prefixes: negation & degree", "L re. Resection, relapse, remission."),
]

# ---------------------------------------------------------------- suffixes

SUFFIXES = [
    # --- conditions and disease
    ("-itis", "inflammation", "G", "Suffixes: conditions & disease", "Gk -itis. The commonest suffix in clinical medicine: appendicitis, arthritis."),
    ("-osis", "abnormal condition; increase in number", "G", "Suffixes: conditions & disease", "Gk -osis. Cyanosis, leukocytosis — not necessarily inflammatory."),
    ("-iasis", "abnormal condition, presence of", "G", "Suffixes: conditions & disease", "Gk -iasis. Usually a condition caused by something: cholelithiasis, psoriasis."),
    ("-pathy", "disease, disorder", "G", "Suffixes: conditions & disease", "Gk pathos 'suffering'. Neuropathy, cardiomyopathy."),
    ("-algia", "pain", "G", "Suffixes: conditions & disease", "Gk algos. Neuralgia, myalgia, arthralgia."),
    ("-dynia", "pain", "G", "Suffixes: conditions & disease", "Gk odyne. Rarer than -algia: mastodynia, pleurodynia."),
    ("-emia", "blood condition", "G", "Suffixes: conditions & disease", "Gk haima 'blood'. Anaemia, hyperglycaemia, uraemia."),
    ("-uria", "urine condition", "G", "Suffixes: conditions & disease", "Gk ouron. Haematuria, polyuria, dysuria."),
    ("-penia", "deficiency, abnormal reduction", "G", "Suffixes: conditions & disease", "Gk penia 'poverty'. Thrombocytopenia, leukopenia."),
    ("-megaly", "enlargement", "G", "Suffixes: conditions & disease", "Gk megas. Hepatomegaly, cardiomegaly, splenomegaly."),
    ("-malacia", "abnormal softening", "G", "Suffixes: conditions & disease", "Gk malakia. Osteomalacia, chondromalacia."),
    ("-sclerosis", "abnormal hardening", "G", "Suffixes: conditions & disease", "Gk skleros 'hard'. Atherosclerosis, multiple sclerosis."),
    ("-stenosis", "narrowing, stricture", "G", "Suffixes: conditions & disease", "Gk stenos. Aortic stenosis, pyloric stenosis."),
    ("-ectasis", "dilation, expansion", "G", "Suffixes: conditions & disease", "Gk ektasis. Bronchiectasis; atelectasis is incomplete expansion."),
    ("-ptosis", "drooping, sagging, prolapse", "G", "Suffixes: conditions & disease", "Gk ptosis 'a falling'. Blepharoptosis, nephroptosis. The p is silent initially."),
    ("-rrhea", "flow, discharge", "G", "Suffixes: conditions & disease", "Gk rhoia. Diarrhoea, rhinorrhoea, amenorrhoea. Note the double r."),
    ("-rrhagia", "bursting forth, excessive flow", "G", "Suffixes: conditions & disease", "Gk rhegnynai 'to burst'. Menorrhagia, haemorrhage."),
    ("-rrhexis", "rupture", "G", "Suffixes: conditions & disease", "Gk rhexis. Hysterorrhexis, karyorrhexis."),
    ("-cele", "hernia, protrusion, swelling", "G", "Suffixes: conditions & disease", "Gk kele. Hydrocele, cystocele, meningocele."),
    ("-oma", "tumour, mass, swelling", "G", "Suffixes: conditions & disease", "Gk -oma. Usually benign — carcinoma and melanoma are the malignant exceptions."),
    ("-edema", "swelling, accumulation of fluid", "G", "Suffixes: conditions & disease", "Gk oidema. Lymphoedema, papilloedema."),
    ("-spasm", "sudden involuntary contraction", "G", "Suffixes: conditions & disease", "Gk spasmos. Bronchospasm, blepharospasm."),
    ("-plegia", "paralysis", "G", "Suffixes: conditions & disease", "Gk plege 'stroke, blow'. Hemiplegia, paraplegia, quadriplegia."),
    ("-paresis", "partial paralysis, weakness", "G", "Suffixes: conditions & disease", "Gk paresis 'letting go'. Weaker than -plegia: hemiparesis."),
    ("-phobia", "abnormal fear, aversion", "G", "Suffixes: conditions & disease", "Gk phobos. Photophobia, agoraphobia."),
    ("-mania", "obsessive preoccupation", "G", "Suffixes: conditions & disease", "Gk mania 'madness'. Kleptomania, pyromania."),
    ("-lith", "stone, calculus", "G", "Suffixes: conditions & disease", "Gk lithos. Sialolith, urolith."),
    ("-lithiasis", "condition of stones", "G", "Suffixes: conditions & disease", "Cholelithiasis (gallstones), nephrolithiasis (kidney stones)."),
    ("-emesis", "vomiting", "G", "Suffixes: conditions & disease", "Gk emesis. Haematemesis — vomiting blood."),
    ("-pnea", "breathing", "G", "Suffixes: conditions & disease", "Gk pnoia. Apnoea, dyspnoea, orthopnoea, tachypnoea."),
    ("-phagia", "eating, swallowing", "G", "Suffixes: conditions & disease", "Gk phagein. Dysphagia (difficulty swallowing); contrast dysphasia (speech)."),
    ("-phasia", "speech", "G", "Suffixes: conditions & disease", "Gk phasis. Aphasia, dysphasia. One letter from -phagia and a very different sign."),
    ("-plasia", "formation, development, growth", "G", "Suffixes: conditions & disease", "Gk plasis. Hyperplasia (more cells), dysplasia (disordered), aplasia (none)."),
    ("-trophy", "nourishment, development", "G", "Suffixes: conditions & disease", "Gk trophe. Hypertrophy (bigger cells), atrophy (wasting)."),
    ("-genesis", "production, formation, origin", "G", "Suffixes: conditions & disease", "Gk genesis. Carcinogenesis, osteogenesis."),
    ("-genic", "producing, causing; produced by", "G", "Suffixes: conditions & disease", "Carcinogenic (causing cancer), iatrogenic (caused by treatment)."),
    ("-oid", "resembling, like", "G", "Suffixes: conditions & disease", "Gk eidos 'form'. Lipoid, mucoid, rheumatoid."),
    ("-lysis", "breakdown, destruction, separation", "G", "Suffixes: procedures & surgery", "Gk lysis 'loosening'. Haemolysis, dialysis, adhesiolysis."),
    ("-sepsis", "infection, putrefaction", "G", "Suffixes: conditions & disease", "Gk sepsis 'decay'. Antisepsis, asepsis."),
    ("-toxic", "poisonous, harmful to", "G", "Suffixes: conditions & disease", "Gk toxikon. Nephrotoxic, hepatotoxic, cytotoxic."),
    ("-ptysis", "spitting", "G", "Suffixes: conditions & disease", "Gk ptysis. Haemoptysis — coughing up blood from the lungs."),
    ("-stasis", "stopping, controlling, standing still", "G", "Suffixes: conditions & disease", "Gk stasis. Haemostasis, cholestasis, metastasis."),

    # --- procedures, surgery and instruments
    ("-ectomy", "surgical removal, excision", "G", "Suffixes: procedures & surgery", "Gk ektome 'a cutting out'. Appendectomy, nephrectomy."),
    ("-otomy", "incision, cutting into", "G", "Suffixes: procedures & surgery", "Gk tome. You cut in and close up again: tracheotomy, laparotomy."),
    ("-ostomy", "surgical creation of an opening", "G", "Suffixes: procedures & surgery", "Gk stoma 'mouth'. A lasting opening: colostomy, tracheostomy."),
    ("-plasty", "surgical repair or reshaping", "G", "Suffixes: procedures & surgery", "Gk plassein 'to mould'. Rhinoplasty, arthroplasty, angioplasty."),
    ("-pexy", "surgical fixation, suspension", "G", "Suffixes: procedures & surgery", "Gk pexis. Orchidopexy, nephropexy."),
    ("-desis", "surgical fusion, binding together", "G", "Suffixes: procedures & surgery", "Gk desis. Arthrodesis, pleurodesis."),
    ("-rrhaphy", "suture, surgical repair by stitching", "G", "Suffixes: procedures & surgery", "Gk rhaphe 'seam'. Herniorrhaphy, myorrhaphy."),
    ("-centesis", "surgical puncture to withdraw fluid", "G", "Suffixes: procedures & surgery", "Gk kentesis. Amniocentesis, thoracocentesis, paracentesis."),
    ("-scopy", "visual examination", "G", "Suffixes: procedures & surgery", "Gk skopein 'to look'. Endoscopy, colonoscopy, laparoscopy."),
    ("-scope", "instrument for viewing", "G", "Suffixes: procedures & surgery", "The instrument; -scopy is the procedure."),
    ("-graphy", "process of recording", "G", "Suffixes: procedures & surgery", "Gk graphein 'to write'. Radiography, angiography."),
    ("-gram", "the record or image produced", "G", "Suffixes: procedures & surgery", "The result; -graphy is the process; -graph the machine."),
    ("-graph", "instrument for recording", "G", "Suffixes: procedures & surgery", "Electrocardiograph — the machine that produces the electrocardiogram."),
    ("-metry", "process of measuring", "G", "Suffixes: procedures & surgery", "Gk metron. Spirometry, optometry, pelvimetry."),
    ("-meter", "instrument for measuring", "G", "Suffixes: procedures & surgery", "Thermometer, sphygmomanometer."),
    ("-therapy", "treatment", "G", "Suffixes: procedures & surgery", "Gk therapeia. Chemotherapy, radiotherapy, physiotherapy."),
    ("-tripsy", "crushing", "G", "Suffixes: procedures & surgery", "Gk tripsis. Lithotripsy — crushing a stone."),

    # --- specialties, agents and general
    ("-logy", "study of, science of", "G", "Suffixes: specialties & study", "Gk logos. Cardiology, histology, pathology."),
    ("-logist", "specialist in the study of", "G", "Suffixes: specialties & study", "The person: a cardiologist practises cardiology."),
    ("-iatry", "medical treatment, healing", "G", "Suffixes: specialties & study", "Gk iatros 'physician'. Psychiatry, podiatry."),
    ("-iatrics", "branch of medicine", "G", "Suffixes: specialties & study", "Paediatrics, geriatrics."),
    ("-ic", "pertaining to", "G", "Suffixes: specialties & study", "One of many adjective endings: gastric, hepatic, thoracic."),
    ("-al", "pertaining to", "L", "Suffixes: specialties & study", "Renal, duodenal, skeletal."),
    ("-ary", "pertaining to", "L", "Suffixes: specialties & study", "Pulmonary, coronary, urinary."),
    ("-ous", "pertaining to, full of", "L", "Suffixes: specialties & study", "Mucous, fibrous, venous."),
    ("-cyte", "cell", "G", "Suffixes: specialties & study", "Gk kytos 'hollow vessel'. Erythrocyte, leukocyte, hepatocyte."),
    ("-blast", "immature cell, germ cell", "G", "Suffixes: specialties & study", "Gk blastos 'sprout'. Osteoblast, myeloblast."),
    ("-clast", "cell that breaks down", "G", "Suffixes: specialties & study", "Gk klastos 'broken'. Osteoclast — resorbs bone; the opposite of osteoblast."),
    ("-poiesis", "formation, production", "G", "Suffixes: specialties & study", "Gk poiein 'to make'. Haematopoiesis, erythropoiesis."),
    ("-esthesia", "sensation, feeling", "G", "Suffixes: conditions & disease", "Gk aisthesis. Anaesthesia, paraesthesia, hyperaesthesia."),
    ("-kinesia", "movement", "G", "Suffixes: conditions & disease", "Gk kinesis. Bradykinesia, dyskinesia."),
    ("-tocia", "labour, childbirth", "G", "Suffixes: conditions & disease", "Gk tokos. Dystocia — difficult labour."),
    ("-para", "having borne offspring", "L", "Suffixes: specialties & study", "L parere 'to bring forth'. Primipara, multipara."),
    ("-gravida", "pregnant woman", "L", "Suffixes: specialties & study", "L gravidus 'laden'. Primigravida — pregnant for the first time."),
    ("-ase", "enzyme", "G", "Suffixes: specialties & study", "Amylase, lipase, protease."),
    ("-ose", "sugar, carbohydrate", "G", "Suffixes: specialties & study", "Glucose, lactose, fructose."),
    ("-tropic", "stimulating, acting on", "G", "Suffixes: specialties & study", "Gk tropos 'a turning'. Gonadotropic, inotropic."),
    ("-crine", "to secrete", "G", "Suffixes: specialties & study", "Gk krinein 'to separate'. Endocrine, exocrine."),
    ("-ectasia", "dilation, stretching", "G", "Suffixes: conditions & disease", "The -ectasis pair; both are used."),
]

# ---------------------------------------------------------------- roots

ROOTS = [
    # --- cardiovascular
    ("cardi/o", "heart", "G", "Cardiovascular", "Gk kardia. Carditis, cardiology, tachycardia."),
    ("angi/o", "vessel (blood or lymph)", "G", "Cardiovascular", "Gk angeion. Angiography, angioplasty, haemangioma."),
    ("vas/o", "vessel, duct", "L", "Cardiovascular", "L vas. Vasodilation, vasectomy."),
    ("vascul/o", "blood vessel", "L", "Cardiovascular", "L vasculum, a small vessel. Cardiovascular, vasculitis."),
    ("ven/o", "vein", "L", "Cardiovascular", "L vena. Venous, intravenous, venipuncture."),
    ("phleb/o", "vein", "G", "Cardiovascular", "Gk phleps. Phlebitis, phlebotomy."),
    ("arteri/o", "artery", "G", "Cardiovascular", "Gk arteria. Arteriosclerosis, arteriography."),
    ("aort/o", "aorta", "G", "Cardiovascular", "Gk aorte. Aortic stenosis, aortography."),
    ("atri/o", "atrium (upper heart chamber)", "L", "Cardiovascular", "L atrium 'entrance hall'. Atrioventricular."),
    ("ventricul/o", "ventricle (of heart or brain)", "L", "Cardiovascular", "L ventriculus 'little belly'. Ventriculography."),
    ("valvul/o", "valve", "L", "Cardiovascular", "L valvula. Valvuloplasty, valvulitis."),
    ("myocardi/o", "heart muscle", "G", "Cardiovascular", "my/o + cardi/o. Myocardial infarction, myocarditis."),
    ("pericardi/o", "pericardium, sac around the heart", "G", "Cardiovascular", "peri- + cardi/o. Pericarditis, pericardiocentesis."),
    ("thromb/o", "clot", "G", "Cardiovascular", "Gk thrombos. Thrombosis, thrombocyte, thrombolysis."),
    ("embol/o", "plug, embolus", "G", "Cardiovascular", "Gk embolos 'stopper'. Embolism, embolectomy."),
    ("ather/o", "fatty plaque, porridge-like deposit", "G", "Cardiovascular", "Gk athere 'gruel'. Atheroma, atherosclerosis."),
    ("sphygm/o", "pulse", "G", "Cardiovascular", "Gk sphygmos. Sphygmomanometer — the blood-pressure cuff."),
    ("coron/o", "heart, crown", "L", "Cardiovascular", "L corona 'crown' — the vessels encircle the heart. Coronary."),

    # --- respiratory
    ("pneum/o", "lung, air", "G", "Respiratory", "Gk pneumon/pneuma. Pneumothorax — air in the pleural space."),
    ("pneumon/o", "lung", "G", "Respiratory", "Pneumonia, pneumonectomy."),
    ("pulmon/o", "lung", "L", "Respiratory", "L pulmo. Pulmonary artery, cardiopulmonary."),
    ("bronch/o", "bronchus, airway", "G", "Respiratory", "Gk bronchos. Bronchitis, bronchoscopy, bronchodilator."),
    ("bronchiol/o", "bronchiole", "L", "Respiratory", "The small airways. Bronchiolitis."),
    ("trache/o", "trachea, windpipe", "G", "Respiratory", "Gk tracheia. Tracheostomy, tracheitis."),
    ("laryng/o", "larynx, voice box", "G", "Respiratory", "Gk larynx. Laryngitis, laryngoscopy."),
    ("pharyng/o", "pharynx, throat", "G", "Respiratory", "Gk pharynx. Pharyngitis, nasopharyngeal."),
    ("rhin/o", "nose", "G", "Respiratory", "Gk rhis/rhinos. Rhinitis, rhinorrhoea, rhinoplasty."),
    ("nas/o", "nose", "L", "Respiratory", "L nasus. Nasogastric tube, nasal."),
    ("sinus/o", "sinus, cavity", "L", "Respiratory", "L sinus 'hollow'. Sinusitis."),
    ("thorac/o", "chest, thorax", "G", "Respiratory", "Gk thorax. Thoracotomy, thoracocentesis."),
    ("pector/o", "chest", "L", "Respiratory", "L pectus. Angina pectoris, pectoral muscles."),
    ("pleur/o", "pleura, membrane around the lung", "G", "Respiratory", "Gk pleura 'side, rib'. Pleurisy, pleural effusion."),
    ("alveol/o", "alveolus, air sac", "L", "Respiratory", "L alveolus 'small hollow'. Alveolar gas exchange."),
    ("ox/i", "oxygen", "G", "Respiratory", "Hypoxia, pulse oximetry, anoxia."),
    ("capn/o", "carbon dioxide", "G", "Respiratory", "Gk kapnos 'smoke'. Hypercapnia, capnography."),
    ("spir/o", "to breathe", "L", "Respiratory", "L spirare. Spirometry, inspiration, expiration."),
    ("phren/o", "diaphragm; also mind", "G", "Respiratory", "Gk phren. Phrenic nerve (diaphragm); schizophrenia (mind)."),

    # --- gastrointestinal
    ("stomat/o", "mouth", "G", "Gastrointestinal", "Gk stoma. Stomatitis."),
    ("or/o", "mouth", "L", "Gastrointestinal", "L os/oris. Oral, oropharynx, per os."),
    ("gloss/o", "tongue", "G", "Gastrointestinal", "Gk glossa. Glossitis, hypoglossal nerve."),
    ("lingu/o", "tongue", "L", "Gastrointestinal", "L lingua. Sublingual, lingual artery."),
    ("odont/o", "tooth", "G", "Gastrointestinal", "Gk odous/odontos. Orthodontics, periodontal."),
    ("dent/i", "tooth", "L", "Gastrointestinal", "L dens/dentis. Dentist, dentine, edentulous."),
    ("gingiv/o", "gum", "L", "Gastrointestinal", "L gingiva. Gingivitis."),
    ("esophag/o", "oesophagus, gullet", "G", "Gastrointestinal", "Gk oisophagos. Oesophagitis, oesophagoscopy."),
    ("gastr/o", "stomach", "G", "Gastrointestinal", "Gk gaster. Gastritis, gastroscopy, gastrectomy."),
    ("enter/o", "intestine, especially the small intestine", "G", "Gastrointestinal", "Gk enteron. Enteritis, gastroenterology, parenteral."),
    ("duoden/o", "duodenum", "L", "Gastrointestinal", "L duodeni 'twelve each' — about twelve finger-breadths long."),
    ("jejun/o", "jejunum", "L", "Gastrointestinal", "L ieiunus 'empty' — it is usually found empty after death."),
    ("ile/o", "ileum, final part of the small intestine", "L", "Gastrointestinal", "L ileum. Ileostomy, ileitis. Do not confuse with ili/o, the hip bone."),
    ("col/o", "colon, large intestine", "G", "Gastrointestinal", "Gk kolon. Colostomy, colitis."),
    ("colon/o", "colon", "G", "Gastrointestinal", "Colonoscopy."),
    ("sigmoid/o", "sigmoid colon", "G", "Gastrointestinal", "Shaped like the Greek letter sigma. Sigmoidoscopy."),
    ("rect/o", "rectum", "L", "Gastrointestinal", "L rectus 'straight'. Rectal, rectocele."),
    ("proct/o", "anus and rectum", "G", "Gastrointestinal", "Gk proktos. Proctology, proctoscopy."),
    ("an/o", "anus", "L", "Gastrointestinal", "L anus 'ring'. Anal fissure, perianal."),
    ("cec/o", "caecum", "L", "Gastrointestinal", "L caecus 'blind' — a blind-ended pouch."),
    ("append/o", "appendix", "L", "Gastrointestinal", "L appendere 'to hang upon'. Appendectomy."),
    ("hepat/o", "liver", "G", "Gastrointestinal", "Gk hepar/hepatos. Hepatitis, hepatomegaly, hepatic."),
    ("chol/e", "bile, gall", "G", "Gastrointestinal", "Gk chole. Cholestasis, cholaemia."),
    ("cholecyst/o", "gallbladder", "G", "Gastrointestinal", "chol/e + cyst/o — the bile sac. Cholecystectomy."),
    ("choledoch/o", "common bile duct", "G", "Gastrointestinal", "Choledocholithiasis — a stone in the common bile duct."),
    ("pancreat/o", "pancreas", "G", "Gastrointestinal", "Gk pankreas 'all flesh'. Pancreatitis."),
    ("splen/o", "spleen", "G", "Gastrointestinal", "Gk splen. Splenomegaly, splenectomy."),
    ("abdomin/o", "abdomen", "L", "Gastrointestinal", "L abdomen. Abdominal, intra-abdominal."),
    ("lapar/o", "abdomen, abdominal wall", "G", "Gastrointestinal", "Gk lapara 'flank'. Laparotomy, laparoscopy."),
    ("periton/o", "peritoneum", "G", "Gastrointestinal", "Gk peritonaion. Peritonitis, peritoneal dialysis."),
    ("bil/i", "bile", "L", "Gastrointestinal", "L bilis. Biliary tree, bilirubin."),
    ("pylor/o", "pylorus, stomach outlet", "G", "Gastrointestinal", "Gk pyloros 'gatekeeper'. Pyloric stenosis."),

    # --- renal and urinary
    ("nephr/o", "kidney", "G", "Renal & urinary", "Gk nephros. Nephritis, nephrectomy, nephrology."),
    ("ren/o", "kidney", "L", "Renal & urinary", "L ren. Renal failure, renal artery — the anatomical adjective."),
    ("pyel/o", "renal pelvis", "G", "Renal & urinary", "Gk pyelos 'trough'. Pyelonephritis, pyelogram."),
    ("ureter/o", "ureter", "G", "Renal & urinary", "The tube from kidney to bladder. Ureteroscopy."),
    ("urethr/o", "urethra", "G", "Renal & urinary", "The tube from bladder to outside. Urethritis. One letter from ureter."),
    ("cyst/o", "bladder; sac, cyst", "G", "Renal & urinary", "Gk kystis. Cystitis, cystoscopy — but also cholecystitis (a sac)."),
    ("vesic/o", "bladder", "L", "Renal & urinary", "L vesica. Vesicoureteral reflux."),
    ("ur/o", "urine, urinary tract", "G", "Renal & urinary", "Gk ouron. Urology, urinalysis."),
    ("glomerul/o", "glomerulus", "L", "Renal & urinary", "L glomus 'ball of yarn'. Glomerulonephritis."),
    ("lith/o", "stone, calculus", "G", "Renal & urinary", "Gk lithos. Lithotripsy, nephrolithiasis."),

    # --- nervous system and psychiatry
    ("neur/o", "nerve, nervous system", "G", "Nervous system", "Gk neuron. Neurology, neuropathy, neuralgia."),
    ("encephal/o", "brain", "G", "Nervous system", "Gk enkephalos 'in the head'. Encephalitis, electroencephalogram."),
    ("cerebr/o", "cerebrum, brain", "L", "Nervous system", "L cerebrum. Cerebral cortex, cerebrovascular."),
    ("cerebell/o", "cerebellum", "L", "Nervous system", "L 'little brain'. Cerebellar ataxia."),
    ("mening/o", "meninges, membranes around the brain", "G", "Nervous system", "Gk meninx. Meningitis, meningioma."),
    ("myel/o", "spinal cord; also bone marrow", "G", "Nervous system", "Gk myelos 'marrow'. Myelitis (cord) but myeloma (marrow) — context decides."),
    ("radicul/o", "nerve root", "L", "Nervous system", "L radicula 'little root'. Radiculopathy — sciatica is one."),
    ("gangli/o", "ganglion, nerve cluster", "G", "Nervous system", "Gk ganglion. Ganglionectomy."),
    ("psych/o", "mind", "G", "Nervous system", "Gk psyche. Psychiatry, psychosis, psychology."),
    ("esthesi/o", "sensation, feeling", "G", "Nervous system", "Gk aisthesis. Anaesthesia, anaesthetist."),
    ("narc/o", "stupor, numbness", "G", "Nervous system", "Gk narke. Narcolepsy, narcotic."),
    ("somn/o", "sleep", "L", "Nervous system", "L somnus. Insomnia, somnolence."),
    ("hypn/o", "sleep", "G", "Nervous system", "Gk hypnos. Hypnosis, hypnotic drugs."),
    ("gli/o", "glue; neuroglia (supporting brain cells)", "G", "Nervous system", "Gk glia 'glue'. Glioma, glioblastoma."),
    ("dur/o", "dura mater, tough outer meninx", "L", "Nervous system", "L durus 'hard'. Epidural, subdural haematoma."),
    ("thalam/o", "thalamus", "G", "Nervous system", "Gk thalamos 'inner chamber'. Hypothalamus."),

    # --- musculoskeletal
    ("oste/o", "bone", "G", "Musculoskeletal", "Gk osteon. Osteoporosis, osteomyelitis, osteoarthritis."),
    ("my/o", "muscle", "G", "Musculoskeletal", "Gk mys. Myalgia, myopathy, myocardium."),
    ("muscul/o", "muscle", "L", "Musculoskeletal", "L musculus 'little mouse'. Musculoskeletal, intramuscular."),
    ("arthr/o", "joint", "G", "Musculoskeletal", "Gk arthron. Arthritis, arthroscopy, arthroplasty."),
    ("articul/o", "joint", "L", "Musculoskeletal", "L articulus. Articular cartilage, articulation."),
    ("chondr/o", "cartilage", "G", "Musculoskeletal", "Gk chondros. Chondromalacia, costochondritis."),
    ("tendin/o", "tendon", "L", "Musculoskeletal", "L tendo. Tendinitis, tendinopathy."),
    ("ten/o", "tendon", "G", "Musculoskeletal", "Gk tenon. Tenosynovitis, tenotomy."),
    ("ligament/o", "ligament", "L", "Musculoskeletal", "L ligare 'to bind'. Ligamentous injury."),
    ("burs/o", "bursa, fluid-filled sac", "L", "Musculoskeletal", "L bursa 'purse'. Bursitis."),
    ("synovi/o", "synovial membrane or fluid", "L", "Musculoskeletal", "Synovitis, tenosynovitis."),
    ("crani/o", "skull, cranium", "G", "Musculoskeletal", "Gk kranion. Craniotomy, craniofacial."),
    ("vertebr/o", "vertebra, spinal bone", "L", "Musculoskeletal", "L vertebra. Vertebral column, vertebroplasty."),
    ("spondyl/o", "vertebra, spine", "G", "Musculoskeletal", "Gk spondylos. Spondylitis, spondylolisthesis."),
    ("cost/o", "rib", "L", "Musculoskeletal", "L costa. Intercostal, costochondral."),
    ("stern/o", "sternum, breastbone", "G", "Musculoskeletal", "Gk sternon. Sternotomy, sternoclavicular."),
    ("clavicul/o", "clavicle, collarbone", "L", "Musculoskeletal", "L clavicula 'little key'. Clavicular fracture."),
    ("scapul/o", "scapula, shoulder blade", "L", "Musculoskeletal", "L scapula. Scapulothoracic."),
    ("humer/o", "humerus, upper arm bone", "L", "Musculoskeletal", "L humerus. Humeral head."),
    ("uln/o", "ulna, medial forearm bone", "L", "Musculoskeletal", "L ulna 'elbow'. Ulnar nerve."),
    ("carp/o", "wrist", "G", "Musculoskeletal", "Gk karpos. Carpal tunnel, metacarpal."),
    ("phalang/o", "phalanx, finger or toe bone", "G", "Musculoskeletal", "Gk phalanx, a line of soldiers. Phalangeal."),
    ("pelv/i", "pelvis", "L", "Musculoskeletal", "L pelvis 'basin'. Pelvimetry, pelvic floor."),
    ("ili/o", "ilium, flared hip bone", "L", "Musculoskeletal", "L ilium. Iliac crest. Not ile/o, the intestine."),
    ("ischi/o", "ischium, lower hip bone", "G", "Musculoskeletal", "Gk ischion. Ischial tuberosity — what you sit on."),
    ("femor/o", "femur, thigh bone", "L", "Musculoskeletal", "L femur. Femoral artery, femoroacetabular."),
    ("patell/o", "patella, kneecap", "L", "Musculoskeletal", "L patella 'small dish'. Patellar tendon."),
    ("tibi/o", "tibia, shin bone", "L", "Musculoskeletal", "L tibia 'flute'. Tibial plateau."),
    ("fibul/o", "fibula, lateral lower leg bone", "L", "Musculoskeletal", "L fibula 'clasp'. Fibular fracture."),
    ("calcane/o", "calcaneus, heel bone", "L", "Musculoskeletal", "L calcaneum. Calcaneal spur."),
    ("kyph/o", "hump, excessive outward curve", "G", "Musculoskeletal", "Gk kyphos. Kyphosis — a hunched thoracic spine."),
    ("lord/o", "inward curve, swayback", "G", "Musculoskeletal", "Gk lordos. Lordosis — the lumbar curve, exaggerated."),
    ("scoli/o", "crooked, lateral curvature", "G", "Musculoskeletal", "Gk skolios. Scoliosis — a sideways spinal curve."),

    # --- integumentary
    ("dermat/o", "skin", "G", "Integumentary", "Gk derma. Dermatitis, dermatology."),
    ("derm/o", "skin", "G", "Integumentary", "Epidermis, hypodermic, intradermal."),
    ("cutane/o", "skin", "L", "Integumentary", "L cutis. Subcutaneous, cutaneous."),
    ("epitheli/o", "epithelium, surface tissue", "G", "Integumentary", "Gk epi + thele. Epithelial cells."),
    ("kerat/o", "horny tissue, hard; also cornea", "G", "Integumentary", "Gk keras 'horn'. Keratosis (skin) but keratitis (cornea)."),
    ("melan/o", "black, dark", "G", "Integumentary", "Gk melas. Melanoma, melanin, melaena."),
    ("onych/o", "nail", "G", "Integumentary", "Gk onyx. Onychomycosis — a fungal nail infection."),
    ("ungu/o", "nail", "L", "Integumentary", "L unguis. Subungual haematoma."),
    ("trich/o", "hair", "G", "Integumentary", "Gk thrix/trichos. Trichotillomania."),
    ("pil/o", "hair", "L", "Integumentary", "L pilus. Pilonidal sinus, piloerection."),
    ("seb/o", "sebum, oil", "L", "Integumentary", "L sebum 'tallow'. Seborrhoea, sebaceous gland."),
    ("hidr/o", "sweat", "G", "Integumentary", "Gk hidros. Hyperhidrosis, anhidrosis. One letter from hydr/o, water."),
    ("squam/o", "scale, scaly", "L", "Integumentary", "L squama. Squamous cell carcinoma."),
    ("xer/o", "dry", "G", "Integumentary", "Gk xeros. Xerosis, xerostomia (dry mouth)."),
    ("erythemat/o", "redness", "G", "Integumentary", "Gk erythema. Erythematous rash."),

    # --- blood, immune and lymphatic
    ("hemat/o", "blood", "G", "Blood & immune", "Gk haima. Haematology, haematoma, haematuria."),
    ("hem/o", "blood", "G", "Blood & immune", "Haemoglobin, haemolysis, haemostasis."),
    ("erythr/o", "red", "G", "Blood & immune", "Gk erythros. Erythrocyte — the red blood cell."),
    ("leuk/o", "white", "G", "Blood & immune", "Gk leukos. Leukocyte, leukaemia, leukopenia."),
    ("lymph/o", "lymph, lymphatic tissue", "L", "Blood & immune", "L lympha 'clear water'. Lymphoma, lymphocyte."),
    ("lymphaden/o", "lymph node", "L", "Blood & immune", "lymph/o + aden/o. Lymphadenopathy — swollen nodes."),
    ("thym/o", "thymus gland", "G", "Blood & immune", "Gk thymos. Thymoma, thymectomy."),
    ("immun/o", "immune, protection", "L", "Blood & immune", "L immunis 'exempt'. Immunology, immunosuppression."),
    ("phag/o", "to eat, to swallow", "G", "Blood & immune", "Gk phagein. Phagocyte — a cell that engulfs debris."),
    ("ser/o", "serum, serous fluid", "L", "Blood & immune", "L serum 'whey'. Serology, serosanguinous."),
    ("fibrin/o", "fibrin, fibrous protein", "L", "Blood & immune", "L fibra. Fibrinolysis, fibrinogen."),
    ("coagul/o", "clotting", "L", "Blood & immune", "L coagulare. Anticoagulant, coagulopathy."),
    ("sider/o", "iron", "G", "Blood & immune", "Gk sideros. Sideroblastic anaemia, haemosiderin."),
    ("granul/o", "granule", "L", "Blood & immune", "L granulum. Granulocyte, granuloma."),

    # --- endocrine and metabolic
    ("aden/o", "gland", "G", "Endocrine & metabolic", "Gk aden. Adenoma, adenopathy, adenocarcinoma."),
    ("thyr/o", "thyroid gland", "G", "Endocrine & metabolic", "Gk thyreos 'shield'. Thyroidectomy, hyperthyroidism."),
    ("adren/o", "adrenal gland", "L", "Endocrine & metabolic", "L ad + ren — literally 'upon the kidney'. Adrenaline."),
    ("gluc/o", "glucose, sugar", "G", "Endocrine & metabolic", "Gk glykys 'sweet'. Glucose, gluconeogenesis."),
    ("glyc/o", "sugar, glucose", "G", "Endocrine & metabolic", "Hyperglycaemia, glycogen, glycosuria."),
    ("ket/o", "ketones, acetone", "G", "Endocrine & metabolic", "Ketoacidosis, ketonuria, ketogenic."),
    ("calc/i", "calcium", "L", "Endocrine & metabolic", "L calx 'lime'. Hypercalcaemia, calcification."),
    ("natr/o", "sodium", "L", "Endocrine & metabolic", "L natrium — hence Na. Hyponatraemia."),
    ("kal/i", "potassium", "L", "Endocrine & metabolic", "L kalium — hence K. Hyperkalaemia."),
    ("cortic/o", "cortex, outer layer", "L", "Endocrine & metabolic", "L cortex 'bark'. Corticosteroid, adrenocortical."),
    ("somat/o", "body", "G", "Endocrine & metabolic", "Gk soma. Somatic, somatotropin."),
    ("acr/o", "extremity, tip, top", "G", "Endocrine & metabolic", "Gk akron. Acromegaly — enlarged hands, feet and jaw."),
    ("crin/o", "to secrete", "G", "Endocrine & metabolic", "Endocrinology, exocrine."),
    ("insulin/o", "insulin", "L", "Endocrine & metabolic", "L insula 'island' — from the islets of Langerhans."),

    # --- reproductive and obstetric
    ("gynec/o", "woman, female", "G", "Reproductive & obstetric", "Gk gyne. Gynaecology, gynaecomastia."),
    ("andr/o", "male, masculine", "G", "Reproductive & obstetric", "Gk aner/andros. Androgen, andrology."),
    ("oophor/o", "ovary", "G", "Reproductive & obstetric", "Gk oon + phoros 'egg-bearing'. Oophorectomy."),
    ("ovari/o", "ovary", "L", "Reproductive & obstetric", "L ovarium. Ovarian cyst."),
    ("salping/o", "fallopian tube; also eustachian tube", "G", "Reproductive & obstetric", "Gk salpinx 'trumpet'. Salpingitis, salpingectomy."),
    ("hyster/o", "uterus, womb", "G", "Reproductive & obstetric", "Gk hystera. Hysterectomy, hysteroscopy."),
    ("uter/o", "uterus", "L", "Reproductive & obstetric", "L uterus. Uterine, intrauterine."),
    ("metr/o", "uterus", "G", "Reproductive & obstetric", "Gk metra. Endometrium, metrorrhagia."),
    ("vagin/o", "vagina", "L", "Reproductive & obstetric", "L vagina 'sheath'. Vaginitis, vaginal."),
    ("colp/o", "vagina", "G", "Reproductive & obstetric", "Gk kolpos. Colposcopy, colporrhaphy."),
    ("cervic/o", "neck; cervix of the uterus", "L", "Reproductive & obstetric", "L cervix 'neck'. Cervical — of the neck OR the cervix."),
    ("mamm/o", "breast", "L", "Reproductive & obstetric", "L mamma. Mammography, mammoplasty."),
    ("mast/o", "breast", "G", "Reproductive & obstetric", "Gk mastos. Mastectomy, mastitis, gynaecomastia."),
    ("lact/o", "milk", "L", "Reproductive & obstetric", "L lac/lactis. Lactation, prolactin."),
    ("galact/o", "milk", "G", "Reproductive & obstetric", "Gk gala/galaktos. Galactorrhoea, galactosaemia."),
    ("orchi/o", "testis", "G", "Reproductive & obstetric", "Gk orchis. Orchitis, orchiectomy, cryptorchidism."),
    ("prostat/o", "prostate gland", "G", "Reproductive & obstetric", "Gk prostates 'one standing before'. Prostatitis, prostatectomy."),
    ("spermat/o", "sperm, seed", "G", "Reproductive & obstetric", "Gk sperma. Spermatogenesis, oligospermia."),
    ("balan/o", "glans penis", "G", "Reproductive & obstetric", "Gk balanos 'acorn'. Balanitis."),
    ("men/o", "menstruation, month", "G", "Reproductive & obstetric", "Gk men 'month'. Menorrhagia, amenorrhoea, menopause."),
    ("nat/o", "birth", "L", "Reproductive & obstetric", "L natus 'born'. Neonate, prenatal, postnatal."),
    ("toc/o", "labour, childbirth", "G", "Reproductive & obstetric", "Gk tokos. Dystocia, oxytocin."),
    ("fet/o", "fetus", "L", "Reproductive & obstetric", "L fetus 'offspring'. Fetal monitoring."),
    ("embry/o", "embryo", "G", "Reproductive & obstetric", "Gk embryon. Embryology, embryonic."),
    ("amni/o", "amnion, fetal sac", "G", "Reproductive & obstetric", "Gk amnion. Amniocentesis, amniotic fluid."),
    ("placent/o", "placenta", "L", "Reproductive & obstetric", "L placenta 'flat cake'. Placenta praevia, placental abruption."),
    ("episi/o", "vulva", "G", "Reproductive & obstetric", "Gk epision. Episiotomy."),

    # --- eye, ear, nose and throat
    ("ophthalm/o", "eye", "G", "Eye & ENT", "Gk ophthalmos. Ophthalmology, exophthalmos."),
    ("ocul/o", "eye", "L", "Eye & ENT", "L oculus. Ocular, intraocular, oculomotor."),
    ("opt/o", "vision, sight", "G", "Eye & ENT", "Gk optos. Optometry, optic nerve."),
    ("corne/o", "cornea", "L", "Eye & ENT", "L cornu 'horn'. Corneal abrasion."),
    ("irid/o", "iris", "G", "Eye & ENT", "Gk iris 'rainbow'. Iridectomy, iritis."),
    ("retin/o", "retina", "L", "Eye & ENT", "L rete 'net'. Retinopathy, retinal detachment."),
    ("scler/o", "hard; sclera, white of the eye", "G", "Eye & ENT", "Gk skleros. Scleritis (eye) but scleroderma (hard skin)."),
    ("conjunctiv/o", "conjunctiva", "L", "Eye & ENT", "L coniungere 'to join'. Conjunctivitis."),
    ("lacrim/o", "tear, tear duct", "L", "Eye & ENT", "L lacrima. Lacrimal gland."),
    ("dacry/o", "tear, tear duct", "G", "Eye & ENT", "Gk dakryon. Dacryocystitis."),
    ("blephar/o", "eyelid", "G", "Eye & ENT", "Gk blepharon. Blepharitis, blepharoplasty, blepharoptosis."),
    ("phac/o", "lens of the eye", "G", "Eye & ENT", "Gk phakos 'lentil'. Phacoemulsification — cataract surgery."),
    ("ot/o", "ear", "G", "Eye & ENT", "Gk ous/otos. Otitis, otoscope, otorrhoea."),
    ("aur/i", "ear", "L", "Eye & ENT", "L auris. Aural, auricle."),
    ("tympan/o", "eardrum, middle ear", "G", "Eye & ENT", "Gk tympanon 'drum'. Tympanostomy, tympanic membrane."),
    ("myring/o", "tympanic membrane", "L", "Eye & ENT", "Myringotomy — incising the eardrum to drain the middle ear."),
    ("audi/o", "hearing", "L", "Eye & ENT", "L audire 'to hear'. Audiology, audiometry."),
    ("acous/o", "hearing, sound", "G", "Eye & ENT", "Gk akouein. Acoustic neuroma, presbyacusis."),
    ("cochle/o", "cochlea", "G", "Eye & ENT", "Gk kochlias 'snail'. Cochlear implant."),
    ("vestibul/o", "vestibule of the inner ear", "L", "Eye & ENT", "L vestibulum 'entrance'. Vestibular — balance."),

    # --- general roots, colours and qualities
    ("cyt/o", "cell", "G", "General & colour roots", "Gk kytos. Cytology, cytoplasm, cytotoxic."),
    ("hist/o", "tissue", "G", "General & colour roots", "Gk histos 'web'. Histology, histopathology."),
    ("path/o", "disease, suffering", "G", "General & colour roots", "Gk pathos. Pathology, pathogen, pathogenesis."),
    ("carcin/o", "cancer, carcinoma", "G", "General & colour roots", "Gk karkinos 'crab'. Carcinogen, carcinoma."),
    ("onc/o", "tumour, mass", "G", "General & colour roots", "Gk onkos. Oncology, oncogene."),
    ("sarc/o", "flesh, connective tissue", "G", "General & colour roots", "Gk sarx. Sarcoma — a cancer of connective tissue."),
    ("lip/o", "fat, lipid", "G", "General & colour roots", "Gk lipos. Lipoma, hyperlipidaemia, liposuction."),
    ("adip/o", "fat", "L", "General & colour roots", "L adeps. Adipose tissue."),
    ("steat/o", "fat, sebum", "G", "General & colour roots", "Gk stear. Steatosis, steatorrhoea — fatty stools."),
    ("hydr/o", "water, fluid", "G", "General & colour roots", "Gk hydor. Hydrocephalus, dehydration, hydronephrosis."),
    ("pyr/o", "fever, heat, fire", "G", "General & colour roots", "Gk pyr. Antipyretic, pyrexia."),
    ("therm/o", "heat, temperature", "G", "General & colour roots", "Gk therme. Hypothermia, thermometer."),
    ("cry/o", "cold", "G", "General & colour roots", "Gk kryos. Cryotherapy, cryoprecipitate."),
    ("py/o", "pus", "G", "General & colour roots", "Gk pyon. Pyuria, empyema, pyogenic. Not pyr/o, fever."),
    ("bacteri/o", "bacteria", "G", "General & colour roots", "Gk bakterion 'small staff'. Bacteriuria, bactericidal."),
    ("myc/o", "fungus", "G", "General & colour roots", "Gk mykes. Mycosis, onychomycosis, mycology."),
    ("vir/o", "virus", "L", "General & colour roots", "L virus 'poison'. Virology, antiviral, viraemia."),
    ("toxic/o", "poison, toxin", "G", "General & colour roots", "Gk toxikon. Toxicology, toxaemia."),
    ("necr/o", "death (of tissue)", "G", "General & colour roots", "Gk nekros. Necrosis, necrotising fasciitis."),
    ("geront/o", "old age, the elderly", "G", "General & colour roots", "Gk geron. Gerontology, geriatrics."),
    ("ped/o", "child", "G", "General & colour roots", "Gk pais/paidos. Paediatrics. Beware: L pes/pedis is 'foot'."),
    ("morph/o", "form, shape", "G", "General & colour roots", "Gk morphe. Morphology, dysmorphic, pleomorphic."),
    ("phon/o", "sound, voice", "G", "General & colour roots", "Gk phone. Dysphonia, phonocardiogram."),
    ("chrom/o", "colour", "G", "General & colour roots", "Gk chroma. Chromosome, hyperchromic."),
    ("bi/o", "life, living", "G", "General & colour roots", "Gk bios. Biopsy, biology, antibiotic."),
    ("cyan/o", "blue", "G", "General & colour roots", "Gk kyanos. Cyanosis — blue discolouration from low oxygen."),
    ("xanth/o", "yellow", "G", "General & colour roots", "Gk xanthos. Xanthoma, xanthelasma."),
    ("chlor/o", "green", "G", "General & colour roots", "Gk chloros. Chlorosis, chloride."),
    ("poli/o", "grey", "G", "General & colour roots", "Gk polios. Poliomyelitis — inflammation of the grey matter of the cord."),
    ("alb/o", "white", "L", "General & colour roots", "L albus. Albinism, albumin."),
    ("cirrh/o", "orange-yellow, tawny", "G", "General & colour roots", "Gk kirrhos — the colour of the diseased liver. Cirrhosis."),
    ("malign/o", "bad, harmful, cancerous", "L", "General & colour roots", "L malignus. Malignant — invasive and destructive."),
    ("benign/o", "harmless, not cancerous", "L", "General & colour roots", "L benignus 'kind'. Benign — localised and non-invasive."),
    ("iatr/o", "physician, treatment", "G", "General & colour roots", "Gk iatros. Iatrogenic — caused by medical treatment."),
    ("noct/i", "night", "L", "General & colour roots", "L nox/noctis. Nocturia, nocturnal."),
    ("viscer/o", "internal organ", "L", "Anatomical position & planes", "L viscera. Visceral pain, eviscerate."),
    ("cephal/o", "head", "G", "Anatomical position & planes", "Gk kephale. Cephalic, hydrocephalus, encephalopathy."),
]

# Greek/Latin pairs for the same structure. The generator links both directions
# and fails if a form is missing from ROOTS, so a typo cannot ship.
DOUBLETS = [
    ("nephr/o", "ren/o", "kidney"),
    ("phleb/o", "ven/o", "vein"),
    ("pneumon/o", "pulmon/o", "lung"),
    ("rhin/o", "nas/o", "nose"),
    ("thorac/o", "pector/o", "chest"),
    ("stomat/o", "or/o", "mouth"),
    ("gloss/o", "lingu/o", "tongue"),
    ("odont/o", "dent/i", "tooth"),
    ("proct/o", "rect/o", "rectum / anus"),
    ("cyst/o", "vesic/o", "bladder"),
    ("encephal/o", "cerebr/o", "brain"),
    ("hypn/o", "somn/o", "sleep"),
    ("my/o", "muscul/o", "muscle"),
    ("arthr/o", "articul/o", "joint"),
    ("spondyl/o", "vertebr/o", "vertebra"),
    ("dermat/o", "cutane/o", "skin"),
    ("onych/o", "ungu/o", "nail"),
    ("trich/o", "pil/o", "hair"),
    ("oophor/o", "ovari/o", "ovary"),
    ("hyster/o", "uter/o", "uterus"),
    ("colp/o", "vagin/o", "vagina"),
    ("mast/o", "mamm/o", "breast"),
    ("galact/o", "lact/o", "milk"),
    ("ophthalm/o", "ocul/o", "eye"),
    ("dacry/o", "lacrim/o", "tear"),
    ("ot/o", "aur/i", "ear"),
    ("acous/o", "audi/o", "hearing"),
    ("lip/o", "adip/o", "fat"),
    ("hidr/o", "sudor/i", "sweat"),
    # added after the bone report and the audit that followed
    ("oste/o", "oss/e", "bone"),
    ("hemat/o", "sanguin/o", "blood"),
    ("cephal/o", "capit/o", "head"),
    ("neur/o", "nerv/o", "nerve"),
    ("myel/o", "medull/o", "bone marrow"),
    ("somat/o", "corpor/o", "body"),
    ("hydr/o", "aqu/e", "water"),
    ("lith/o", "calcul/o", "stone"),
    ("orchi/o", "test/o", "testis"),
    ("aden/o", "glandul/o", "gland"),
    # both halves were already in the deck but had never been linked
    ("cyt/o", "cellul/o", "cell"),
    ("leuk/o", "alb/o", "white"),
    ("phon/o", "son/o", "sound"),
    ("ten/o", "tendin/o", "tendon"),
    ("chol/e", "bil/i", "bile"),
    ("lapar/o", "abdomin/o", "abdomen"),
]

# sudor/i is only needed as the Latin half of a doublet; add it here so the
# doublet check has both sides without cluttering the Integumentary root list.
# --- Latin counterparts that were missing ---------------------------------
# Found after a report that bone appeared as Greek oste/o only. An audit for
# glosses where Greek and Latin both name the same structure turned up the rest;
# without these the doublet drill could only ever ask half the pairs.
ROOTS += [
    ("oss/e", "bone", "L", "Musculoskeletal",
     "L os, ossis 'bone'. Osseous tissue is bone tissue; the ear ossicles are the three smallest bones in the body. Also written oss/i."),
    ("sanguin/o", "blood", "L", "Blood & immune",
     "L sanguis 'blood'. Sanguineous drainage is blood-stained; consanguinity is blood relationship."),
    ("capit/o", "head", "L", "Anatomical position & planes",
     "L caput, capitis 'head'. The capitate is the head-shaped wrist bone; decapitation is removal of the head."),
    ("nerv/o", "nerve", "L", "Nervous system",
     "L nervus 'sinew, nerve'. Innervation is the nerve supply to a part."),
    ("medull/o", "bone marrow; the inner part of an organ", "L", "Musculoskeletal",
     "L medulla 'marrow, pith'. The medullary cavity holds bone marrow; the adrenal medulla is the inner part of that gland."),
    ("corpor/o", "body", "L", "Anatomical position & planes",
     "L corpus, corporis 'body'. The corpus callosum joins the two halves of the brain."),
    ("aqu/e", "water", "L", "General & colour roots",
     "L aqua 'water'. The aqueous humour is the watery fluid at the front of the eye."),
    ("calcul/o", "stone", "L", "Renal & urinary",
     "L calculus 'pebble', once used for counting. A renal calculus is a kidney stone."),
    ("test/o", "testis", "L", "Reproductive & obstetric",
     "L testis. Testicular torsion is a surgical emergency; testosterone is the main male hormone."),
    ("glandul/o", "gland", "L", "Endocrine & metabolic",
     "L glandula 'little acorn'. Glandular tissue is made of secreting cells."),
]

ROOTS.append(("sudor/i", "sweat", "L", "Integumentary", "L sudor. Sudoriferous glands; diaphoresis is the Greek-derived clinical term."))
